<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML Reporting - Search bar</name>
   <tag></tag>
   <elementGuidId>1698f126-270b-4689-98b1-69dd84a30dbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_applicant_aml_checks']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_applicant_aml_checks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c4cc245-5bad-4403-a08b-80eb202542ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d4f74bd-b7f7-41ef-bf0a-0aca6ad82b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_applicant_aml_checks</value>
      <webElementGuid>3519fe1d-d9ec-42f0-81e5-d8aca7184593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_applicant_aml_checks</value>
      <webElementGuid>ab456c6e-1359-4074-95f9-c501b5db5cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>a3fca0c1-8c40-4157-8b3c-21ddf8c937e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name, address or ref</value>
      <webElementGuid>c5cb3540-18b8-4b64-b8a7-183a88eb8df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_applicant_aml_checks&quot;)</value>
      <webElementGuid>53e11238-777a-4cec-b202-390d32c7e018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_applicant_aml_checks']</value>
      <webElementGuid>f218742b-7e76-4000-8518-dccaa58350ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/input[2]</value>
      <webElementGuid>ff61ad1a-2e51-4744-9e07-9ccc6a26c3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>19347156-3c24-409c-8c23-e7a9e166c248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_applicant_aml_checks' and @id = 'search_applicant_aml_checks' and @placeholder = 'Search by name, address or ref']</value>
      <webElementGuid>5ad15b7c-f227-489f-904e-be63e8013748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
