<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML Reporting - Cancel (x) bt</name>
   <tag></tag>
   <elementGuidId>cf4e6f82-0848-486a-9f98-69eaefe358cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='✕']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.string.optional.cancelhover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8321bbea-0062-42b7-821e-4a75462893a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>76758c22-89c1-4623-8243-9fbcca00953c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional cancelhover</value>
      <webElementGuid>b19d1c24-bd87-4998-8986-eaff952ced27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5527b2f2-eb5e-4267-9fb3-9fab5cf8f652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>482ff0be-4597-4164-81cb-be1abf5a2ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetsearch_applicant_aml_check&quot;)/a[1]/input[@class=&quot;string optional cancelhover&quot;]</value>
      <webElementGuid>8aa65d1a-c25f-4611-8d97-b1789426fd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='✕']</value>
      <webElementGuid>dc929f41-8699-467e-9544-4b12be707b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='resetsearch_applicant_aml_check']/a/input</value>
      <webElementGuid>4fb944dd-1489-4d7a-bb58-e99e6b2ed7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>f1bd57dd-f23d-4835-86c5-5952ecc62657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>48cfdcbf-320e-451d-a6cc-ea78a0ff043b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
