<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Properties-Onboarding - Search bar</name>
   <tag></tag>
   <elementGuidId>95d1e213-86e8-49ad-9751-dbac0b006902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_tenancies']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_tenancies</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a882d367-474c-4f42-ae7a-6a3af360812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78f3f60d-800f-44a2-9505-b39ef4f782bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_tenancies</value>
      <webElementGuid>92ed1e6d-2cd3-43e9-9d41-8865a4ede2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_tenancies</value>
      <webElementGuid>44af3ac0-278a-4270-b94f-c852a86ce9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>705b323e-b138-4fad-b83e-a4a4b19e3db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by landlord, address or UTR</value>
      <webElementGuid>42baa5a4-72d9-4b4d-9dab-1e55926b1ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_tenancies&quot;)</value>
      <webElementGuid>c49d88b7-031f-4c3b-b0cf-c3c5b2559173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_tenancies']</value>
      <webElementGuid>2f8b7f13-0ba5-4f7f-a462-2b34197e83f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab2']/div/div/form/input[2]</value>
      <webElementGuid>d2670843-aede-44b2-9370-06638aab8fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/input[2]</value>
      <webElementGuid>fef7aa45-9250-4103-b8d2-530d202a7be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_tenancies' and @id = 'search_tenancies' and @placeholder = 'Search by landlord, address or UTR']</value>
      <webElementGuid>af07cd90-0486-4d0c-a6e0-c9c9efdc194e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
