<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gmail - 3 dots</name>
   <tag></tag>
   <elementGuidId>83987746-904f-4042-96b3-defc683e29db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':o4']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ajT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b9a91327-53ee-4d32-9793-6186864db56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajT</value>
      <webElementGuid>7227d707-da9d-47a5-9878-0b1f6a83c414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif</value>
      <webElementGuid>a830cbf9-e07d-43c6-93ef-8effe0de1b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:o4&quot;)/img[@class=&quot;ajT&quot;]</value>
      <webElementGuid>4f95b244-95d2-4a35-b235-db445c9f8bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':o4']/img</value>
      <webElementGuid>11cb87f5-6753-4f98-b98e-31d93be40a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/img</value>
      <webElementGuid>872137f7-6470-45a3-ad77-86cf14d2fcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif']</value>
      <webElementGuid>d4786eb1-34b0-4f65-a31a-eb2f070d0d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
