<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agreed_AgencyTerms</name>
   <tag></tag>
   <elementGuidId>cd613db0-b0ec-40c9-ba40-231dbca36a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.progresssectiontext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='checkstabletable']/tbody/tr[2]/td[2]/p/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>822cea23-18d3-4706-81bf-a260b727363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>progresssectiontext</value>
      <webElementGuid>334ee70b-61ba-4100-b9bd-9cef4b1cb1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tenancy/tenancy_terms?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010</value>
      <webElementGuid>94e24a5d-edad-42ea-af2e-f5d913ed18cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agreed</value>
      <webElementGuid>3a8d7765-aa45-4d48-af7b-cd7c9881e003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/span[1]/div[@id=&quot;checkstablecontainer&quot;]/div[@id=&quot;checkstable&quot;]/table[@id=&quot;checkstabletable&quot;]/tbody[1]/tr[2]/td[2]/p[@class=&quot;prequalificationstyling prequalificationstylingsmall sectioncenter&quot;]/span[1]/a[@class=&quot;progresssectiontext&quot;]</value>
      <webElementGuid>89370a7b-2ba9-4200-a6e7-f3ad19971fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable']/tbody/tr[2]/td[2]/p/span/a</value>
      <webElementGuid>f3cdf7b0-692b-44b6-adb2-8d4ca4bdc8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agreed')]</value>
      <webElementGuid>4029e374-e7ed-40a0-b0cc-c85d6607f85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test'])[1]/following::a[1]</value>
      <webElementGuid>981d6554-ea78-4b98-9de4-81486ea215f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Starts 16/11/2024'])[1]/following::a[1]</value>
      <webElementGuid>de5711e8-645c-4565-8d34-b6449161f508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreed'])[2]/preceding::a[1]</value>
      <webElementGuid>b830856c-ed27-4033-a15e-95f59c47a791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[3]</value>
      <webElementGuid>2abff5c3-f056-4245-a133-22f03d17fc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agreed']/parent::*</value>
      <webElementGuid>fefc7a87-cba3-463c-8e10-6e0d03cc0b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tenancy/tenancy_terms?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010')]</value>
      <webElementGuid>0858dc0c-b04e-4814-8345-0cff761031d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>011b69d3-3f0f-46ad-b192-b911ab36762e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tenancy/tenancy_terms?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010' and (text() = 'Agreed' or . = 'Agreed')]</value>
      <webElementGuid>2d55ad35-4297-466b-9e4c-ece43b0016e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
