<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agreed_ReferencingCriteria</name>
   <tag></tag>
   <elementGuidId>8dd8a1ed-e77e-4a39-be44-6bd802d463c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > p.prequalificationstyling.prequalificationstylingsmall.sectioncenter > span > a.progresssectiontext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='checkstabletable']/tbody/tr[2]/td[3]/p/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5eec1c6-5438-4b45-a453-ae64d915b95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>progresssectiontext</value>
      <webElementGuid>fc763397-6e06-47d9-b148-f282971f2505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tenancy/referencing_criteria?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010</value>
      <webElementGuid>9411f7d8-3341-4a3e-9aa1-cfce47565bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agreed</value>
      <webElementGuid>0a4fb9cf-3d99-4171-ac9d-581c722dca20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/span[1]/div[@id=&quot;checkstablecontainer&quot;]/div[@id=&quot;checkstable&quot;]/table[@id=&quot;checkstabletable&quot;]/tbody[1]/tr[2]/td[3]/p[@class=&quot;prequalificationstyling prequalificationstylingsmall sectioncenter&quot;]/span[1]/a[@class=&quot;progresssectiontext&quot;]</value>
      <webElementGuid>cebfb77d-72de-42d9-a2e8-aa9a0d1b3c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable']/tbody/tr[2]/td[3]/p/span/a</value>
      <webElementGuid>fedddc9c-cca9-46ef-b5f0-e2be2a355414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Agreed')])[2]</value>
      <webElementGuid>563967b4-e96e-4f86-9cd2-0e6396b2c1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreed'])[1]/following::a[1]</value>
      <webElementGuid>ed7ecc7f-5dad-4c6a-b228-a4c20a98da7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Test'])[1]/following::a[2]</value>
      <webElementGuid>7f7cd901-c4e0-43be-ada7-feec4e26ed35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[2]</value>
      <webElementGuid>0d596191-3ac7-4870-9c3d-95cf2daa977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/preceding::a[6]</value>
      <webElementGuid>ef603e2b-bbe8-4c38-8f95-458ec75beebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tenancy/referencing_criteria?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010')]</value>
      <webElementGuid>b8c3d552-d8a4-4674-9fe1-81136bdf5516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p/span/a</value>
      <webElementGuid>20306613-1b7a-4fe8-a9ec-1d121ea69cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tenancy/referencing_criteria?tenancy_ref=27fd209441899fba4fe186912a653873916b91427f098e96bbfa12b5b79d&amp;invite_id=15010' and (text() = 'Agreed' or . = 'Agreed')]</value>
      <webElementGuid>0c9f9882-e39e-4b2e-b877-4666571bfa81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
