<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CANCEL TENANCY</name>
   <tag></tag>
   <elementGuidId>225fe94f-c934-406b-9904-d4386326b61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancel_tenancy_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cancel_tenancy_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7daf74a8-c4bc-49a9-816e-eee1ad33d535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trigger_popup_fricc3</value>
      <webElementGuid>6494fa2c-681e-4696-a0d3-7516f820ba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cancel_tenancy</value>
      <webElementGuid>7008583a-511c-4e18-bbcc-a6affc315dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1320b53a-8dbf-43b8-ac34-8e128d26ff6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel_tenancy_id</value>
      <webElementGuid>f166e8dc-41f7-48dd-8ae3-26054e0d3fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCEL TENANCY</value>
      <webElementGuid>83ae8684-6c15-44e6-bdf4-dd3f6508ed2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel_tenancy_id&quot;)</value>
      <webElementGuid>0459957a-f262-4ff5-ac6b-678f64dad239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cancel_tenancy_id']</value>
      <webElementGuid>d4ad2c08-488c-4604-96c2-62b7ee87761e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkstable']/div[2]/p[3]/a</value>
      <webElementGuid>3aafd8b9-ff6e-4b48-b61e-c2606fc96ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CANCEL TENANCY')]</value>
      <webElementGuid>cce40896-bf5a-423e-a3e0-332629a6cccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT TENANCY'])[1]/following::a[1]</value>
      <webElementGuid>43c01b1f-0bd3-4fcf-a3e8-d3df63cdfa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TENANCY AGREEMENT'])[1]/following::a[2]</value>
      <webElementGuid>61e182a3-02e8-4b4a-aa45-4dcc6e6b3875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D4139'])[1]/preceding::a[1]</value>
      <webElementGuid>850ec4bf-7d92-4114-b6db-8fd159f77dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to cancel this tenancy?'])[1]/preceding::a[1]</value>
      <webElementGuid>42768936-da59-4ee6-85fd-69583376130e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCEL TENANCY']/parent::*</value>
      <webElementGuid>7e50052f-c8a2-410a-b27a-0fae9bb516ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/p[3]/a</value>
      <webElementGuid>a0c76264-dc27-4ac8-90a1-39d0498bdc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cancel_tenancy_id' and (text() = 'CANCEL TENANCY' or . = 'CANCEL TENANCY')]</value>
      <webElementGuid>3b21a2e2-1564-4c22-b269-d34cba30b6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
