<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NewTenancy_3B54D</name>
   <tag></tag>
   <elementGuidId>e2b4518a-c53f-4de1-893f-dcf18ce8f0d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkstabletable_tenancies > tbody > tr:nth-of-type(2) > td:nth-of-type(6) > p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='checkstabletable_tenancies']/tbody/tr[2]/td[6]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5033f8e-9e82-476e-871b-b750ded1996c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent/property_in_tenancy?tenancyid=d413934f29196b2d0b9a764ac6841391e70c4db34f0f292b54b8855327a4</value>
      <webElementGuid>c0f6984e-db63-4d17-9b19-75f98ee25011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>property_in_tenancy</value>
      <webElementGuid>9c95cc3f-f69e-4f54-b8db-9fec014b30cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>12e1ed75-1f09-4d2a-ab75-7a47bfa2a273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tenancy Agreement</value>
      <webElementGuid>a61f32a5-712b-45e0-b9ed-4a683e97a42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkstabletable_tenancies&quot;)/tbody[1]/tr[2]/td[6]/p[1]/a[1]</value>
      <webElementGuid>f10cdd62-ab84-4209-a3eb-a72bd000129c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable_tenancies']/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>34aa6430-73a8-479f-984e-23499a4dccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tenancy Agreement')]</value>
      <webElementGuid>e4820030-c631-495d-baa5-a92e7385a997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ends 14/07/2025'])[1]/following::a[1]</value>
      <webElementGuid>3b499f92-f03f-4611-ad33-de9b4faefcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='carlo lands'])[1]/following::a[2]</value>
      <webElementGuid>28e93bdd-8ac7-4c2b-b110-f0d647915644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat 5, Loona Apartments, 43A Golders Gree... NW11 8EE'])[3]/preceding::a[2]</value>
      <webElementGuid>2f30dde7-6c6a-4897-8e15-12850e030997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat 5, Loon... NW11 8EE'])[3]/preceding::a[3]</value>
      <webElementGuid>6b7bafa6-57ce-4433-a4d6-bdec278bd474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/agent/property_in_tenancy?tenancyid=d413934f29196b2d0b9a764ac6841391e70c4db34f0f292b54b8855327a4')])[2]</value>
      <webElementGuid>46fd0eca-8be4-45ba-ac40-1fd93bea2a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>bdab4631-aa71-4a96-b805-b03591a895e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/agent/property_in_tenancy?tenancyid=d413934f29196b2d0b9a764ac6841391e70c4db34f0f292b54b8855327a4' and (text() = 'Tenancy Agreement' or . = 'Tenancy Agreement')]</value>
      <webElementGuid>1d537fed-5e50-490c-982f-69d77058d5de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
