<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registered_Deposit</name>
   <tag></tag>
   <elementGuidId>2576186f-acea-4568-b263-59e7c9a2c014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7) > p.sectioncenter.progresssectiontext > span > a.progresssectiontext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='show_full_deposit()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50b97fa5-47ef-42e8-ae31-50d05708fcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>progresssectiontext</value>
      <webElementGuid>2eb2aa46-af1f-4ed5-8624-cc8fb2ea9660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ced5da0b-c5e8-4e8a-837e-55f6ead1e8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_full_deposit()</value>
      <webElementGuid>1b84fc49-68ce-4daa-94f7-eed1424d88b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registered</value>
      <webElementGuid>61e5cac7-6800-4543-96d3-ee2673ffebd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/span[1]/div[@id=&quot;checkstablecontainer&quot;]/div[@id=&quot;checkstable&quot;]/table[@id=&quot;checkstabletable&quot;]/tbody[1]/tr[2]/td[7]/p[@class=&quot;sectioncenter progresssectiontext&quot;]/span[1]/a[@class=&quot;progresssectiontext&quot;]</value>
      <webElementGuid>b2db5f01-502d-46ef-8001-79eabb77f162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_full_deposit()']</value>
      <webElementGuid>1581e066-042f-4257-909c-0d806f2f67da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable']/tbody/tr[2]/td[7]/p/span/a</value>
      <webElementGuid>46ff9d98-c545-4487-8228-3dcb1cb49d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Registered')]</value>
      <webElementGuid>2d1c36be-06bb-4a89-9e33-d320a70d19cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::a[2]</value>
      <webElementGuid>d6ebe8d6-b6fc-44f5-802e-21f7dc434424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreed'])[2]/following::a[4]</value>
      <webElementGuid>b33297db-1421-4ec6-a6db-9bc6eb60c0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/preceding::a[2]</value>
      <webElementGuid>9371936b-249e-4759-9461-b0c2e0ceb19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update'])[1]/preceding::a[2]</value>
      <webElementGuid>7a272d54-473c-4efd-bc0d-25ac1b255715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registered']/parent::*</value>
      <webElementGuid>861547d0-be9f-454a-8313-041323538aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>e8de8f29-15e0-4bac-a5d1-163836bff045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/p/span/a</value>
      <webElementGuid>41c36cf4-cbd2-448e-9407-116696d3baa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Registered' or . = 'Registered')]</value>
      <webElementGuid>af865ce9-e867-462e-b6ba-3659790d81c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
