<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Received_HoldingDeposit</name>
   <tag></tag>
   <elementGuidId>0ba04a09-b807-4bb7-bee3-2a2947f3d9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > p.sectioncenter > span > a.progresssectiontext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='show_holding_deposit()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0917f208-39fb-42b5-8f25-0431651f96ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>progresssectiontext</value>
      <webElementGuid>5607a68e-3489-4bed-9c0f-44442063575a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>47c0b0f8-6a34-444d-93b2-d7113c117daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_holding_deposit()</value>
      <webElementGuid>011f3ea6-8b66-4f18-a1a2-8a399fa1a86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Received</value>
      <webElementGuid>e4169cd2-52aa-417e-9adf-deb50adfc05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/span[1]/div[@id=&quot;checkstablecontainer&quot;]/div[@id=&quot;checkstable&quot;]/table[@id=&quot;checkstabletable&quot;]/tbody[1]/tr[2]/td[4]/p[@class=&quot;sectioncenter&quot;]/span[1]/a[@class=&quot;progresssectiontext&quot;]</value>
      <webElementGuid>d03be624-678f-4ab9-bd75-10647692899d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_holding_deposit()']</value>
      <webElementGuid>b3386c6b-6b55-4fa6-84e9-cb1d15c9faec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable']/tbody/tr[2]/td[4]/p/span/a</value>
      <webElementGuid>0c9e9455-0bfb-47e3-b7e4-264e0f762412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Received')]</value>
      <webElementGuid>477c86bc-6919-46ab-918b-16c19004e85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreed'])[2]/following::a[1]</value>
      <webElementGuid>e30cc545-00e0-4fd5-b211-1292ddcc0e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreed'])[1]/following::a[2]</value>
      <webElementGuid>78536a46-5d9e-4444-afcb-802e56959160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[1]</value>
      <webElementGuid>0e758714-d515-4fc5-9138-feeff1c9c957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[1]/preceding::a[5]</value>
      <webElementGuid>71a2a4c8-862c-4bc4-9108-1c5791d446e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Received']/parent::*</value>
      <webElementGuid>9586b4b5-054e-4bdd-8374-caa0fc19e6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>6df0aa5d-5433-4efc-86f9-8cd9237f386c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/p/span/a</value>
      <webElementGuid>a7f40122-6a70-415f-aeed-20ff46db9434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Received' or . = 'Received')]</value>
      <webElementGuid>13cb4d1c-11c9-43ba-b5c4-08582e776bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
