<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add RG - Side panel - Confirm switch bt</name>
   <tag></tag>
   <elementGuidId>af30b707-0684-4683-8aa2-2c006ad78bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.switch.combinedornot</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModalDialog']/div/div[2]/label/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16bff664-64a1-480d-9dd8-ac6b728ad26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch  combinedornot</value>
      <webElementGuid>f83daeb4-e8e0-463b-a84a-27e84c6042fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModalDialog&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/label[1]/button[@class=&quot;switch  combinedornot&quot;]</value>
      <webElementGuid>01fba633-5879-4672-981e-cf0f9fb44b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalDialog']/div/div[2]/label/button</value>
      <webElementGuid>8df22a44-35e1-4893-9cb2-103648d3e9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button</value>
      <webElementGuid>ec323f26-7ab1-424e-a81b-e37eb0c8a878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
