<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add RG- Side panel - Purchase RG bt</name>
   <tag></tag>
   <elementGuidId>e90256a0-9038-461e-b749-bebeeb172adc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purchase_rent_guarantee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='purchase_rent_guarantee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64abae8d-a086-4cd6-9482-7a5f2d4a613a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchase_rent_guarantee</value>
      <webElementGuid>656768fe-0d67-4ee7-9283-ec92bf97121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>puchase-rent</value>
      <webElementGuid>c36292bc-91f3-4b40-a0d0-24160086017e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>62a84be4-4dad-4410-b8ce-247c9ac2f158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rent-color</value>
      <webElementGuid>71fce812-2107-4077-b6dc-3b79d99ff22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Rent Guarantee - £215 inc tax</value>
      <webElementGuid>ccb4f6c7-9b1f-45c7-8560-79a0700d3e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase_rent_guarantee&quot;)</value>
      <webElementGuid>78222536-8e84-4754-a6e4-994e8992cde8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='purchase_rent_guarantee']</value>
      <webElementGuid>3074eb39-792a-464e-a2e9-f957b7f8f44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalDialog']/div/div[2]/a/button</value>
      <webElementGuid>9d7e4982-d795-456e-b769-7db39bafb5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Information'])[1]/following::button[2]</value>
      <webElementGuid>38aca4d8-c37c-443f-8f94-5b7ab520bb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obligations'])[1]/following::button[2]</value>
      <webElementGuid>a437bbf6-8f97-4527-acf4-8bf944727112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a new end date for the tenancy'])[1]/preceding::button[1]</value>
      <webElementGuid>4252e141-b21c-4de7-a40d-642fce7c4c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::button[1]</value>
      <webElementGuid>340340c9-407a-4114-b146-1498e32ee2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Purchase Rent Guarantee - £215 inc tax']/parent::*</value>
      <webElementGuid>fbbdad6c-2e9a-4863-81f2-33bc85547175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>4a389ef8-2ccf-450a-a9c8-ef9ee514bfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'purchase_rent_guarantee' and (text() = 'Purchase Rent Guarantee - £215 inc tax' or . = 'Purchase Rent Guarantee - £215 inc tax')]</value>
      <webElementGuid>b6792b8d-8ca5-420c-979e-a469b831f77d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
