<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML - AML tab bt</name>
   <tag></tag>
   <elementGuidId>3e2fccfd-48b4-4391-9ffc-8dd6a1a214dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AML')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.nav-tabs > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ed8b7df-5d49-41bb-95ee-740b2971c3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent/applicant_aml_checks</value>
      <webElementGuid>65b214fa-0031-4e8d-bae4-524f050fc720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>applicant_aml_checks</value>
      <webElementGuid>05e14703-e9cb-4db9-8583-801f890f0060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>39e345e7-e589-4d1b-a79f-3bcab1e115c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AML</value>
      <webElementGuid>a0286b4b-8670-4922-9b4a-1febf4798c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cbp-spmenu-push&quot;]/div[3]/div[@class=&quot;maincontainer&quot;]/div[@class=&quot;col-md-12 lgtopspacing rpcontentholder&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[3]/a[1]</value>
      <webElementGuid>71dd8e03-82da-4420-8021-22fb6bfc2b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AML')]</value>
      <webElementGuid>932ff571-780b-4e40-83b4-8164655190ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencing'])[3]/following::a[1]</value>
      <webElementGuid>2f0abc5e-b525-4d65-b2ed-7d3f02473d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properties'])[1]/following::a[2]</value>
      <webElementGuid>cadcc7a0-5ed7-4ab3-86d7-74e9d74ab0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landlord AML'])[1]/preceding::a[1]</value>
      <webElementGuid>c76acc48-f48c-4f5a-89c1-5a579961ba4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right to Rent'])[1]/preceding::a[2]</value>
      <webElementGuid>031e1784-5ade-4442-95f1-07493ad9fe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AML']/parent::*</value>
      <webElementGuid>ef93d925-64d8-44b4-bc57-2d7b2d13ba00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agent/applicant_aml_checks')]</value>
      <webElementGuid>75edebd5-5854-4a50-97ce-0a898deffd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[3]/a</value>
      <webElementGuid>be9745bb-4c31-476b-ae44-8f32e748e4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/agent/applicant_aml_checks' and (text() = 'AML' or . = 'AML')]</value>
      <webElementGuid>20ba1707-146e-4551-9c9c-0b1339bbb864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
