<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML tab - Date of birth field</name>
   <tag></tag>
   <elementGuidId>d47a29f1-64e3-415a-b545-6c8fdd15effe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='applicant_dob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#applicant_dob</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcc91c04-87e4-4be1-a776-5d5bc8400481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6918c7ad-7ce6-42df-b0d5-70c61d3b97ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applicant_dob</value>
      <webElementGuid>7fb240db-91b5-4c63-9a11-6add3679a726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2cdbaf30-14b6-4294-95f4-9cea96957de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>3275a7ba-563f-4755-8d0c-64ef48cdd745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of birth</value>
      <webElementGuid>ee271d80-be4f-4e09-9b81-3dfcfa10957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicant_aml_check[dob]</value>
      <webElementGuid>2d8d57fe-211d-4e73-a329-ba7b1756e678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicant_dob&quot;)</value>
      <webElementGuid>e7e144c6-6946-4f6b-ba06-fcf6143d9069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='applicant_dob']</value>
      <webElementGuid>e144fd3f-a333-4610-acd6-c9725fbda8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ownerindividual']/div[4]/div/input</value>
      <webElementGuid>785231ec-b18b-4459-9f09-57aff1877969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a9c0f710-156d-4294-9769-7dbda6e22829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'applicant_dob' and @placeholder = 'Date of birth' and @name = 'applicant_aml_check[dob]']</value>
      <webElementGuid>08f36b84-e1d0-4ec8-8612-c25e1e222672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
