<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML - Side panel - Download Certificate bt</name>
   <tag></tag>
   <elementGuidId>1678425c-7fb1-4d29-806e-affb2a00eb78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.clickable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aml_download_link']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6ddbfe9-1db5-4697-bcb8-1b7a3c66bc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent/applicant_aml_checks/996/download_report</value>
      <webElementGuid>16da5f20-879e-4831-9848-aec6d7130f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable</value>
      <webElementGuid>08273206-0241-481f-abcf-6253aa259057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2ef6551e-ebc1-4c61-8d96-bc9fdc0d4304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Certificate</value>
      <webElementGuid>7ed79e0d-0372-40ac-8f7f-3a80ce0052b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aml_download_link&quot;)/a[@class=&quot;clickable&quot;]</value>
      <webElementGuid>16ae74dc-dee6-4be2-b4f1-620818f63938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aml_download_link']/a</value>
      <webElementGuid>530223c4-84c5-482c-94ed-c1e79af7f0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Certificate')]</value>
      <webElementGuid>1eaae067-4f85-4b92-bcef-d5f6df9168ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant AML: Cthy Test'])[1]/following::a[1]</value>
      <webElementGuid>afb047d2-205e-4f9d-af0a-05f8f04f89ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[2]/following::a[1]</value>
      <webElementGuid>c7ccd852-e44f-40e0-a9ef-52e0c138592b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[1]/preceding::a[1]</value>
      <webElementGuid>8b72d277-fcd8-48de-b666-85f90e41c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requested info'])[1]/preceding::a[1]</value>
      <webElementGuid>039340b4-48a9-4c88-8df4-a1cd24240c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Certificate']/parent::*</value>
      <webElementGuid>e7e0c5ed-0228-4003-9113-e62a18bf653e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agent/applicant_aml_checks/996/download_report')]</value>
      <webElementGuid>a2ce209a-f5b1-42c3-ab17-f22deb662949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>6942bc86-2b77-4dcf-b328-c6a77860f70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/agent/applicant_aml_checks/996/download_report' and (text() = 'Download Certificate' or . = 'Download Certificate')]</value>
      <webElementGuid>e458d0f9-a9c5-41f7-8ec9-e797490aa836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
