<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML tab - Add AML bt</name>
   <tag></tag>
   <elementGuidId>9cf2bb75-80c0-4250-a96f-a6d907e15875</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addreferencingbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addreferencingbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>116ac6a7-35ed-48a9-b0c1-4d3eb85065a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>dbb4721d-ed9d-4e41-8302-a52f99b875db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>fccc830b-9654-457e-a31c-254e25397e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add AML</value>
      <webElementGuid>a155d01e-203b-4e28-938e-aa7bca54112d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addreferencingbtn&quot;)</value>
      <webElementGuid>6c19cf88-746d-4236-af25-35b233ca3857</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addreferencingbtn']</value>
      <webElementGuid>d8143e5c-c3f6-45a3-9ca2-aa714771545a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form/div/div/a</value>
      <webElementGuid>6e2839ed-ff44-47e9-aedd-a89f18a1818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add AML')]</value>
      <webElementGuid>ccd4fed5-de7a-4ec6-bef4-1cc72fe29ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent Guarantee'])[1]/following::a[1]</value>
      <webElementGuid>f9dd09cd-ee99-4ea5-a9af-80e9a9fd52a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right to Rent'])[1]/following::a[2]</value>
      <webElementGuid>570a4fb0-fa3e-4ca9-a245-e9f67b6aaf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk upload AML checks'])[1]/preceding::a[1]</value>
      <webElementGuid>f9cb744a-db4c-43ad-bcde-2a80995bc0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.csv'])[1]/preceding::a[1]</value>
      <webElementGuid>254691c0-3186-4cc9-88d4-404a7128e84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add AML']/parent::*</value>
      <webElementGuid>678401c3-5235-427f-a7c0-18676777af4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>19543d4e-213f-45ab-a522-eff87717a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addreferencingbtn' and (text() = 'Add AML' or . = 'Add AML')]</value>
      <webElementGuid>109b920b-d916-4602-9815-5db3f2028098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
