<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AML tab - Middle name(s) field</name>
   <tag></tag>
   <elementGuidId>f6f3b9cb-0f0e-4fa7-abbf-03d5bdfc4123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='middle_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#middle_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c629673b-2f5b-4703-8d53-aa8afe96025c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7a4a181-3133-402e-b578-94cb96c6c129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middle_name</value>
      <webElementGuid>f70fad4d-b280-4434-b9d0-3955fe2bcfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ba825bf3-e684-4d18-8eab-ccd3670ed380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>61085260-b42f-4ab3-b314-9c99a1f6f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Middle name(s)</value>
      <webElementGuid>5fb69f9b-53f7-4a92-8a14-2e5a70a39979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applicant_aml_check[middle_name]</value>
      <webElementGuid>32e32a2a-108c-4c87-8c21-775ed5018d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;middle_name&quot;)</value>
      <webElementGuid>7db3132f-b132-4c31-a43c-239086cfdcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='middle_name']</value>
      <webElementGuid>3eababd4-0dc3-4f14-a61c-684b8ea1ad0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ownerindividual']/div[2]/div/input</value>
      <webElementGuid>6ac86083-8514-4240-a53b-281e33b7177c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3b99788d-0f98-4873-b645-b05714f8f41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'middle_name' and @placeholder = 'Middle name(s)' and @name = 'applicant_aml_check[middle_name]']</value>
      <webElementGuid>c3670b11-39a6-4ed4-8c6b-0cf6e2161abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
