<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseforHoldingDeposit</name>
   <tag></tag>
   <elementGuidId>1d970ad5-4e70-435e-b2ab-e9e21ba8f4f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide_holding_deposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hide_holding_deposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47d8ac8f-6a1c-4ae0-b782-88106735f9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide_holding_deposit</value>
      <webElementGuid>eef9ab91-9eca-4895-912a-bdc5811f89a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hide_holding_deposit();</value>
      <webElementGuid>9e81dd44-6c86-4143-8f2b-c8a79b1f6766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg btn-block</value>
      <webElementGuid>94f235b9-a07e-480c-a11a-d05a291159d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>ff552870-7bcb-4e00-b61d-4fa8e860f196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>be038e29-3e18-44d9-a59a-617142ce45c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide_holding_deposit&quot;)</value>
      <webElementGuid>c2904daa-9a31-4300-97e4-dbb861ae81b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hide_holding_deposit']</value>
      <webElementGuid>6f63634e-5371-4086-81e8-06a0ca7e7160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info_div_holding_deposit']/button</value>
      <webElementGuid>ed1ca0c8-080d-42e0-bacd-c1a413ab0c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[1]/following::button[1]</value>
      <webElementGuid>49f748cd-5cb9-40bc-8f31-9d7bd42fa08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount:'])[1]/following::button[1]</value>
      <webElementGuid>526d1d64-b7b1-49ed-90d4-beb4dffe6c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[2]/preceding::button[1]</value>
      <webElementGuid>d8d3c322-fd69-4d74-97a8-320e8c27b147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Method used:'])[2]/preceding::button[1]</value>
      <webElementGuid>779f838d-114a-448e-9422-e1161302285e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Close']/parent::*</value>
      <webElementGuid>b940d888-db19-45cd-a875-f428794c1e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8614f2ed-94bd-4813-be1a-0032105a69fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hide_holding_deposit' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>31482918-b8ef-46af-9ad8-8aebe0efc1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
