<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseforTenancyAgreement</name>
   <tag></tag>
   <elementGuidId>4bf3c3e9-472a-4291-9ab3-f210678f6d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide_sign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hide_sign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8891b02f-0e30-44f2-92b5-0b25e463e426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide_sign</value>
      <webElementGuid>166b9ed9-45c7-423f-ab3b-5f72eae58d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hide_sign();</value>
      <webElementGuid>64330adf-ea13-4ca4-836b-b35241b04d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg btn-block</value>
      <webElementGuid>4c9fed0f-1526-4acc-983d-8b6fb2805aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>22010f62-6af6-4bcf-b579-4b5898a71c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>3c6838e7-9422-437e-bd5e-aa75fd3f90ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_sign&quot;)/div[@id=&quot;info_div_holding_deposit&quot;]/button[@id=&quot;hide_sign&quot;]</value>
      <webElementGuid>f1c6085c-c6a7-4879-b6b4-a6a3e58772cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hide_sign']</value>
      <webElementGuid>848b826b-a84d-40c9-9d73-d9a9b7c2f79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='info_div_holding_deposit']/button)[2]</value>
      <webElementGuid>968cf15f-16c2-4995-bef3-92e4cad50197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Agreement'])[1]/following::button[1]</value>
      <webElementGuid>204bdb98-2a30-4d5a-9833-d8bf6aa89845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Agreement:'])[1]/following::button[1]</value>
      <webElementGuid>1242ae8c-81ab-4003-b8b1-b34544e2c450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renter signature:'])[2]/preceding::button[1]</value>
      <webElementGuid>928d3fa0-4f70-4dcb-ae48-fa5b0cea0991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[5]/preceding::button[1]</value>
      <webElementGuid>fbb23962-886e-460a-a757-8aac8aed654e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>9047f30f-a3a0-4e32-9619-cf0e634e0fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hide_sign' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>e83d3773-41e9-4791-a083-9edd02fa7ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
