<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm Tenancy Cancellation</name>
   <tag></tag>
   <elementGuidId>4c57b3e6-35f7-4678-8e60-4f5a1ac18f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refundbtnv2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refundbtnv2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e682a582-f2ac-4f3e-a1f7-6dd9a149b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fae0b95a-aaf1-4f1f-9fbd-aeecd4345cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>92b37863-b47a-40bc-842a-caa009078300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refundbtnv2</value>
      <webElementGuid>1a0a9261-0a63-4b53-b329-ce756f10d230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-success</value>
      <webElementGuid>15cfc4d7-9fe1-4ba7-8586-6513bee441e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm Tenancy Cancellation</value>
      <webElementGuid>ca459b6f-0ae7-4d9c-9222-9e7661ae022a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refundbtnv2&quot;)</value>
      <webElementGuid>b43ce01e-46f6-4912-b569-fa92f393aaee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refundbtnv2']</value>
      <webElementGuid>7161d12e-54ee-4d5f-9227-a9e9029b2588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_tenancy_18138']/button</value>
      <webElementGuid>ba8908b3-cbb7-4e34-837b-93afe97a91bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to cancel this tenancy?'])[1]/following::button[1]</value>
      <webElementGuid>28756822-f59a-4c64-b60b-7f43a4af77e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D4139'])[1]/following::button[1]</value>
      <webElementGuid>2d74c37f-1be9-4b08-aefb-959725786a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::button[1]</value>
      <webElementGuid>7ce92821-9f51-4c52-8fe4-f919bb1c9e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::button[1]</value>
      <webElementGuid>92914ad5-d785-4234-a65c-cf702dc1242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm Tenancy Cancellation']/parent::*</value>
      <webElementGuid>fe7ebd04-1806-4004-a5f0-8f0973e330a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/form/button</value>
      <webElementGuid>e58948b3-67d3-444b-a841-b4b973c91cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'submit' and @id = 'refundbtnv2' and (text() = 'Confirm Tenancy Cancellation' or . = 'Confirm Tenancy Cancellation')]</value>
      <webElementGuid>71a246b2-f62f-401e-a95e-ee1d421b8960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
