<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseforInitialRent</name>
   <tag></tag>
   <elementGuidId>f048a6ab-9dba-41a6-84ca-931f8a7364e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide_initial_rent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hide_initial_rent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63837b95-de0b-442f-832e-9b50a50e3b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide_initial_rent</value>
      <webElementGuid>b0b818a3-cce2-4fc9-a506-f10c8224419e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hide_initial_rent();</value>
      <webElementGuid>f426ef65-74fc-49a1-ac30-93b10615b526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg btn-block</value>
      <webElementGuid>3fc11977-fb45-4859-b8cd-223b12d990e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>5706d363-b393-4a7a-8d87-dbd262a824df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>5fe30f11-6bb6-4bb9-b532-b33a1551e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide_initial_rent&quot;)</value>
      <webElementGuid>04647f44-8d58-4256-8577-bacb5e03bf12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='hide_initial_rent']</value>
      <webElementGuid>7775a1f1-1380-4cd9-b533-65cc8b980902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info_div_initial_rent']/button</value>
      <webElementGuid>80f1a447-cbb8-4ad6-8abe-389d24b048c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference:'])[2]/following::button[1]</value>
      <webElementGuid>61ded3c0-2426-47d8-82c1-14a7db9ca718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[3]/following::button[1]</value>
      <webElementGuid>be2d55b9-c037-4e17-874a-400f8c446e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renter signature:'])[1]/preceding::button[1]</value>
      <webElementGuid>84301302-0aec-4d81-b267-de34b9de0d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[4]/preceding::button[1]</value>
      <webElementGuid>a0bf2166-2fe1-4e8a-b3b8-991ad7c1003b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>a6aea7c6-69e8-43be-a5b9-c8fe5a785750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'hide_initial_rent' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>7f2edf9f-ca66-4a30-afcf-4458bf2d2945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
