<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car Parking - Search field</name>
   <tag></tag>
   <elementGuidId>643af951-75b9-471b-b872-e7366d5432cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_addons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_addons']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13177baf-8fe8-4a6c-b250-ff1ba6143fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8c36975-4493-4670-9270-e6bfc5ccf38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_addons</value>
      <webElementGuid>cb4a19c9-c6f9-4ea5-a95c-b87eb8c011b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_addons</value>
      <webElementGuid>43097da6-a52a-4805-a112-40df9b9e3e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>e401fa63-a82e-4560-8d9a-dcc38485499e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by tenant, building or bay number</value>
      <webElementGuid>eda8501b-6a45-4061-afc4-cf956e0f1488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_addons&quot;)</value>
      <webElementGuid>5b85d522-f7d2-4cbd-929a-5fcda1436370</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_addons']</value>
      <webElementGuid>182903b4-c84c-442c-a053-ceb3425073e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/input[2]</value>
      <webElementGuid>e73e6894-519e-41e4-88fd-a6489bbe7f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>77778fc7-b4ac-44b2-987a-ab09139e7a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_addons' and @id = 'search_addons' and @placeholder = 'Search by tenant, building or bay number']</value>
      <webElementGuid>c982decd-6907-4ee7-b073-340302198683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
