<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car Parking - Cancel (x) bt</name>
   <tag></tag>
   <elementGuidId>d50aa219-88d1-4dee-b359-6dadf58b0836</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.string.optional.cancelhover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='✕']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5fa1324-c5ba-4edd-a530-5cd9e411d2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>a1507cf5-4dce-471a-9f7e-acd5402f83de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional cancelhover</value>
      <webElementGuid>e2066caa-d503-4b82-bd2d-812ff915b485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ca2bbb7-023d-4988-aaec-da8616bebaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>182bbf2e-1e07-4b6e-8929-e27b482ebae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetsearch_addon&quot;)/a[1]/input[@class=&quot;string optional cancelhover&quot;]</value>
      <webElementGuid>80288135-3fba-456f-a1f9-6f337fcfceb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='✕']</value>
      <webElementGuid>feeb5ddb-cbd4-42a9-83ef-fa0de9bcdf4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='resetsearch_addon']/a/input</value>
      <webElementGuid>383bf2ef-5c78-4f44-8511-f71c1634126a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>1f830b75-f56d-4f23-8a71-e6b1ab5f1e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>00521a87-54fa-4a0d-a69f-6b44cd633cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
