<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car parking - Direct debit field</name>
   <tag></tag>
   <elementGuidId>aa0dc732-e529-4654-9cc5-8ade5aea943a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addon_direct_debit_reference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addon_direct_debit_reference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2c92ba0-4ac8-4e4b-a0d0-fe07dc74455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addon_direct_debit_reference</value>
      <webElementGuid>5e40030b-ed40-4048-a2d0-2af6b952122c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6855f90f-ced8-45e1-9be2-5f4652cf8273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>41f485d1-0e8a-4b58-8694-79867c9ced23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addonDDRefHF();</value>
      <webElementGuid>a07aef8c-7a55-4ab9-8ad8-9ba5478a330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direct debit reference</value>
      <webElementGuid>b8fa3b13-e416-487e-99e7-3e33ccd5c768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3060847b-5e55-49de-ab0e-9d37824145e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[parking_direct_debit_ref]</value>
      <webElementGuid>0a3da200-1e07-48ce-ab9c-f2cf77474ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addon_direct_debit_reference&quot;)</value>
      <webElementGuid>018a0031-76b3-4781-8210-5d901c7a077b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addon_direct_debit_reference']</value>
      <webElementGuid>b9bd8c95-03dd-4407-b6c8-df562745a124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab']/div/form/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>1244f1dc-446a-411c-b0d9-478100253229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>b625aaf5-6bf4-498f-8557-e9590342181c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addon_direct_debit_reference' and @placeholder = 'Direct debit reference' and @type = 'text' and @name = 'invite[parking_direct_debit_ref]']</value>
      <webElementGuid>118f6310-bacf-4f80-9e0d-9553c32116b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
