<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car parking - Bay number field</name>
   <tag></tag>
   <elementGuidId>f35c3eeb-8235-4018-bdb8-6a631cc0137b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addon_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addon_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2e68b1f-fe21-4d34-b0f4-93d8deff445b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addon_number</value>
      <webElementGuid>5c6c1a71-6697-47d8-b0f9-60e2b9756d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1975ee22-98f0-40fa-a2fb-31cc4ed58cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>7e963674-2471-4eea-af61-0d2dcabb2d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addonNumberHF();</value>
      <webElementGuid>30dd20a3-337a-4e43-8aa9-fdba81c0242b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bay number</value>
      <webElementGuid>7b060301-8c56-4357-adf6-36904eaede42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0acee446-1a6b-48f2-ab1a-32c3ecc9d08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[addon_number]</value>
      <webElementGuid>9afe3d0c-84b8-4d2e-a655-268df6bf6697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addon_number&quot;)</value>
      <webElementGuid>c82bec9c-1c7e-43ba-a84b-290c60ca7734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addon_number']</value>
      <webElementGuid>be03f2fc-7570-4f87-8c0b-fb9e1b7f90d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab']/div/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>c1d83a56-b01c-4c38-a19d-3e3c562dedc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>17053594-e309-41ce-aecf-0e8e61cf3771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addon_number' and @placeholder = 'Bay number' and @type = 'text' and @name = 'invite[addon_number]']</value>
      <webElementGuid>a9c2b254-d143-469c-b1f7-c0177ebe5de7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
