<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Commercial enquiries - Search bar</name>
   <tag></tag>
   <elementGuidId>e0177fd0-cbe6-49cf-bbc4-7f66bed91fff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_enquiries</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_enquiries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a402bcc-411c-4ee9-a8ea-279080ffaf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51312b44-438e-42e6-bf73-e8f0fbd42f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_enquiries</value>
      <webElementGuid>d7177471-78a0-4707-a5ad-d24fcfe77516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_enquiries</value>
      <webElementGuid>917e52cf-39a3-4185-a38e-46d18c9e4db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>7969b27f-234d-4cfd-bd7c-13b01b25bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by address or applicant name</value>
      <webElementGuid>c43b6e29-4ac9-4296-9c74-4f965f14611e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_enquiries&quot;)</value>
      <webElementGuid>2d218a19-df15-4614-86a8-bc4f04b6a7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_enquiries']</value>
      <webElementGuid>d64ba223-2345-4cb7-868a-4817f056399d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-enquiries-form']/input[4]</value>
      <webElementGuid>2de5c073-173b-4c6f-9062-e3c6ac1b7415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>f924ff4b-f7f7-4056-9f97-7086a7860b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_enquiries' and @id = 'search_enquiries' and @placeholder = 'Search by address or applicant name']</value>
      <webElementGuid>9dd05b76-b07c-475a-b0c1-e22188f4f84c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
