<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Tooltip icon for Lead Tenant</name>
   <tag></tag>
   <elementGuidId>4a45c0d8-8b58-4e9a-a6df-d80a2e557b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='renter123container']/div/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-4.overlay > div > div.clause_example_popup > a > i.fa.fa-question-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e8e18847-9731-4106-892c-a1fddce7d96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-question-circle</value>
      <webElementGuid>c7203024-e973-4fc9-a138-b79644b5ae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23306399-5ae8-4b67-ae12-5d5904469caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter123container&quot;)/div[@class=&quot;col-sm-4 overlay&quot;]/div[1]/div[@class=&quot;clause_example_popup&quot;]/a[1]/i[@class=&quot;fa fa-question-circle&quot;]</value>
      <webElementGuid>69db99bb-18dc-4b06-811b-5de6f97c03bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter123container']/div/div/div/a/i</value>
      <webElementGuid>b232b191-bc57-47d9-96cd-706110aa8bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/i</value>
      <webElementGuid>155b0546-c60a-4a47-afbd-34428230c99c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
