<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Tenancy - Flatfair logo</name>
   <tag></tag>
   <elementGuidId>7e274898-1594-40a5-97b0-cae2203b714d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flatfair_multiple_div']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flatfair_multiple_div > img.card-img-top</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d81d640-8a15-4f03-94b8-eb9a06d81062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/deposit_replacement/flatfair_logo.svg</value>
      <webElementGuid>e28a9933-105b-44b4-9442-bce82f2d0e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>ac45eda0-ce2c-4b35-9db6-89614cf9507d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>e2a01512-195c-4e49-bbeb-8710101080d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flatfair_multiple_div&quot;)/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>4a6d178e-2a4a-4582-8312-e5ccbc3a1d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flatfair_multiple_div']/img</value>
      <webElementGuid>35c3e86a-a6a5-4987-971f-a24ff517dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[5]</value>
      <webElementGuid>2019a30f-1cf6-4108-bbf9-0fb5debcdabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>3dcaad20-003f-4a6b-9441-d0141ee91853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/deposit_replacement/flatfair_logo.svg' and @alt = 'logo']</value>
      <webElementGuid>ce5ea98d-c4d9-4418-bb43-1c22697851d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
