<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - NHA for company radio button</name>
   <tag></tag>
   <elementGuidId>2ddaf8f7-d23c-4430-bfe6-7a373cf21478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company_let_radio_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company_let_radio_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>297c2a67-403d-42a7-a478-3500d3792c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company_let_radio_button</value>
      <webElementGuid>0e130279-3ca0-4574-a50f-82b90ddedbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agreement_type_radio_button</value>
      <webElementGuid>e2898263-7a32-42f3-89b9-81b087537ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>eeb821e9-dd35-48fc-95db-1e8982a3110d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>company_let</value>
      <webElementGuid>562c41b5-143f-47a8-ad6d-703343b553e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company_let_radio_button&quot;)</value>
      <webElementGuid>3068ea90-8739-4295-9cf7-a9bcb4ca537b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company_let_radio_button']</value>
      <webElementGuid>625d2f13-9078-445d-8f32-6f8b27ddfb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/table[2]/tbody/tr[2]/td[2]/label[3]/input</value>
      <webElementGuid>18bf7213-d927-425c-9f39-7fb9ad15ca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>be5c7cde-c45e-4baf-a514-c06a439e8cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'company_let_radio_button' and @name = 'agreement_type_radio_button' and @type = 'radio']</value>
      <webElementGuid>09b74d2d-4015-4f01-8925-f291022e3c79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
