<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dashboard - Account page - Logout bt</name>
   <tag></tag>
   <elementGuidId>b537dc31-81d0-4e1e-9ba0-013123a52ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tab-content > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='requeststab']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f72f7f4b-cacc-4dff-a143-0a1c4893288a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent/logout</value>
      <webElementGuid>5153d291-c07b-4369-a189-c6bcd06e8bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>c0a2c265-f76c-4df6-b9fc-7d79e425acbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[1]/a[1]</value>
      <webElementGuid>efd886f2-3b54-445f-8236-08265c885606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab']/div/div/a</value>
      <webElementGuid>e06c86f3-a0c9-4b99-be72-cf472a8b818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>e16f42c6-e6de-4848-86f3-e1d793b3cfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged in as'])[1]/following::a[1]</value>
      <webElementGuid>9e9c950f-97c8-4c2e-a780-cf54b862a85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::a[1]</value>
      <webElementGuid>e77fa726-7bdd-4c20-abca-c0cfcf7ffcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Announcements'])[1]/preceding::a[1]</value>
      <webElementGuid>11a3fc46-50a7-4b3b-993f-ef8c31eef7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all announcements'])[1]/preceding::a[1]</value>
      <webElementGuid>0f0f4716-75b0-4312-8a8a-48a63009d4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>3d937da6-3c81-48f6-a4b8-9ceff49911bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agent/logout')]</value>
      <webElementGuid>d460a648-12cd-45b9-ab2c-a47c9fa54697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a</value>
      <webElementGuid>a62acbc0-4cd0-45e8-8a2f-5d7c19fae900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/agent/logout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>03a63971-5f02-47b6-91af-23244c958e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
