<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DD Car parking - Edit textfield</name>
   <tag></tag>
   <elementGuidId>7170d3b8-be05-417a-b181-93f3f5e28125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parking_direct_debit_ref</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parking_direct_debit_ref']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfc98cdd-b2bb-4cf0-a9cd-deddaac7df16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parking_direct_debit_ref</value>
      <webElementGuid>dc7438eb-4628-4d12-9340-30613d2bfe1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>94f88a4c-b983-47d4-916d-7a9c1ccd3c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4656</value>
      <webElementGuid>ffaecfcc-c65a-4e17-b175-b3bf08f41c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter reference</value>
      <webElementGuid>e03b19c0-23b4-43f9-aa4a-e7ff6a7354af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>837bd197-568b-4a20-b1bc-041984257b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addon[direct_debit_ref]</value>
      <webElementGuid>0cd10b9c-6d31-4944-ae2f-2032f9545c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parking_direct_debit_ref&quot;)</value>
      <webElementGuid>a94970f4-2d0a-495e-a064-fa674a7cc4f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parking_direct_debit_ref']</value>
      <webElementGuid>2d939a37-a40d-43c1-8bee-907f083fbe94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dd_ref_parking_form']/input[4]</value>
      <webElementGuid>c2be87dd-b819-4992-bc6a-d0a6d047a90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/form/input[4]</value>
      <webElementGuid>ddef5a00-8b75-4e9b-b9e5-c5fbba5409e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'parking_direct_debit_ref' and @placeholder = 'Enter reference' and @type = 'text' and @name = 'addon[direct_debit_ref]']</value>
      <webElementGuid>3cdbfdc3-4ac0-4264-918e-d61a63a48118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
