<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Direct debit Tenancy - Edit bt</name>
   <tag></tag>
   <elementGuidId>44bf23aa-e76a-4ce9-9703-aa538b6f1352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit_dd_ref</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='edit_dd_ref']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d805507c-3f40-4c4b-ba1a-082f98bc3ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_dd_ref</value>
      <webElementGuid>aa23fba2-c063-4584-bf72-1284887a5cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>5a6830ba-744c-4676-aaee-652dc3c9ec8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_dd_ref&quot;)</value>
      <webElementGuid>04527e90-be92-4cd0-b4bf-d8a725c299c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='edit_dd_ref']</value>
      <webElementGuid>883d1d3c-0ee4-413b-8e97-c5b4e2d5a89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkstable']/div/table/tbody/tr[4]/td[4]/span</value>
      <webElementGuid>c9cba252-b8de-4e5a-b74e-797b5444153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[1]</value>
      <webElementGuid>552ad9a7-d103-4c60-b2a3-13ea2ab3ca43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::span[2]</value>
      <webElementGuid>48edb757-7803-42cb-9812-c4db690fd72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See less'])[1]/preceding::span[2]</value>
      <webElementGuid>bdb7365b-e663-46ad-82f2-770b8fd8f61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>f8684255-50f2-457d-a264-73c48e953dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'edit_dd_ref' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>f7e78ca4-fd8b-4274-b3f6-edeb07acb435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
