<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Direct debit - Edit textfield</name>
   <tag></tag>
   <elementGuidId>c188cf57-9626-4375-b438-97cd6e7f184a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#direct_debit_ref</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='direct_debit_ref']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34edbef5-5962-454c-bbeb-da3c7f212121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>direct_debit_ref</value>
      <webElementGuid>0d8602d0-1c9d-4612-936a-34ee4fbedad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>f570a44e-ec40-4d76-a92b-8892492d46a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123abcd</value>
      <webElementGuid>3d11dab9-0f7d-4712-ae22-7873fad6dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter reference</value>
      <webElementGuid>e42b47cb-4bdc-4fb4-a1dd-9855f3ab4789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4126a588-66d9-4870-a2dd-8e500cbfd765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[direct_debit_ref]</value>
      <webElementGuid>dc46e1a0-f6a6-4a0f-bd78-5b08f96d68e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direct_debit_ref&quot;)</value>
      <webElementGuid>fae7872f-b260-478e-9010-3f4d808c241f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='direct_debit_ref']</value>
      <webElementGuid>90a96aa9-6291-42c7-ae36-a2fed9ed63e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dd_ref_form']/input[4]</value>
      <webElementGuid>6c7789cc-53e6-4524-b9ed-5e816d46da9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/form/input[4]</value>
      <webElementGuid>da4c8181-392f-495b-8bb5-2074db9ab805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'direct_debit_ref' and @placeholder = 'Enter reference' and @type = 'text' and @name = 'tenancy[direct_debit_ref]']</value>
      <webElementGuid>84ed7326-6f5b-4839-8c12-dc46dae30b9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
