<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Direct debit - reissue field</name>
   <tag></tag>
   <elementGuidId>68855a40-c739-4943-b809-468bfdc2d9ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addon_direct_debit_reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addon_direct_debit_reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea3a2159-bdc2-4379-8822-99650cbf71d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addon_direct_debit_reference</value>
      <webElementGuid>df8ecc17-2411-4364-bdd9-234bc30f57f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c66092a6-c98c-4025-bd5c-35ba9ef807a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>c92fb054-2488-4ae4-ba58-b005f81bafd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>addonDDRefHF();</value>
      <webElementGuid>5b6f009b-4893-4ad8-81c7-aed179197507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Direct debit reference</value>
      <webElementGuid>f5145c4f-5e3e-447b-a233-71decfd407b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbf3063b-5b0b-4881-9663-1afbb3dfc070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[parking_direct_debit_ref]</value>
      <webElementGuid>523d7227-4fe6-45f8-aadc-ce2611170a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addon_direct_debit_reference&quot;)</value>
      <webElementGuid>8c7b7a02-fbb2-4170-accb-284cafeca2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addon_direct_debit_reference']</value>
      <webElementGuid>00c6f612-8a35-43fc-aa2d-dde71bea3d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab']/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>e3ee8d3c-bbae-466c-809a-84dd61988daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>f15e1a92-6f63-44a3-a03e-9c8f07f6deb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addon_direct_debit_reference' and @placeholder = 'Direct debit reference' and @type = 'text' and @name = 'invite[parking_direct_debit_ref]']</value>
      <webElementGuid>8e86a751-cd32-4a16-8668-d26583ccfd7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
