<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LTD Company Continue bt</name>
   <tag></tag>
   <elementGuidId>c1d1513f-b994-48fb-b654-7fd4f6637ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='selfemployedcompanydirectorcontinue1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selfemployedcompanydirectorcontinue1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12074281-2c52-45c4-94d5-61ea244da33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkgreen btn-lg btn-block</value>
      <webElementGuid>43764160-fb22-48f2-8865-b7a04a083686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selfemployedcompanydirectorcontinue1</value>
      <webElementGuid>19ec5b11-b9cd-4300-bbfa-228c1ec102f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selfEmployedCompanyDirectorSection1()</value>
      <webElementGuid>4f2d2101-8133-4677-b66a-66fb1b187847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>8e855cdb-4eea-4934-ad66-182c1667adb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selfemployedcompanydirectorcontinue1&quot;)</value>
      <webElementGuid>9601037b-7439-422a-8f99-0e60dec8a6d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='selfemployedcompanydirectorcontinue1']</value>
      <webElementGuid>7f899dd5-ad8f-430c-abcc-880dbce7ea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployeddirector']/div[10]</value>
      <webElementGuid>7b1cf297-bce9-49ca-98b0-5b52fdc51128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Director'])[1]/following::div[9]</value>
      <webElementGuid>35ce65fe-bb4c-47d5-acd6-0f70eab26551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back a step'])[1]/following::div[11]</value>
      <webElementGuid>4981252e-1eb9-48ff-a110-c80588dfb930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back a step'])[2]/preceding::div[1]</value>
      <webElementGuid>d8b4c432-60b7-4173-8b6e-e172eae46adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Director'])[2]/preceding::div[2]</value>
      <webElementGuid>1141efdb-5b94-445d-b14a-7dd443a1467c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>4fcaa4c1-a96e-43ce-9caf-83ee72c23377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>9e329848-3ad4-4ac2-8fb5-a80484dd863b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'selfemployedcompanydirectorcontinue1' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>485ab891-5bfe-4955-a1b2-c864ff94b718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
