<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_09B7E toggle guarantor</name>
   <tag></tag>
   <elementGuidId>859b6f96-d094-4afd-8373-a33627009d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guarantorornotswitch1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='guarantorornotswitch1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d35b256-dde5-4524-9771-517cf3a318bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch </value>
      <webElementGuid>a2db2a76-72ab-4397-97cb-27bb07f7bd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guarantorornotswitch1</value>
      <webElementGuid>3243ae15-6fd9-4e8b-93b4-6177904c6f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guarantorornotswitch1&quot;)</value>
      <webElementGuid>50b0e27a-9f77-4270-965f-af7bbfdf247b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='guarantorornotswitch1']</value>
      <webElementGuid>952eddb7-d8bb-4900-8233-e40e08ec11b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter123container']/div/div[9]</value>
      <webElementGuid>318050a1-5979-43e8-985d-2af68374e51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[9]</value>
      <webElementGuid>d25d8a32-ec08-4488-89ee-290c6d508855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'guarantorornotswitch1']</value>
      <webElementGuid>8af1823e-a822-43d9-b1ac-8402ada8e933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
