<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I am self employed bt</name>
   <tag></tag>
   <elementGuidId>7663243b-a9cd-4552-b787-8a1fd623d82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='changeValueSelfemployed()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0de3a5a-22bb-4928-b57d-14a723cdbe84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg btn-block button_mobile</value>
      <webElementGuid>738e4a13-9569-454c-99da-5e0d02e72481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeValueSelfemployed()</value>
      <webElementGuid>87243d7a-f070-4446-ad2a-ef5715876eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I am self employed</value>
      <webElementGuid>2cf11e73-ddf4-42de-b7c2-9fd7c8495146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employmentbtns&quot;)/div[@class=&quot;btn btn-default btn-lg btn-block button_mobile&quot;]</value>
      <webElementGuid>f4fbf08a-3630-4581-b679-7c2a17d6ee4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='changeValueSelfemployed()']</value>
      <webElementGuid>2c690cad-3d1e-44db-8a75-0b80d169ebb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employmentbtns']/div[3]</value>
      <webElementGuid>a1df4492-6786-4a7b-bff3-1051b3a3779c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am employed'])[1]/following::div[1]</value>
      <webElementGuid>c314cf8b-dd7f-4d43-83c6-7390a26aa6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work status &amp; Affordability'])[1]/following::div[2]</value>
      <webElementGuid>ceb1b552-4cf2-4dec-9712-e2ea20e8a7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am a student'])[1]/preceding::div[1]</value>
      <webElementGuid>9982c846-813a-4a25-87c0-be1cbe28acf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am currently unemployed'])[1]/preceding::div[2]</value>
      <webElementGuid>f8acdcc2-dc22-4762-b3d9-9ebedf816a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I am self employed']/parent::*</value>
      <webElementGuid>59b5de97-3d24-4520-8b26-63a482e8e3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]</value>
      <webElementGuid>6b8f6772-3d06-43a0-a34a-3e1dcf4b8fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'I am self employed' or . = 'I am self employed')]</value>
      <webElementGuid>7e75fb35-d68b-44d3-a59e-1d638dab6b65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
