<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Tenancy Page - Update Tenancy bt</name>
   <tag></tag>
   <elementGuidId>382e9e25-d1fb-42d2-aa61-7895a3c46542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='invitecheckvalidmobilenewrightside']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invitecheckvalidmobilenewrightside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39faee5b-7344-4d77-8990-a4a6b4ba8b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitecheckvalidmobilenewrightside</value>
      <webElementGuid>7382f870-6156-41b3-8ebe-04bc3453e98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('invitecheckvalidmobilenew1').click(); return false;</value>
      <webElementGuid>681bbdfe-3b37-4b65-8d3c-492d5f9d21de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>8e36b6c1-9b4d-4ea5-94e8-fef9ba6a2717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Tenancy</value>
      <webElementGuid>c38d3b27-79b3-46d2-acf7-78906a1de822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitecheckvalidmobilenewrightside&quot;)</value>
      <webElementGuid>d4758959-4616-4dd8-8aa6-3966c113ed52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='invitecheckvalidmobilenewrightside']</value>
      <webElementGuid>9efe8a35-370b-4961-95ec-71cb1e0b1989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickytypeheader']/div[3]/div</value>
      <webElementGuid>aaf43f65-ae24-41fb-9587-d738f6597039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new'])[1]/following::div[10]</value>
      <webElementGuid>42deb41d-1440-482d-a1ca-1e9cffd48f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[1]/following::div[21]</value>
      <webElementGuid>71cd04b3-6c03-401d-8055-757578708410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[3]</value>
      <webElementGuid>3ae5a3f1-9f4b-43b8-bf07-96bec6b53f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::div[3]</value>
      <webElementGuid>92652e7e-2628-4c85-980f-46681a8c517e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[3]/div</value>
      <webElementGuid>ca8d31c3-80c2-4daa-bfe8-9eb1946d01c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'invitecheckvalidmobilenewrightside' and (text() = 'Update Tenancy' or . = 'Update Tenancy')]</value>
      <webElementGuid>27f469fd-91ca-4611-9497-61c056f51aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
