<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Electrical Certificate - Expiry date field</name>
   <tag></tag>
   <elementGuidId>8fff380b-08bc-459d-82ab-2f865b9eb093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='electric_certificate_expiry_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#electric_certificate_expiry_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7ef176c-1009-404c-b435-ef94675bc9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e6eeab3-8db3-4ab2-ab6f-2a8e3b62c33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>electric_certificate_expiry_date</value>
      <webElementGuid>a4a17273-a3b5-4225-ae46-191ecf2be1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input datepicker hasDatepicker</value>
      <webElementGuid>e47801eb-4a11-453d-a9ca-85d0288eebe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiry date</value>
      <webElementGuid>97ee6249-9d59-475f-8064-43d990be5f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72b1b965-bff8-496a-adea-169f5f4d15dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[electric_certificate_expiry_date]</value>
      <webElementGuid>229bdb06-65ac-49b5-af5f-154d1c1e9abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;electric_certificate_expiry_date&quot;)</value>
      <webElementGuid>e6987c62-4c15-4f65-b20e-102775b32b3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='electric_certificate_expiry_date']</value>
      <webElementGuid>018ecf91-6bfd-4302-b137-d8da0f0c8a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='upload_electrical_certificate_expiry_form']/input[4])[2]</value>
      <webElementGuid>54f9dd5d-c393-45a5-9524-2810f20d74df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/form/input[4]</value>
      <webElementGuid>e80ce642-f134-4d00-91bc-fbe1e042833c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'electric_certificate_expiry_date' and @placeholder = 'Expiry date' and @type = 'text' and @name = 'tenancy[electric_certificate_expiry_date]']</value>
      <webElementGuid>c55c0dcc-c0de-4a65-84ef-b6d414a28f3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
