<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Electrical Certificate - Close (x) bt</name>
   <tag></tag>
   <elementGuidId>c2b141b8-8432-4e64-9f3d-8fee2e41e858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close_electric_certificate_expiry_date_div > i.fa.fa-times</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='close_electric_certificate_expiry_date_div']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5e081bcf-6396-452d-ba7c-2556d5cee0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times</value>
      <webElementGuid>9f22c8a2-8f3e-448e-bb59-ca7c3153f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6890d88e-bc80-424d-9273-1e32fc3b86dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close_electric_certificate_expiry_date_div&quot;)/i[@class=&quot;fa fa-times&quot;]</value>
      <webElementGuid>082ac84a-4906-4aa6-bd09-85497d98a52c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='close_electric_certificate_expiry_date_div']/i</value>
      <webElementGuid>80bee533-b628-4113-a84a-97e93f4285c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/form/span/i</value>
      <webElementGuid>10bca99d-e907-4a0e-8c15-6a21bf490a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
