<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Energy Certificate - Expiry date field</name>
   <tag></tag>
   <elementGuidId>a4ae5009-85bd-42b4-b74b-70b3c2b3f8b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='energy_certificate_expiry_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#energy_certificate_expiry_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebb2c08a-0113-4871-bd4f-e20ec8486b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c133b240-87ab-44d3-aa29-15ce4b302f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>energy_certificate_expiry_date</value>
      <webElementGuid>a838b028-0704-4479-a17b-8ca99442c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input datepicker hasDatepicker</value>
      <webElementGuid>2c012368-2425-4f3a-b00a-190223bcba68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiry date</value>
      <webElementGuid>4ea9da3e-4a3d-4db5-9a91-cf88a31fead0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f185f463-8e57-4159-be23-83fd41b937ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[energy_certificate_expiry_date]</value>
      <webElementGuid>7251ad08-d483-4214-aade-90ba5f2d4bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;energy_certificate_expiry_date&quot;)</value>
      <webElementGuid>e08518d4-99bc-4cb6-8722-a2b39551a9a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='energy_certificate_expiry_date']</value>
      <webElementGuid>dadcd758-85c4-46e9-9f26-36939e141e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='upload_electrical_certificate_expiry_form']/input[4]</value>
      <webElementGuid>bd3f5b84-260e-4587-8e94-9b4589a6de8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/input[4]</value>
      <webElementGuid>311ac816-fd81-44ea-b98f-8ceef3b70450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'energy_certificate_expiry_date' and @placeholder = 'Expiry date' and @type = 'text' and @name = 'tenancy[energy_certificate_expiry_date]']</value>
      <webElementGuid>62dee2e2-96c4-4914-b8f0-a26245d02d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
