<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enquiries - Restore bt</name>
   <tag></tag>
   <elementGuidId>1e98a6d3-d7ae-4f5f-8997-78d2047fc6dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submit_undo_archive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit_undo_archive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e75d96dd-abb7-4e49-b3e1-06b0bd95fb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_undo_archive</value>
      <webElementGuid>589dacd2-071d-486b-aa56-850e7628f0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RESTORE</value>
      <webElementGuid>74c7e385-fb22-4cd1-91ba-dafa1802de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_undo_archive&quot;)</value>
      <webElementGuid>c06879de-1c9b-4a13-b65b-9848f2bf437c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submit_undo_archive']</value>
      <webElementGuid>dd0df8fd-554a-4acc-88ca-01a26165e95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='enquiry_applicant_details']/div/div/div[2]/div/a</value>
      <webElementGuid>ffe0b37b-ab9b-48fa-9ee6-17714bd8c1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'RESTORE')]</value>
      <webElementGuid>bddda705-61ab-4471-8523-e27178529cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIT ENQUIRY'])[1]/following::a[5]</value>
      <webElementGuid>1cc5d209-7047-4b45-82b8-eccb74418df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add additional email address'])[1]/preceding::a[4]</value>
      <webElementGuid>1babb210-90b7-45ef-86ca-0aaddbbb989b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add additional email address'])[2]/preceding::a[4]</value>
      <webElementGuid>315948b3-a6de-4caa-a80a-9965d558f7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RESTORE']/parent::*</value>
      <webElementGuid>b57dd92b-12c6-46f2-869b-ae50027bc253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a</value>
      <webElementGuid>3692e871-ef24-40b9-a807-d5d765c0eab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'submit_undo_archive' and (text() = 'RESTORE' or . = 'RESTORE')]</value>
      <webElementGuid>2a7f4b09-1b66-42a3-82ff-bd80547b8e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
