<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enquiries - Add (plus) bt</name>
   <tag></tag>
   <elementGuidId>2bab679e-f889-4111-8b24-b4dc67a8afeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#importaddproperty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='importaddproperty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>213ac109-98d6-4b07-9951-f3bfd2efc633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/plus-solid.svg</value>
      <webElementGuid>6dc3765f-6fee-4a8b-ab92-b3961209de6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>importaddproperty</value>
      <webElementGuid>8cf72f75-2358-4596-8666-6485de2da509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;importaddproperty&quot;)</value>
      <webElementGuid>8b8705c0-8999-4308-a496-bb14d9a5aebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='importaddproperty']</value>
      <webElementGuid>e2c53fd8-8bbf-442e-8677-b80806f01ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>6906d98c-a1b6-4371-bf15-4352ab48a0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/plus-solid.svg' and @id = 'importaddproperty']</value>
      <webElementGuid>13f354ce-4f0a-4649-a88e-6b545866f319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
