<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enquiries - Contact Details - Add Enquiry bt</name>
   <tag></tag>
   <elementGuidId>0c7bee50-d604-4d1d-a7ee-bba7fa071c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitapplicantdetails</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submitapplicantdetails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>451a43e6-9ce4-40df-adfe-ef2d4e243c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitapplicantdetails</value>
      <webElementGuid>f321f313-88dc-4449-8785-fe8a360e99d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>565f9c74-db55-462d-8491-4c45784c5bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Enquiry</value>
      <webElementGuid>e5542a9b-21a7-4c24-ac0e-51c4d8d59d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitapplicantdetails&quot;)</value>
      <webElementGuid>830f47f6-b2e2-4031-a9f6-bd390875f024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='submitapplicantdetails']</value>
      <webElementGuid>337585f5-0935-44d8-8a30-f238e1eb16f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickycreate']/div</value>
      <webElementGuid>7606cd40-eb67-47bf-b934-cbede184761e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annually'])[1]/following::div[9]</value>
      <webElementGuid>da852631-5749-4d29-bc22-7df51f1e5e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/following::div[10]</value>
      <webElementGuid>8c141838-f00c-4ff0-92a4-3e020afe2ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[1]</value>
      <webElementGuid>edd3bc02-c2c4-4f75-a854-1a36f05ed656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::div[1]</value>
      <webElementGuid>1dc5449d-6b80-4630-a789-85d12d97e013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Enquiry']/parent::*</value>
      <webElementGuid>763b6948-a11d-4cf1-8484-374747780eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>b9b12a48-a55f-4244-915c-bb6ac6d6025a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'submitapplicantdetails' and (text() = 'Add Enquiry' or . = 'Add Enquiry')]</value>
      <webElementGuid>235f5252-2e9c-48b3-986d-49c13356522f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
