<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enquiries - Contact Details - Email address</name>
   <tag></tag>
   <elementGuidId>b426e209-1d37-465f-ac8e-0b66177579a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22b3b811-432a-424f-bfab-5ba18639b033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>972d38c9-4f35-42d7-afa7-6961f9ca465b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string form-control input-lg</value>
      <webElementGuid>e348d552-b9a2-4c0f-b6e9-211eb1ba4bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_address</value>
      <webElementGuid>42bfa20b-f437-4d9b-8608-581ff8c67c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enquiry_applicant[email_address]</value>
      <webElementGuid>925c78d2-7e0c-4567-8fe1-4c4337aacb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>6c403979-3e3e-4c4c-be7f-ca0a16ce572f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_address&quot;)</value>
      <webElementGuid>808e2960-b83d-426b-871f-0d7156eb126f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_address']</value>
      <webElementGuid>654d3395-84c7-4de7-9b32-18378c08e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='applicantdetailsform']/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>6f0b9185-56ef-4e8b-9b05-52ed4bf4a6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>89a68082-7c1b-41c4-8aca-10896a1caa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'email_address' and @name = 'enquiry_applicant[email_address]' and @placeholder = 'Email address']</value>
      <webElementGuid>985d2a72-ad81-4690-a7a5-cebc8c9da308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
