<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>For Void Address - Start bt</name>
   <tag></tag>
   <elementGuidId>3fd7092e-32f0-49f4-93b1-c8bc0f820b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;addRecordModal2('Po Box 363, TRIMDON STATION, TS29 6YU, UNITED KINGDOM', '16386','false');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkstabletable_tenancies > tbody > tr:nth-of-type(2) > td:nth-of-type(6) > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d13ffc9-4039-4f26-babd-d83ef76d9f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addRecordModal2('Po Box 363, TRIMDON STATION, TS29 6YU, UNITED KINGDOM', '16386','false');</value>
      <webElementGuid>36a9fb74-9de6-42c5-8fb9-b053ba77f907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0b0b6e97-c5a1-4314-8343-becfe28052b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>property_in_tenancy</value>
      <webElementGuid>6975eeec-53ed-458f-9111-3c0bfb45436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>66ee91bd-b1a3-4f4e-9435-dfd53d8a62ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>2cee63f8-a9b1-4838-9fc7-a17f38c2b409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkstabletable_tenancies&quot;)/tbody[1]/tr[2]/td[6]/p[1]/a[1]</value>
      <webElementGuid>1f9b8837-ff70-4768-a36d-8117cf4b74bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;addRecordModal2('Po Box 363, TRIMDON STATION, TS29 6YU, UNITED KINGDOM', '16386','false');&quot;]</value>
      <webElementGuid>dd56f1d4-092a-4c97-8dba-160616a98e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable_tenancies']/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>58fb2cf9-e558-47cd-b535-cb4a8748a992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start')]</value>
      <webElementGuid>651257dc-4c13-4a89-932b-0cc293f47e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[1]/following::a[1]</value>
      <webElementGuid>3b22b295-c7d3-46ee-9013-86d83461fcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Listing'])[2]/following::a[2]</value>
      <webElementGuid>a8b298c4-f6c0-48e1-9066-32849175f5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[2]/preceding::a[1]</value>
      <webElementGuid>8223c533-26b6-4d03-a11c-9ab43a126202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Barbers of Windermere, 8 Victoria Stre... LA23 1AB'])[2]/preceding::a[2]</value>
      <webElementGuid>6dd4aa15-19f5-488f-8540-11f6c0540dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>54b1a946-dab9-4b23-80da-37bab6e2a4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>da564b6a-c1bb-433f-9279-c8961c5770c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>31b70ef6-4509-4ed0-86c2-fed653c6db74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
