<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Gas Safety Certificate - Expiry date field</name>
   <tag></tag>
   <elementGuidId>d39f2061-0b3d-4e71-9878-30859acacbd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gas_safety_expiry_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gas_safety_expiry_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c3d7cb5-e54c-4a1a-8c06-c6ac6bf0e74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f96adc7e-9a96-47c6-87fb-ad7bf62cbba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gas_safety_expiry_date</value>
      <webElementGuid>aa5631de-97ee-4a38-9744-d651d81776dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input datepicker hasDatepicker</value>
      <webElementGuid>3d234027-c0e9-44ff-bcef-9d036ba23733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiry date</value>
      <webElementGuid>f969e591-9fcf-4ffd-903a-e3028e1710a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e33504e-2a1b-4658-a8a8-5cddd61ea29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[gas_safety_expiry_date]</value>
      <webElementGuid>bd37646e-42c8-468f-8fcd-2c2dfdd86491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gas_safety_expiry_date&quot;)</value>
      <webElementGuid>ea5b1595-7729-4240-ae87-8bee140e9e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gas_safety_expiry_date']</value>
      <webElementGuid>3ae691af-fcef-4a74-b98a-b61929bd1a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='upload_gas_safety_expiry_form']/input[4]</value>
      <webElementGuid>7fa6e561-c97b-41c6-9890-9d5593c08df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/form/input[4]</value>
      <webElementGuid>8d80b59e-c591-4a1d-bb8d-a7497c9bc7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gas_safety_expiry_date' and @placeholder = 'Expiry date' and @type = 'text' and @name = 'tenancy[gas_safety_expiry_date]']</value>
      <webElementGuid>852b03ed-9313-4727-bcd5-044c8280ba9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
