<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>In Tenancy - Edit End date - Confirm bt</name>
   <tag></tag>
   <elementGuidId>8f7ea1bc-5cb1-497a-826a-8595fe1f439a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refundbtnv4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refundbtnv4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5cff89d5-bc45-48fa-93fa-7987792366b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fba9149a-a8ef-45d8-a58a-6ec48a154238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0d38324b-2584-4034-b7ac-f6893d80ecdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refundbtnv4</value>
      <webElementGuid>38cade0a-1dd9-47f8-8436-f064c96735ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-success</value>
      <webElementGuid>ec05d5d9-02db-43f3-8525-e318061ba753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>5ebdbd50-f8d8-4260-9970-3bb40f58d913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refundbtnv4&quot;)</value>
      <webElementGuid>b6cc0ce9-9fdd-4c25-bd44-300753cc1397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refundbtnv4']</value>
      <webElementGuid>fcec512a-309d-47c1-8867-5a20cdf13049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='end_tenancy_form']/div/button</value>
      <webElementGuid>dbafd982-1fbf-425e-9e2b-ce4c62bc4f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a new end date for the tenancy'])[1]/following::button[1]</value>
      <webElementGuid>a04d1ab0-1717-4ad2-883a-71831d29f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Rent Guarantee - £215 inc tax'])[1]/following::button[1]</value>
      <webElementGuid>a91147fc-5958-42ef-8e3d-e6675b8aa6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to end this tenancy?'])[1]/preceding::button[1]</value>
      <webElementGuid>d9882f1b-c098-4d5b-b5ca-5c9354cdc008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Tenancy Ending'])[1]/preceding::button[1]</value>
      <webElementGuid>dce8e464-0222-42c4-a7c3-99052f2a2889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>ff62c0e4-bdf2-4c6b-93c8-18de30958094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>46e6e402-0e8a-44c4-a29e-a124f767141c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'submit' and @id = 'refundbtnv4' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>e0bc8736-2a35-4cb6-94ed-ddfd1f1b7355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
