<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>In Tenancy - Edit End Date textfield</name>
   <tag></tag>
   <elementGuidId>7545d1ba-9fc1-4d39-8939-b1c78bb1bc4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenancy_override_tenancy_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tenancy_override_tenancy_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52697e15-b927-43cf-82a5-d098650adeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enddate datepicker form-control hasDatepicker</value>
      <webElementGuid>46f1db37-8a83-47ce-bf1c-d1200ee88b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3318f2b1-f88f-4c31-a628-450d77d192e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[override_tenancy_end_date]</value>
      <webElementGuid>665df6a6-7894-4564-bf28-62b9bbda17aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenancy_override_tenancy_end_date</value>
      <webElementGuid>053d6287-696a-4fb1-b472-450bed818d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e91a7b67-212f-4d58-b455-0406d3fbf67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cbp-spmenu-push&quot;]/div[3]/div[@class=&quot;hover_bkgr_fricc4&quot;]/div[1]/form[@id=&quot;end_tenancy_form&quot;]/div[1]/input[@id=&quot;tenancy_override_tenancy_end_date&quot;]</value>
      <webElementGuid>6fead4fe-f5f4-40ce-a390-fcbcddc704ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tenancy_override_tenancy_end_date']</value>
      <webElementGuid>ad5c136e-0fd8-440a-9d2d-fffd4550a3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='end_tenancy_form']/div/input</value>
      <webElementGuid>0435c241-144d-4716-9246-7722c29fc1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cfc23fe0-409b-4b49-8940-99b42c2e9dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tenancy[override_tenancy_end_date]' and @id = 'tenancy_override_tenancy_end_date']</value>
      <webElementGuid>da2e4d52-c6d4-4c8c-a902-53d3b9e0d4cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
