<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>In Tenancy - Edit End Date bt</name>
   <tag></tag>
   <elementGuidId>bed9fcc0-f416-4351-a067-a1983efdfa4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_tenancy_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='end_tenancy_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>836396a1-0b26-4fb7-a2f9-c76b665a2360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trigger_popup_fricc4</value>
      <webElementGuid>2f0021ce-89fe-42e9-8018-4a74df32d415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cancel_tenancy</value>
      <webElementGuid>d37c86e8-6a88-4ce6-b90f-c66d61cc798f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>13ae3063-c6e0-4855-8fed-a9c5b48a71ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_tenancy_id</value>
      <webElementGuid>b9f17a82-8c4b-43b9-a508-53fe01d9be95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT END DATE</value>
      <webElementGuid>12bafb4c-3791-485d-b5bc-5c530949d090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/div[@id=&quot;checkstablecontainer&quot;]/a[@id=&quot;end_tenancy_id&quot;]</value>
      <webElementGuid>fab2a8a3-6ddf-4895-b461-6b036eec8fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='end_tenancy_id']</value>
      <webElementGuid>fb6f5396-b94d-4b33-980f-9ee784438d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkstablecontainer']/a</value>
      <webElementGuid>3c0c341e-8ff8-477a-84d7-09d0f8eb7a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EDIT END DATE')]</value>
      <webElementGuid>bbfafb18-36e3-4d75-9804-1c52ad40970a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit the end date if the tenancy is finishing early or becoming a rolling tenancy.'])[1]/preceding::a[2]</value>
      <webElementGuid>9e7bc7e3-1d57-4b0b-b4bb-bda6b63f51a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='END TENANCY'])[1]/preceding::a[2]</value>
      <webElementGuid>fcd3256c-be50-441e-9626-bd85af3d7940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDIT END DATE']/parent::*</value>
      <webElementGuid>a3bf7d16-bcaf-4666-a296-947cf3bec608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[53]</value>
      <webElementGuid>570d5b6a-8a63-4203-9bc0-60e105eb9827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>683d6fd3-eb63-4d87-b220-0e9dc7e2a7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'end_tenancy_id' and (text() = 'EDIT END DATE' or . = 'EDIT END DATE')]</value>
      <webElementGuid>8df05a1b-d5fb-45da-ba66-563b2aa57983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
