<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LTD date of incorporation</name>
   <tag></tag>
   <elementGuidId>6f613c44-43b7-4f60-813b-8559518a364e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='self_employed_date_of_incorporation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#self_employed_date_of_incorporation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adda1060-dd7e-47c9-b57c-60e521b01572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>self_employed_date_of_incorporation</value>
      <webElementGuid>63817937-6039-4834-b470-c4100a77274f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f694ccd6-1529-4857-a518-765a32dfcbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>844fd4a0-a8f4-42b3-bdff-d3a431891cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of incorporation</value>
      <webElementGuid>1c7b1673-9cde-4880-8a7b-94ec37615391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_date_of_incorporation]</value>
      <webElementGuid>ad9fbfcf-9b28-42d6-91d5-7356209cb264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;self_employed_date_of_incorporation&quot;)</value>
      <webElementGuid>8ac2fb10-8f36-41dc-adba-f628248ca9a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='self_employed_date_of_incorporation']</value>
      <webElementGuid>14b8cb24-9edd-4ad3-8e3e-7e80a54fb051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployeddirector']/input[3]</value>
      <webElementGuid>c3e5b48d-8f19-4e1a-8cb3-ddd7ec495fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[3]</value>
      <webElementGuid>83065911-86bb-4e89-bfa1-66832af78cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'self_employed_date_of_incorporation' and @type = 'text' and @placeholder = 'Date of incorporation' and @name = 'renter[self_employed_date_of_incorporation]']</value>
      <webElementGuid>a60eb052-7329-4adc-ae44-7004aa2d75be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
