<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add property_manual_city</name>
   <tag></tag>
   <elementGuidId>3e960593-1fd3-4af1-a000-080e877ab340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manual_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manual_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a805a0e0-6408-494a-922f-fae3282f6645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manual_city</value>
      <webElementGuid>4a3a1139-0812-45c6-9b67-0bb164f27fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6705a915-c8b8-4b14-b5e1-77209625c25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a171559c-db66-4123-9695-b1bcb01a971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Town/City</value>
      <webElementGuid>288da710-5130-48c9-bfb9-699abe0800e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual_city&quot;)</value>
      <webElementGuid>1c1dc017-c32d-4112-bf07-b8a7af32c311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manual_city']</value>
      <webElementGuid>f551070e-b2e5-45d3-a9d6-1b2845b37447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manual_prop']/div/input</value>
      <webElementGuid>3da5b9eb-1260-42ad-8c56-bd33a2bbe3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>d6e2cc4c-63a9-4050-b724-1a514e7f2c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'manual_city' and @placeholder = 'Town/City']</value>
      <webElementGuid>fadcf8c3-c280-4a8b-89e6-635f954708fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
