<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_09B7E guarantorname</name>
   <tag></tag>
   <elementGuidId>63cac08b-f892-40d5-b353-4142ed4e275e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invite_guarantorname_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invite_guarantorname_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb2dfe06-ef63-4499-8f84-48b194ca6a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d98d15e1-f368-4312-9a4d-3476cb86630d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>5a3a6b27-418c-47cd-8549-bd501abd6158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor name</value>
      <webElementGuid>fb3038a0-a789-4198-b02c-10185e460d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1371511e-63d0-448a-aacb-65e9d7bc891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[guarantorname_1]</value>
      <webElementGuid>9671bd37-eccd-4201-9d3f-ed947c2fe0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invite_guarantorname_1</value>
      <webElementGuid>64f52b2e-27ce-431e-a5e0-81cc0260e59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite_guarantorname_1&quot;)</value>
      <webElementGuid>58f62289-d4dc-4cbe-b0c5-bcce904db2b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invite_guarantorname_1']</value>
      <webElementGuid>55d48d7f-7a0a-4444-8686-568ebdd04b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guarantordiv1']/div/input</value>
      <webElementGuid>47ed764e-b16b-45ef-abe6-1eb97e80ee5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input</value>
      <webElementGuid>60b190cb-83d2-4aa8-95f0-d4bc642c9758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Guarantor name' and @type = 'text' and @name = 'invite[guarantorname_1]' and @id = 'invite_guarantorname_1']</value>
      <webElementGuid>8bff9b55-2468-410d-ae74-f0518176f12b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
