<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add property_manual_post_code</name>
   <tag></tag>
   <elementGuidId>61c3fbe9-a9c5-4ceb-9f61-f15dfee527a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manual_post_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manual_post_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bc3f8a9-a26c-413c-ae2d-e9a99578a037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manual_post_code</value>
      <webElementGuid>7a14b643-e047-45fa-b502-842ed0c43a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4cc2393-900e-41b3-a983-3f6937f393a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2be0aeaf-2c43-4876-9283-ef3939012846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>a871ac4c-affa-44ba-9ce1-fd5ec8d789e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual_post_code&quot;)</value>
      <webElementGuid>0a2b5a6a-fad6-43d9-a2b4-559d4cf29366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manual_post_code']</value>
      <webElementGuid>b5004eba-3e61-460f-8c03-1026314022d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manual_prop']/div/input[2]</value>
      <webElementGuid>37f836e8-b237-473b-b2e6-a473203d0daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input[2]</value>
      <webElementGuid>0ba35373-25cd-4f6d-84e1-93da22e90034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'manual_post_code' and @placeholder = 'Postcode']</value>
      <webElementGuid>d90af8bb-d533-44bc-95f7-8209b26b75e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
