<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenancy Renewal bt</name>
   <tag></tag>
   <elementGuidId>95ade047-7424-4f32-aba5-96e37db08cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renewal_only_radio_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#renewal_only_radio_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84828498-62e9-4294-b399-b842b0422d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renewal_only_radio_btn</value>
      <webElementGuid>dddd3379-882d-4902-9943-cd4baa95f569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refortenant</value>
      <webElementGuid>e3842982-47f9-4486-9f35-c3950bd7d22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ad4db79c-1f1e-4ced-930a-e54862f74887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>renewal_only</value>
      <webElementGuid>1597cc94-5d95-4b52-a346-3e66db57bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renewal_only_radio_btn&quot;)</value>
      <webElementGuid>06173ec3-b724-4c94-a9ad-57e3a7f8dd23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renewal_only_radio_btn']</value>
      <webElementGuid>83ef3090-d5b0-42c0-acfc-ac033d92b3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/table[2]/tbody/tr/td[3]/label/input</value>
      <webElementGuid>d6a46d53-65dc-4b81-96c1-70d857b99d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/label/input</value>
      <webElementGuid>b889a879-7cdc-4ca8-8ffe-fc39c242e7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renewal_only_radio_btn' and @name = 'refortenant' and @type = 'radio']</value>
      <webElementGuid>8b65c7bd-050e-44ce-bcbc-eb22d238e3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
