<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add property_searchbar</name>
   <tag></tag>
   <elementGuidId>15243997-6bf7-4e18-8817-95f82a129157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc545134-5e3e-4ac8-b311-8391f8d685a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop</value>
      <webElementGuid>430fc2f6-d2c0-4c64-951a-61958612d7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f79a35e2-935a-4d21-a203-7fedb199f737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>b4061383-9041-4a56-952a-683706219e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select rental address (do not copy paste address)'</value>
      <webElementGuid>635d4e72-6b22-45c8-8e04-b5b1386e6df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select rental address (do not copy paste address)</value>
      <webElementGuid>2dcc05a0-e52a-4e56-8079-d2b1ac628d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55a1a107-6257-41ad-9786-05d598b1e39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[prop]</value>
      <webElementGuid>6281ab61-4419-4d26-a685-a4c0ef405289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop&quot;)</value>
      <webElementGuid>bd1d6d20-a230-4184-b00a-54e7d6b72dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop']</value>
      <webElementGuid>2adaf837-af78-442a-9e32-7be7c0b6e7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/input[3]</value>
      <webElementGuid>7df3158c-2a88-419c-a824-baa71546ccb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/form/input[3]</value>
      <webElementGuid>fe19aed4-7f2a-48d0-8d57-290c700c5dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop' and @placeholder = 'Start typing and select rental address (do not copy paste address)' and @type = 'text' and @name = 'invite[prop]']</value>
      <webElementGuid>8367f534-2f08-42f4-9395-f1204ce40444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
