<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add property_manual_line_1</name>
   <tag></tag>
   <elementGuidId>0aa995f0-c3ba-407b-905e-375696bc4570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#manual_line_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manual_line_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b4bcf79-441a-49b4-b312-643265b7e54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manual_line_1</value>
      <webElementGuid>aee616a2-a98c-437c-a442-c3f13b1f4b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fc37cc5c-5616-421c-8dc4-db8396b1e852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd6ac707-4124-45c5-bcb1-ef0bb28d2fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Line 1</value>
      <webElementGuid>ccf2eb59-2efb-4b41-bed2-681da89f23eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manual_line_1&quot;)</value>
      <webElementGuid>aaf06d3c-c459-4e8c-9331-d89839d6b27a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manual_line_1']</value>
      <webElementGuid>ce9855d9-3f97-4cc3-858b-19e2cf865c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manual_prop']/input</value>
      <webElementGuid>3a4ac2db-3c95-4b2b-a694-144360494a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/input</value>
      <webElementGuid>413e9f48-2d43-479d-8dbf-f1bb558a4ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'manual_line_1' and @placeholder = 'Line 1']</value>
      <webElementGuid>4ce6db19-758e-4c2e-b03d-6fa4b11efea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
