<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LTD job title</name>
   <tag></tag>
   <elementGuidId>9e8aa7ff-9018-4572-bc76-8a1d9c8eebf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='directorjobtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#directorjobtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13e00887-45d0-447a-b6dd-6775761c29fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>directorjobtitle</value>
      <webElementGuid>e132dfb3-be08-4120-a482-2c759dc3d811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0fa3665-0671-440c-9087-1a2309f15317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>709b80af-8ef6-47f2-b3ef-e7ca680534cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title</value>
      <webElementGuid>65591687-20ef-40d6-9643-1ed846a0945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_job_title]</value>
      <webElementGuid>b726ea2d-0104-41b6-b4c3-1917e3ff59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;directorjobtitle&quot;)</value>
      <webElementGuid>5a5c690c-4d19-439f-bc4e-be36a5910eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='directorjobtitle']</value>
      <webElementGuid>14665b69-6af4-45b5-a334-894c05bf9f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployeddirector']/input[4]</value>
      <webElementGuid>56aff6d1-2b4e-492b-a47a-53fdb3984714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[4]</value>
      <webElementGuid>9d7e23b0-55aa-4eb5-8bd9-7a087ba87d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'directorjobtitle' and @type = 'text' and @placeholder = 'Job title' and @name = 'renter[self_employed_job_title]']</value>
      <webElementGuid>67ed4003-70f2-4a9b-9f41-2c62ad2691d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
