<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_09B7E_guarantoremail</name>
   <tag></tag>
   <elementGuidId>6e1fed7f-ad3f-4a44-980d-f4911614ddb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invite_guarantoremail_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invite_guarantoremail_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7226f541-57c7-40b8-9767-fe790b141344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94b12b86-06cc-4909-a921-2d73914de1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>2d7f917d-ffab-49c9-8195-1e07582b6d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor email</value>
      <webElementGuid>ed47c804-2cbd-4075-94df-1ecbbd784ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>527e010a-e1ff-4b2e-8fa7-9802b8d348ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[guarantoremail_1]</value>
      <webElementGuid>6b6ff10c-d656-4e62-bb29-4166de53bc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invite_guarantoremail_1</value>
      <webElementGuid>75ebbe58-d38d-4fd3-90ee-f11a83f5a3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite_guarantoremail_1&quot;)</value>
      <webElementGuid>14886cd3-6cd1-43f4-bd8c-ae7bec6b845e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invite_guarantoremail_1']</value>
      <webElementGuid>c73436d9-8de1-4ce3-ba91-fd0460a3ad76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guarantordiv1']/div/input[3]</value>
      <webElementGuid>14442925-091a-42b6-a54e-5d62d5eee9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input[3]</value>
      <webElementGuid>c8ac76d1-80ad-4398-bad7-ea643b45361a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Guarantor email' and @type = 'text' and @name = 'invite[guarantoremail_1]' and @id = 'invite_guarantoremail_1']</value>
      <webElementGuid>de0ff3ac-f4a4-4b54-8555-77bb3d6f6b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
