<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_09B7E guarantor mobile</name>
   <tag></tag>
   <elementGuidId>1cfa9e78-8a76-4561-b03d-fea2a65f445e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invite_guarantormobile_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invite_guarantormobile_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76cb8f85-af01-46de-a8bf-bb9d77cade6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4487b04-159a-4690-bfdb-12843c497a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>c7050fbb-b9db-4b49-b018-947613a80b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor mobile</value>
      <webElementGuid>83d7787b-1b5f-41ef-a17f-146abee275c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>bfb749ed-1ead-4197-98c8-536ebcab17be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[guarantormobile_1]</value>
      <webElementGuid>db03e3af-9176-44aa-9176-3058e61b48aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invite_guarantormobile_1</value>
      <webElementGuid>d7c3bedd-62e7-4ca1-a373-2a0be511b2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite_guarantormobile_1&quot;)</value>
      <webElementGuid>3d3b6cc2-556f-4c32-9228-c50334937343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invite_guarantormobile_1']</value>
      <webElementGuid>c073cb99-a27c-45c3-ab22-2ce7022fd20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guarantordiv1']/div/input[4]</value>
      <webElementGuid>4b5d48fc-ec18-4162-bd4d-589abc865a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/input[4]</value>
      <webElementGuid>93246c4c-2ded-4f4b-a24e-a8bbf6519127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Guarantor mobile' and @type = 'tel' and @name = 'invite[guarantormobile_1]' and @id = 'invite_guarantormobile_1']</value>
      <webElementGuid>eb213830-4ea2-4060-b2b5-7f1368e1ac8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
