<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add property</name>
   <tag></tag>
   <elementGuidId>9f750902-71dc-48fe-a74a-dd27ab9bd217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1b07b90-9c49-4ee1-af96-41c45e0ab733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop</value>
      <webElementGuid>48a939ed-0703-4f83-8205-fbc447bcb4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ed895dac-5925-48bb-a176-7dfbbfe6ae8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>94eb099f-ba70-4f15-aa93-6e4da271b913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select rental address (do not copy paste address)'</value>
      <webElementGuid>fb35e8a9-1550-4c8d-a155-ba9cedab4cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select rental address (do not copy paste address)</value>
      <webElementGuid>df54f6dc-a462-40c6-98f9-88ab1cfec927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a819a58-ac74-4bef-8a1a-9be487a942ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[prop]</value>
      <webElementGuid>4d99bac7-0886-4369-b79a-46fe1928e597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop&quot;)</value>
      <webElementGuid>2cdb769f-951b-4361-9cc7-a71f768c3545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop']</value>
      <webElementGuid>0834684b-888c-4c3c-94da-e4d7cf32a103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/input[3]</value>
      <webElementGuid>419b8b8d-2dc3-43cf-bce8-d72408163dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/form/input[3]</value>
      <webElementGuid>50d9455b-fd32-47d1-901a-a8cfb29401c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop' and @placeholder = 'Start typing and select rental address (do not copy paste address)' and @type = 'text' and @name = 'invite[prop]']</value>
      <webElementGuid>cafee667-fe9e-40f6-b047-96d957c5ccef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
