<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LTD Company name</name>
   <tag></tag>
   <elementGuidId>b288272a-1006-4de3-b744-ec6743b0fcc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='directorcompanyname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#directorcompanyname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98f908d0-a6fe-4f70-98bb-38cf46013eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>directorcompanyname</value>
      <webElementGuid>5f9c0f96-4789-419a-8be3-ec3774c5f95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>629c805c-7be5-4d7b-acd7-39b1e09a10cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>469620bb-e0cc-4fd1-a95f-666d6fd06002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Registered company name</value>
      <webElementGuid>58fd638c-d7f5-4ca0-86a5-12c3e8bc3a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_company_name_manual]</value>
      <webElementGuid>665121a8-5a0f-442e-8437-51718caacca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;directorcompanyname&quot;)</value>
      <webElementGuid>f0786a73-4fc3-4c7a-aa88-303987b703e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='directorcompanyname']</value>
      <webElementGuid>bd7ec21b-2051-4d20-a74e-a48c02232740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployeddirector']/input</value>
      <webElementGuid>9b50b7bb-747f-4814-9d44-9d6d3863b322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f5ff92e4-a77b-4d39-9000-80408cb01957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'directorcompanyname' and @type = 'text' and @placeholder = 'Registered company name' and @name = 'renter[self_employed_company_name_manual]']</value>
      <webElementGuid>400c0acd-66cb-4686-8163-2ae8a1c3c534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
