<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LTD Company number</name>
   <tag></tag>
   <elementGuidId>da48eb62-6486-43ad-b586-fafd41a9d948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='self_employed_company_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#self_employed_company_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92d1261c-c040-42bb-beef-b9e5894457a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>self_employed_company_number</value>
      <webElementGuid>fc3fddad-b546-43e8-a4a4-cb5ebe1da91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9187a976-6d65-43d5-afc8-ad5fe1acf257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>ca94788b-79fe-4379-9ee3-c099bde753ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company number</value>
      <webElementGuid>c7f04b6c-507e-49a5-a8dd-a6b2f2f2477c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_company_number]</value>
      <webElementGuid>e66fac7f-eaf0-49ed-8733-f68247c813c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;self_employed_company_number&quot;)</value>
      <webElementGuid>c20e1eb0-1c06-4ae1-86d5-00500a9b2e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='self_employed_company_number']</value>
      <webElementGuid>c3c1cd6e-19e2-4cbb-8de2-e0621ba31e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployeddirector']/input[2]</value>
      <webElementGuid>776af99e-66ce-41f6-ae30-72019ec3e376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>4716a1fe-6f7f-40ae-a496-f56bcf7cbd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'self_employed_company_number' and @type = 'text' and @placeholder = 'Company number' and @name = 'renter[self_employed_company_number]']</value>
      <webElementGuid>8d286571-4e5a-4cf1-b3b3-6398b46f7a68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
