<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InTenancy - Add RG bt</name>
   <tag></tag>
   <elementGuidId>50cf6ac9-d3b5-499e-bc18-b238b06d5cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal_show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal_show']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>248969ae-32fd-4d29-a428-83aeb449ad7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal_show</value>
      <webElementGuid>a31fb3ec-33ce-4c0a-832f-6dbd9a0eb042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>righttorent</value>
      <webElementGuid>9a1d3961-ab46-423c-9a2d-7a826d08d7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>224395f3-eb33-4975-921f-1d42fd3d485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>modal_show()</value>
      <webElementGuid>b683981f-8398-445d-9ae3-327bbce3c084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Rent Guarantee</value>
      <webElementGuid>90aeeeba-f424-498b-9573-a4b2148d0bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_show&quot;)</value>
      <webElementGuid>cf79f8cf-d5b0-41b3-91e8-8c9d34c53e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal_show']</value>
      <webElementGuid>6573eefe-1558-46ec-a803-428951bca19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[4]/following::button[1]</value>
      <webElementGuid>387228ad-aef8-4c95-868e-75fd16d365c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='submit'])[3]/following::button[1]</value>
      <webElementGuid>c9a3a1de-d506-468c-8f0c-1e6ddd359e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[1]/preceding::button[1]</value>
      <webElementGuid>8d810bcc-d43d-4bab-9ee0-bfd8597e651d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Rentguara...'])[1]/preceding::button[1]</value>
      <webElementGuid>1df94004-d474-4e78-bda0-2497ce6c3dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Rent Guarantee']/parent::*</value>
      <webElementGuid>25f69e67-a929-4147-99f5-0eb4a055e182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/button</value>
      <webElementGuid>d2893225-27e5-4050-a768-44c7fe5e9910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modal_show' and (text() = 'Add Rent Guarantee' or . = 'Add Rent Guarantee')]</value>
      <webElementGuid>57d8859d-cf01-4005-bf59-da6bbcacdc0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
