<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Landlord AML - Business name_textfield</name>
   <tag></tag>
   <elementGuidId>b071b8c8-6f1b-4b31-9e4e-3dc4c0c3ebb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aml_business_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aml_business_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aed49a3-0fc9-4bed-8e4e-6904271f0d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>681e04f4-89ce-44f2-8b57-b8ed2f92aaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>96f3aab9-d164-40b4-a3ea-47eb996cde5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business name</value>
      <webElementGuid>40826354-9f0f-4f4d-8f5f-e4f3c72f3a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aml[business_name]</value>
      <webElementGuid>19fa45da-fe4d-4c1b-929f-0a176dc036d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aml_business_name</value>
      <webElementGuid>bb3477a2-5057-484b-ab99-27ba1faa81bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aml_business_name&quot;)</value>
      <webElementGuid>5b8db6cd-7679-4ece-aa50-65eb136ee884</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aml_business_name']</value>
      <webElementGuid>20b8357b-c84b-4542-99e2-702d74d16978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ownerbusiness']/div/div/input</value>
      <webElementGuid>2b7f577a-81fa-4081-bb5d-6eab980102ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>62cb1349-fa2d-45b0-b85b-c7e604da0dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Business name' and @name = 'aml[business_name]' and @id = 'aml_business_name']</value>
      <webElementGuid>165805f0-5be6-4a34-aa1e-122f63715806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
