<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Landlord AML - Beneficial owner (individuals) name</name>
   <tag></tag>
   <elementGuidId>d1f57861-a2de-450f-9f51-de98dc53ac4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aml_beneficial_owner_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aml_beneficial_owner_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9b5d530-f361-4e4e-945a-e5335932229c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e194cdbb-88a2-4736-b99a-d97c4a6de7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>395d6571-ea81-4968-a3bd-70889955b6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Beneficial owner (individual's) name</value>
      <webElementGuid>b3f7cbc6-1f7f-47e5-9cb2-930ff1d31ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aml[beneficial_owner_name]</value>
      <webElementGuid>fba118d0-c7f6-4abe-bc33-424a67ade9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aml_beneficial_owner_name</value>
      <webElementGuid>02d53bbe-d7f2-4f2e-a3dd-8ed9ffb0bd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aml_beneficial_owner_name&quot;)</value>
      <webElementGuid>ef82eac6-90fb-424e-9fb1-b7da4ae5e2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aml_beneficial_owner_name']</value>
      <webElementGuid>79004044-0ceb-4c4b-96cf-dc9d08f9c122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ownerbusiness']/div[3]/div/input</value>
      <webElementGuid>4d44f08a-5e2f-4d49-aa77-fdc7c70bf959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[3]/div/input</value>
      <webElementGuid>22e1fbd5-ef0f-4ce1-ad60-f8b3b7b9195d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = concat(&quot;Beneficial owner (individual&quot; , &quot;'&quot; , &quot;s) name&quot;) and @name = 'aml[beneficial_owner_name]' and @id = 'aml_beneficial_owner_name']</value>
      <webElementGuid>57a900ad-863a-46d5-8d67-67ff6a999acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
