<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Landlord AML - Cancel (x) bt</name>
   <tag></tag>
   <elementGuidId>b6b288da-e5ed-4c6f-ae74-08d346204912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='✕']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.string.optional.cancelhover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80b8512e-6186-41e6-91b7-8fdf5d064d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>8aa84737-9607-4cf4-81f8-b8f3f811c37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional cancelhover</value>
      <webElementGuid>b57e53cc-44ff-4268-95bc-49b88c2d3091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55be5b5f-15c6-4d37-a33f-5c854e717615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fed55ac4-7b46-492f-9dc1-b60718aa090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetsearch_amls&quot;)/a[1]/input[@class=&quot;string optional cancelhover&quot;]</value>
      <webElementGuid>2bdbd66b-c4af-47b2-bbc1-1fe6aeed8e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='✕']</value>
      <webElementGuid>e123ac9b-8222-442b-a3ad-5109f5eb29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='resetsearch_amls']/a/input</value>
      <webElementGuid>68552572-5d7a-41b8-b889-74ba1b9abc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>6d9e6c56-5749-4438-8114-1855b36dbe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>69e3c8df-411a-45a8-ad61-96630b4c07ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
