<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Landlord AML - Rental address field</name>
   <tag></tag>
   <elementGuidId>445a2685-b8db-4fcf-9721-2870e341fa57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acdaf93b-7fba-47c6-867d-86921cbc5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop</value>
      <webElementGuid>90dd01ae-bf60-4dab-bc05-4cc179be7df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>addanotherprop1(); firstpropertytoggle();</value>
      <webElementGuid>80618004-bad4-4ec7-996b-6e7c22212b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg addpropinputsu</value>
      <webElementGuid>261343ae-61d4-4fd8-9298-c07c393a86c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select rental address'</value>
      <webElementGuid>0aa8cb1b-575a-4ec5-a794-621650495358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select rental address</value>
      <webElementGuid>303a2507-0a0f-4a4c-a484-422a8762d4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27d00f74-6f2f-4676-9b32-020fc468868a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aml[newprop]</value>
      <webElementGuid>3adee5a2-624d-4e26-887c-87ca4588a8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb7d98b9-171f-489c-b280-43579b48ab9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop&quot;)</value>
      <webElementGuid>6d53ebba-8f75-42e7-8545-132b3c9652bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop']</value>
      <webElementGuid>3056dd17-e829-4b84-ae9e-9363cc27cf6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='property0']/input</value>
      <webElementGuid>efbb0d25-606b-46c7-a24f-54b89b1902eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>726dc4b0-1660-49e8-8702-183ce00bbcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prop' and @placeholder = 'Start typing and select rental address' and @type = 'text' and @name = 'aml[newprop]']</value>
      <webElementGuid>e61dcf81-0d6b-424d-966a-8e060d9c0ed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
