<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Landlord AML - Add Landlord AML bt</name>
   <tag></tag>
   <elementGuidId>b2708c7c-6de5-415a-b615-43a24b2c0696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addreferencingbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addreferencingbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f37999c-aa3b-409a-ab0b-1dc28c2d43b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>f492e460-418f-42d0-a0b6-4d2a54c16f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>c5ea700e-7e4b-4545-985d-e54055535f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Landlord AML</value>
      <webElementGuid>df67a12a-5f03-4d5c-a476-abc2a23e0c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addreferencingbtn&quot;)</value>
      <webElementGuid>39f04704-994c-4fe9-b090-067ded4a6b28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addreferencingbtn']</value>
      <webElementGuid>b6bf3347-9261-4a54-91a1-7369c95f8af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form[2]/div/div/a</value>
      <webElementGuid>d8d71053-a87f-4b12-9e9f-c9835afd40f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Landlord AML')]</value>
      <webElementGuid>02ec9c09-23ff-4736-9f71-70e58306f83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent Guarantee'])[1]/following::a[2]</value>
      <webElementGuid>8cebb18b-56a1-4cf5-9ce2-9bc21cf032e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right to Rent'])[1]/following::a[3]</value>
      <webElementGuid>5e0d6e2c-dd47-4236-bf67-56bac7524748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner is individual'])[1]/preceding::a[1]</value>
      <webElementGuid>77866878-9ac3-4edf-80f3-698fa1d82aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner is Business'])[1]/preceding::a[1]</value>
      <webElementGuid>39e2f479-b390-4fd0-b7f4-d281b64b77e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Landlord AML']/parent::*</value>
      <webElementGuid>b13375ad-b777-4822-a799-e8ff4a957e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/a</value>
      <webElementGuid>e1517771-f7df-4ef3-8a4b-ebcebc566f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addreferencingbtn' and (text() = 'Add Landlord AML' or . = 'Add Landlord AML')]</value>
      <webElementGuid>621b6741-5da4-4083-be4e-fc8a58c48b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
