<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing -Available to rent from textfield</name>
   <tag></tag>
   <elementGuidId>53e9ad90-e754-4946-846f-294569396332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#proposedmoveindate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proposedmoveindate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f5d5a6-5e82-4508-aa6c-179ec1c96f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a87d7ab-a16b-4fcc-8caa-d108dcd00a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>To be set</value>
      <webElementGuid>0487066b-c534-4d83-a193-df8181c6f936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional datepicker form-control input-lg hasDatepicker</value>
      <webElementGuid>b8dc703d-df1a-4985-b77d-d3713c9f2732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proposedmoveindate</value>
      <webElementGuid>55f441bf-4978-40fc-bf03-7bb5d7fa5506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3ed63d2-d438-483a-8dd8-56223fcd3700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advertisement[proposed_move_in_date]</value>
      <webElementGuid>4bb6571a-9c48-46c9-ba74-4ed7d03153db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proposedmoveindate&quot;)</value>
      <webElementGuid>24a72948-ce72-46e0-b0c3-d855231dbf0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proposedmoveindate']</value>
      <webElementGuid>ef5cd9f7-200c-449f-bda4-41fc007d03a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_advertisement']/table/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>cb51fd1f-9df4-4929-a4b7-cab888e28ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>2e08eb08-d84d-4a55-8a29-2da364b89156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proposedmoveindate' and @type = 'text' and @name = 'advertisement[proposed_move_in_date]']</value>
      <webElementGuid>9ce74934-af98-4e2e-8625-8e67ff353cb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
