<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Energy Cert - Potential textfield</name>
   <tag></tag>
   <elementGuidId>9d61e2c3-8080-49e0-bb2b-7091e66c235d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#potential_rating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='potential_rating']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac7115b2-4d4d-4068-85a6-6d1a4a2beb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4873169-e254-452e-b91f-fb306d823f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>potential_rating</value>
      <webElementGuid>c93a4d7b-1004-4455-b226-75314ad864eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>f5ce3924-2410-429c-a11a-ec0cd658050a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;potential_rating&quot;)</value>
      <webElementGuid>4e9b6933-61e6-4c51-ab99-290d1e5d683d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='potential_rating']</value>
      <webElementGuid>e8bb4d60-1606-4f7c-842f-5da26e696356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploaded_energy_certificate']/div/input[2]</value>
      <webElementGuid>9985e4db-fdec-41cc-8d82-9f71b91393e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>fa1982c7-aa68-4b31-9b12-de785c1e81df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'potential_rating']</value>
      <webElementGuid>e95f889a-ccbd-466c-8e42-8adc015cf564</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
