<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Number of Bedrooms dropdown</name>
   <tag></tag>
   <elementGuidId>56e80fc4-ea57-461d-b315-1fad726dd132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number_of_bedrooms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='number_of_bedrooms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bb5b2366-e362-458e-bab9-d9d6e6bca433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>d34e9fad-98d7-484b-b9c0-c8912154be0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_of_bedrooms</value>
      <webElementGuid>9ce730bb-17d4-4391-829c-9d03deac4fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select optional form-control input-lg</value>
      <webElementGuid>8300e1e8-1cd7-4c0a-abbc-396bdb75c9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select
                        1
                        2
                        3
                        4
                        5
                    </value>
      <webElementGuid>1a41955e-f510-499d-a1e1-d2a9f6bc9558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_of_bedrooms&quot;)</value>
      <webElementGuid>0aa8b089-b9fc-43d0-aa62-fe57ca063785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='number_of_bedrooms']</value>
      <webElementGuid>b8278f3c-4f14-4b56-8927-a587574eff6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='number_of_bedrooms_section']/td[2]/select</value>
      <webElementGuid>5017ff6c-3902-4353-b141-8d3bed9e6573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[3]/following::select[3]</value>
      <webElementGuid>085ade3f-985f-4498-a7e6-feb75a5d0654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[2]/following::select[3]</value>
      <webElementGuid>bdd24050-7af6-42a3-ac58-2c9ea008066f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square foot'])[1]/preceding::select[4]</value>
      <webElementGuid>76d0dce2-491c-415a-9e94-a24ae4228113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square metre'])[1]/preceding::select[4]</value>
      <webElementGuid>f5cc619a-4355-4ad4-a2f8-b5f3d3184dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/select</value>
      <webElementGuid>fd31ec11-11da-4596-ba6d-39cd4915161f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@selected = 'selected' and @id = 'number_of_bedrooms' and (text() = '
                        Select
                        1
                        2
                        3
                        4
                        5
                    ' or . = '
                        Select
                        1
                        2
                        3
                        4
                        5
                    ')]</value>
      <webElementGuid>b756ab81-0aee-42b1-b6bc-724b86903e8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
