<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Furnish Type dropdown</name>
   <tag></tag>
   <elementGuidId>8ce68c62-3467-4418-8042-ad4ded2cb637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#furnished_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='furnished_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d898458-9e5b-47dc-ad1d-c7e75ef11841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>41790e9b-0763-4c95-a6ac-a49542dc6b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>furnished_type</value>
      <webElementGuid>11e48902-ac4c-429b-9d37-f5dd04a65f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select optional form-control input-lg</value>
      <webElementGuid>73aa72e6-d9fb-4315-9fae-f140628effc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select
                        Furnished
                        Part-furnished
                        Unfurnished
                    </value>
      <webElementGuid>f20d8fe2-2e23-4f14-b79c-e381a1a30e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;furnished_type&quot;)</value>
      <webElementGuid>45626d1f-4fd1-45de-bdcf-48f9ce7175c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='furnished_type']</value>
      <webElementGuid>75053d7b-dbb4-4ca3-9e9c-df6019b3951d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='furnished_type_section']/td[2]/select</value>
      <webElementGuid>97aa01b4-bd37-471f-adc2-11af326c1cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[3]/following::select[6]</value>
      <webElementGuid>ffe6efa8-fb4a-485c-a59d-cf5188cb5927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[2]/following::select[6]</value>
      <webElementGuid>86fc530f-6ce4-4d0b-b8c3-ae5021bb2370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square foot'])[1]/preceding::select[1]</value>
      <webElementGuid>f7b204dd-227e-41d8-add2-8cb88cf72524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square metre'])[1]/preceding::select[1]</value>
      <webElementGuid>36a4bb76-e8d0-4269-980b-6a86cc1a79ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>b54c7cc7-723f-4b39-8d93-9c24f1aa69d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@selected = 'selected' and @id = 'furnished_type' and (text() = '
                        Select
                        Furnished
                        Part-furnished
                        Unfurnished
                    ' or . = '
                        Select
                        Furnished
                        Part-furnished
                        Unfurnished
                    ')]</value>
      <webElementGuid>baa28779-c445-49a6-8dcd-42b900d490a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
