<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Rental amount textfield</name>
   <tag></tag>
   <elementGuidId>3ed61f8b-ab90-4b46-80d9-338ccfc8516f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rentdone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rentdone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f4d2239-2003-4ce0-956f-e5f0300584b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rentdone</value>
      <webElementGuid>18398d14-6ad5-426b-9729-a6c3b5854d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3599e22c-db3b-424c-8d0f-17a67b582cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>39d1f767-86cd-48fb-bd2a-46813b725784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Amount (£)</value>
      <webElementGuid>b07c66b2-5737-4435-88c9-7302c850c4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c79072e-5817-40e3-af36-7bdaaa86ae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advertisement[rent_amount]</value>
      <webElementGuid>9b31504e-3f71-424e-a700-04903df6d309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rentdone&quot;)</value>
      <webElementGuid>efeb3684-da77-4b23-ac40-4498c09590ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rentdone']</value>
      <webElementGuid>63d091f0-fb4e-400e-85db-43a79fb0633d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_advertisement']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a913eb94-3b8e-459c-89e8-90a9e8b036bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>439acd7a-9131-413f-84d9-d946e1bcddfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rentdone' and @placeholder = 'Enter Amount (£)' and @type = 'text' and @name = 'advertisement[rent_amount]']</value>
      <webElementGuid>c41dab92-56cc-41bc-8baa-64cf3ea9ba5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
