<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Council tax band dropdown</name>
   <tag></tag>
   <elementGuidId>c21bffcc-b20f-4c68-9639-78f1d6e1874c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#council_tax_band</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='council_tax_band']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41db001c-a6fb-4a9d-9355-cdde79473d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>council_tax_band</value>
      <webElementGuid>4cb77cc0-5c2b-4949-8e6b-5834b7b3d22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select form-control input-lg</value>
      <webElementGuid>df843ec9-4023-4bbc-a1f7-514b8ca8c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Select
                    A
                    B
                    C
                    D
                    E
                    F
                    G
                    H
                    I
                    Not yet known
                  </value>
      <webElementGuid>a9a1a4b1-eb06-4780-bfa2-f27b23ed1c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;council_tax_band&quot;)</value>
      <webElementGuid>8f6da187-89c1-4a07-9865-b9f5ee4b5e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='council_tax_band']</value>
      <webElementGuid>cbd3a5b0-68d5-4342-956e-956ea068207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='depositinformation']/table/tbody/tr[10]/td[2]/select</value>
      <webElementGuid>ed7d3732-6938-42b4-8fa0-9b2de3140cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uploading...'])[1]/following::select[1]</value>
      <webElementGuid>6c9ec450-8248-41bd-95e2-bb7e48b20547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::select[1]</value>
      <webElementGuid>3a43f6fe-c836-4155-abc2-718c7d877577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/preceding::select[1]</value>
      <webElementGuid>08669ed2-41c1-4849-9aac-9bb4418e3abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/select</value>
      <webElementGuid>0adb04cd-efdb-4323-be75-c3d1231ef006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'council_tax_band' and (text() = '
                    Select
                    A
                    B
                    C
                    D
                    E
                    F
                    G
                    H
                    I
                    Not yet known
                  ' or . = '
                    Select
                    A
                    B
                    C
                    D
                    E
                    F
                    G
                    H
                    I
                    Not yet known
                  ')]</value>
      <webElementGuid>c5197040-254d-42c0-beea-3ba9f31cb6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
