<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Property summary textfield</name>
   <tag></tag>
   <elementGuidId>f4837b10-4b86-48f8-b96c-e569ecc54963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#property_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='property_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3587de56-2427-4fa3-aed4-01da2a293c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>property_summary</value>
      <webElementGuid>ea2b468d-ad9e-479b-b06a-4ff971bb1024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12502ce1-9b1c-4a45-b4fc-83e0dce95821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>906f6194-bcd5-4c74-8f26-20dec2c01a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c74cd987-8196-49b5-8b06-8632344cf19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>property_summary</value>
      <webElementGuid>9254f464-5ff7-4ad9-9911-8accafe8fbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your property summary...</value>
      <webElementGuid>538ac8f1-21b0-441a-beed-f11b705b01b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;property_summary&quot;)</value>
      <webElementGuid>6072b21f-805c-4967-b8a4-8484df562b3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='property_summary']</value>
      <webElementGuid>61f18871-0dd5-424a-8a24-23a25e8dba49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='property-description']/textarea</value>
      <webElementGuid>be54697e-8fbe-47c0-bfa7-c8c4deb7afe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bed8e400-9bbb-475b-bf48-e2e7b3455b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'property_summary' and @type = 'text' and @name = 'property_summary' and @placeholder = 'Write your property summary...']</value>
      <webElementGuid>fd7ebc3b-1da5-4e84-aaed-eeb9b2657d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
