<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Energy Cert - Current textfield</name>
   <tag></tag>
   <elementGuidId>0032c672-5f9b-4274-92ef-5cdfd829d8c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current_rating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='current_rating']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1f74388-40e2-44b2-a6fa-cad28a38e7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cb1d973-603a-427d-84b3-b2b343e3214a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current_rating</value>
      <webElementGuid>aeb15e94-40e6-41a5-9906-6d39c6f6ce04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-lg</value>
      <webElementGuid>c2e4da5c-ddfd-42f2-ac1d-870d4403fbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current_rating&quot;)</value>
      <webElementGuid>80b05db9-9901-4e1f-8629-cf03bb88d983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='current_rating']</value>
      <webElementGuid>9157842f-719f-4f6e-bebb-f9a3d8066ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploaded_energy_certificate']/div/input</value>
      <webElementGuid>b50edb91-7bef-4bd5-8b5b-fc7e1a675f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>5b448c56-3093-408f-a4f2-780190b7fcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'current_rating']</value>
      <webElementGuid>a56a1de2-28ea-4dd7-b104-7005af8a5a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
