<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Property type dropdown</name>
   <tag></tag>
   <elementGuidId>b0db419b-47dd-4d96-97f9-29674bc4d98c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='prop_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2a23c290-61a8-4dd9-a995-c988306fed52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>e2fab54f-0687-4aad-bf20-5b1045012bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop_type</value>
      <webElementGuid>7a92cacc-ca1a-4d3f-8b88-910b26927411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select optional form-control input-lg</value>
      <webElementGuid>36b0f858-aa8a-44d0-bd87-cfb3b05d3cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select
                          Flat
                          Detached
                          Semi-detached
                          Terraced
                          Bungalow
                          Studio
                    </value>
      <webElementGuid>1416059f-ee4d-41b8-8bae-534d5f2f7077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop_type&quot;)</value>
      <webElementGuid>cf4c6682-7e99-4478-8708-beb39ea8af26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='prop_type']</value>
      <webElementGuid>80a6a1d3-fbd7-4f60-8cc2-13e23ec7520b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='depositinformation']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>6edcbe82-e639-4cf4-87ab-0d85801aa05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[3]/following::select[1]</value>
      <webElementGuid>5db80ce7-ab1e-4d19-a865-22d795209f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[2]/following::select[1]</value>
      <webElementGuid>02c9cb4a-e6ec-4947-b056-f5c3a500a9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square foot'])[1]/preceding::select[6]</value>
      <webElementGuid>de2fd4df-4cbf-4101-8a56-50ed1f6bf388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square metre'])[1]/preceding::select[6]</value>
      <webElementGuid>902a986a-d323-4c66-b9f6-7e26f8fd3aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>42d13b0e-6651-481f-ad02-5bc51c13f6f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@selected = 'selected' and @id = 'prop_type' and (text() = '
                        Select
                          Flat
                          Detached
                          Semi-detached
                          Terraced
                          Bungalow
                          Studio
                    ' or . = '
                        Select
                          Flat
                          Detached
                          Semi-detached
                          Terraced
                          Bungalow
                          Studio
                    ')]</value>
      <webElementGuid>2ea79ce2-929f-4ffa-8bfe-a02b8a05b11d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
