<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Number of Bathrooms dropdown</name>
   <tag></tag>
   <elementGuidId>3cc6d3d7-fcc0-4fbd-841b-39495699b43d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number_of_bathrooms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='number_of_bathrooms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d04f7ab-af10-4c15-81c9-4b750e048ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>446df266-a92d-4156-9eac-a32fd1fad139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_of_bathrooms</value>
      <webElementGuid>7b4c1a42-c123-4387-a0e0-1b3b1019b297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select optional form-control input-lg</value>
      <webElementGuid>56a1c13b-d3b6-47af-a912-e336e3fb60e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Select
                        1
                        2
                        3
                        4
                        5
                    </value>
      <webElementGuid>6d29bd2c-beb8-44ee-bd91-71e9b9d35bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_of_bathrooms&quot;)</value>
      <webElementGuid>8778c0af-4caa-4576-a31b-5920b3c2c810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='number_of_bathrooms']</value>
      <webElementGuid>026cda66-453b-4e71-b553-17e6f268d37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='number_of_bathrooms_section']/td[2]/select</value>
      <webElementGuid>dbe4bcdb-1741-4274-9add-096c9b8c8bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[3]/following::select[5]</value>
      <webElementGuid>b1352267-7a43-4530-aae9-a76f3c1b3eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='between applicants'])[2]/following::select[5]</value>
      <webElementGuid>67d939db-6811-4f7c-ac4c-053232903937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square foot'])[1]/preceding::select[2]</value>
      <webElementGuid>8d94af54-d0d8-4840-8368-775bd09ae607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square metre'])[1]/preceding::select[2]</value>
      <webElementGuid>c9b15143-aaa0-4bdd-9834-ebb2507343c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/select</value>
      <webElementGuid>42b63118-17c5-4388-a640-bc9cff9a0280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@selected = 'selected' and @id = 'number_of_bathrooms' and (text() = '
                        Select
                        1
                        2
                        3
                        4
                        5
                    ' or . = '
                        Select
                        1
                        2
                        3
                        4
                        5
                    ')]</value>
      <webElementGuid>6e23c262-4597-43b1-9eca-2fc6ce017661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
