<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Listing - Property description textfield</name>
   <tag></tag>
   <elementGuidId>f2c1b879-3287-45b0-8615-e5f114cb399d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#property_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='property_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>94ad0981-e908-4bb4-a7ae-aaeb0179fc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>property_description</value>
      <webElementGuid>b365d619-5f88-470e-829a-9332ae3fa204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec4bc60c-b694-48fc-942d-c420ec709392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>a3311571-6e9a-41fb-ae54-170880ca5d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0d3da8ce-15f0-495f-9b13-5fadabee3d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>property_description</value>
      <webElementGuid>a1fbf975-0a76-497a-a15b-b80ff212e295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your property description...</value>
      <webElementGuid>5640c00a-9158-470d-ad41-7c554b989b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;property_description&quot;)</value>
      <webElementGuid>0e7e3439-f5ef-4587-b771-042d120bfa2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='property_description']</value>
      <webElementGuid>4d6cf6db-1d49-4456-b212-3e0ec7e063f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='property-description']/textarea)[2]</value>
      <webElementGuid>f053429d-569c-4d50-9502-8e95cdecd240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/textarea</value>
      <webElementGuid>481fabbd-272b-4aea-aae3-05716c754704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'property_description' and @type = 'text' and @name = 'property_description' and @placeholder = 'Write your property description...']</value>
      <webElementGuid>6daf3821-5145-4bd5-8fd2-6f75ba18d7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
