<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New Tenancy column-Start bt</name>
   <tag></tag>
   <elementGuidId>1212f876-3092-4c95-9244-dfd53ca0fa5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkstabletable_tenancies > tbody > tr:nth-of-type(2) > td:nth-of-type(6) > p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;addRecordModal2('FOR KATALON ENQUIRIES TEST - 3 Alder Road, STURMINSTER NEWTON, DT10 1AB, UNITED KINGDOM', '15353','false');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81f1d2aa-71b9-46bc-89d4-a0073c8f5c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addRecordModal2('FOR KATALON ENQUIRIES TEST - 3 Alder Road, STURMINSTER NEWTON, DT10 1AB, UNITED KINGDOM', '15353','false');</value>
      <webElementGuid>6d4397e9-3aa4-4cab-bdb7-1c2b890feb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8f9421cc-fc55-4c00-812b-7d608bbdb968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>property_in_tenancy</value>
      <webElementGuid>146aa729-d6cd-4f36-b040-2f667d8a9f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d9415bf4-0a78-4267-b377-8d3f669a54c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>db21b66e-fa7e-4843-af11-4b142b24a129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkstabletable_tenancies&quot;)/tbody[1]/tr[2]/td[6]/p[1]/a[1]</value>
      <webElementGuid>7dcce2b2-b7d0-4037-a76c-c641b59e9fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;addRecordModal2('FOR KATALON ENQUIRIES TEST - 3 Alder Road, STURMINSTER NEWTON, DT10 1AB, UNITED KINGDOM', '15353','false');&quot;]</value>
      <webElementGuid>915ef06f-3e66-4d51-b2aa-df336b5ff5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable_tenancies']/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>3ed0e9ed-2186-4739-8b48-b33ca5cf5654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start')]</value>
      <webElementGuid>4cf4c932-5f2f-4840-8dcb-340c7bb40711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[1]/following::a[1]</value>
      <webElementGuid>1b27516a-9435-4891-929e-da17abc0c007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Listing'])[2]/following::a[2]</value>
      <webElementGuid>ff1676f4-d9f3-4f3b-b378-6933cd9d9837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sydney Hous... EX18 7AB'])[2]/preceding::a[2]</value>
      <webElementGuid>eb0a6e1d-53a6-4aa1-94e8-2e90237cad12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>b5772745-8395-409e-ab9e-2a6bd975740a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[6]/p/a</value>
      <webElementGuid>eb27a030-c83d-4432-ac04-c9cf4fb9bc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>028e9254-d27e-4f22-871d-58d1c8698d81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
