<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Onboarding - Edit end date - Confirm bt</name>
   <tag></tag>
   <elementGuidId>7f1d317c-b782-410f-9609-eba6af93dfc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refundbtnv4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refundbtnv4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8077623b-e7d0-450f-a2d1-c59a0b8639af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5807f221-5983-44d9-aacc-c792b5d330da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1c729a6d-302d-49c6-ad42-256c39b3b6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refundbtnv4</value>
      <webElementGuid>0c77c779-959d-4d45-8a93-dccdaa2471ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn btn-success</value>
      <webElementGuid>f053ed1e-d8fb-46f3-a574-987ac348ccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>ff89d00a-1f40-4b4a-808e-45d5f98be9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refundbtnv4&quot;)</value>
      <webElementGuid>14085740-2b68-48ea-8f94-0033ce851442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refundbtnv4']</value>
      <webElementGuid>8b8863cf-b2c4-462a-b9f5-100b2b372a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='end_tenancy_form']/div/button</value>
      <webElementGuid>cc0344cd-7c52-4664-8d17-8229fd0e9191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a new end date for the tenancy'])[1]/following::button[1]</value>
      <webElementGuid>f6f6a430-7237-4824-b621-48a9852f93cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='END TENANCY'])[1]/following::button[1]</value>
      <webElementGuid>eb32e4fb-734a-404b-817d-8e1ebd014824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to end this tenancy?'])[1]/preceding::button[1]</value>
      <webElementGuid>9a838c4b-1866-49f9-8a91-204d89540297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Tenancy Ending'])[1]/preceding::button[1]</value>
      <webElementGuid>30c2aba8-c41f-4eb9-b033-f1b4aa091bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>d408055e-c6f9-4fdf-909c-81bf7023ddfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>fc7b497a-b0ac-4fc1-a1f7-9d5f11d9fa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'submit' and @id = 'refundbtnv4' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>cc8320b3-864a-4b9b-a646-9a133bc10160</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
