<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Onboarding - Edit end date bt</name>
   <tag></tag>
   <elementGuidId>d8a9a652-6994-4665-98d6-934794db3089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_tenancy_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='end_tenancy_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13b49c6a-3bc4-46b8-8a3b-682e101417b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trigger_popup_fricc4</value>
      <webElementGuid>d3ff36c0-07a1-43d3-8690-ce74e1fe604e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>cancel_tenancy</value>
      <webElementGuid>f03d60a6-ad90-4244-a9b6-cfdac54823a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>1e613ddf-72bd-42bd-b3ed-5ad678cb204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_tenancy_id</value>
      <webElementGuid>e7f6eb51-8dca-4a7d-aa8d-5a40e2baeb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT END DATE</value>
      <webElementGuid>a9faf3f7-0738-49bb-a31b-9924fca4decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requeststab&quot;)/div[@class=&quot;tab-content&quot;]/div[@id=&quot;checkstablecontainer&quot;]/a[@id=&quot;end_tenancy_id&quot;]</value>
      <webElementGuid>4402e333-bedc-4bde-8f34-221e5974b8e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='end_tenancy_id']</value>
      <webElementGuid>65458f10-308c-48ce-8347-145c28fcacf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkstablecontainer']/a</value>
      <webElementGuid>e098c6b8-ddcb-4ed9-ab97-e04d70b6e1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EDIT END DATE')]</value>
      <webElementGuid>4c2957ad-5cd5-455d-8dea-7a31f8650222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit the end date if the tenancy is finishing early or becoming a rolling tenancy.'])[1]/preceding::a[2]</value>
      <webElementGuid>9543a218-390c-43a4-8973-89a729ed685e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editend Da...'])[1]/preceding::a[2]</value>
      <webElementGuid>6ac16704-47d2-4cae-9502-1a809091aa67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDIT END DATE']/parent::*</value>
      <webElementGuid>1aec2220-725e-4fb3-8f39-b8eec0439b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[52]</value>
      <webElementGuid>89a23200-f246-4dd1-85da-ba2c409d5430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>cbb18595-f3c6-4252-940e-7b65022dd693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'end_tenancy_id' and (text() = 'EDIT END DATE' or . = 'EDIT END DATE')]</value>
      <webElementGuid>32784af8-8933-42ba-bff1-2b7213f265c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
