<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Onboarding - Edit end date textfield</name>
   <tag></tag>
   <elementGuidId>0495c4cd-8f9e-41c5-b8af-961ede510004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenancy_override_tenancy_end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tenancy_override_tenancy_end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e502bf0-3154-486b-ae41-86dcf75c5f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enddate datepicker form-control hasDatepicker</value>
      <webElementGuid>061879e2-4559-4751-928d-252cf43b2388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21a802c2-725c-4459-93dd-192a69258f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[override_tenancy_end_date]</value>
      <webElementGuid>988618e2-ed3e-4d08-bab3-2a1426b3a7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenancy_override_tenancy_end_date</value>
      <webElementGuid>7dca46b8-ab09-41e1-9441-8f394dc76484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>04f7372c-09fb-466a-84a4-3d09d8479d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cbp-spmenu-push&quot;]/div[3]/div[@class=&quot;hover_bkgr_fricc4&quot;]/div[1]/form[@id=&quot;end_tenancy_form&quot;]/div[1]/input[@id=&quot;tenancy_override_tenancy_end_date&quot;]</value>
      <webElementGuid>5d2efbc9-b43a-4ff0-88b8-58c73a160449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tenancy_override_tenancy_end_date']</value>
      <webElementGuid>58f727ff-60af-44c1-8e91-cccd023d4f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='end_tenancy_form']/div/input</value>
      <webElementGuid>c2852235-99ea-4eb8-b875-64a0e6405d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>1151cde5-aec0-4a01-ab8d-8e953d235dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tenancy[override_tenancy_end_date]' and @id = 'tenancy_override_tenancy_end_date']</value>
      <webElementGuid>395eb4e9-ec8e-4a9e-b8ce-ffd24c53c6d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
