<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pat Certificate - Expiry date field</name>
   <tag></tag>
   <elementGuidId>632c4a32-9960-42b0-9cd5-ba35e9716146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pat_expiry_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pat_expiry_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14b7b584-291b-4db6-b7ff-8491ad0446d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dfc6d511-0da1-4e74-8e3e-7ca0ec4c87ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pat_expiry_date</value>
      <webElementGuid>3e9c8ac6-be62-4135-9e7f-746d55e95b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input datepicker hasDatepicker</value>
      <webElementGuid>d9b49c8c-92ab-44f9-8071-2465d3d02cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiry date</value>
      <webElementGuid>f1cce0e8-73c1-4d02-8539-be5e028d7c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c66180e-d70b-458f-8c75-a12853bf2206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancy[pat_expiry_date]</value>
      <webElementGuid>5b19a677-d1ba-4ca5-bd71-d7325f88f0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pat_expiry_date&quot;)</value>
      <webElementGuid>9b42b924-845e-4bdd-86cd-7ff50bf8e7e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pat_expiry_date']</value>
      <webElementGuid>1fe3e7ee-7bc1-4c24-a394-87f41211b1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='upload_pat_expiry_form']/input[4]</value>
      <webElementGuid>1fe2de87-7fdb-4abf-a41b-7fe1308f0728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/form/input[4]</value>
      <webElementGuid>8079efd4-f621-4156-bd71-cc95792a94b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pat_expiry_date' and @placeholder = 'Expiry date' and @type = 'text' and @name = 'tenancy[pat_expiry_date]']</value>
      <webElementGuid>bbf507e6-9f5c-4c4d-a8f2-360635cb896d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
