<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Properties-Onboarding - Order by vacant then end date toggle</name>
   <tag></tag>
   <elementGuidId>84c6e89e-88e9-4cc4-876e-bb681b1d186a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#switchorder_vacant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='switchorder_vacant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e6dff54-b3bc-4483-a484-0f4875174a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switchorder_vacant</value>
      <webElementGuid>f25310c6-9e27-442f-83a3-1044dbb89dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>52f3b344-e2a7-45a8-bb78-d36a88a1efcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switchorder_vacant&quot;)</value>
      <webElementGuid>ecf7e88d-9ba1-4541-9c2f-655d843d58e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='switchorder_vacant']</value>
      <webElementGuid>2a6b5ed2-0327-4661-a2a5-2719a88428c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab2']/div/div/label/div</value>
      <webElementGuid>55d0b300-88c7-4c7b-b851-32990bdfb666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>53801434-68ed-4a49-b0ba-046e0fa7c250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'switchorder_vacant']</value>
      <webElementGuid>dcc4d4f0-97dd-4f8b-a49b-da8a14d0b4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
