<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Properties-Onboarding - New tenancies in progress only</name>
   <tag></tag>
   <elementGuidId>eef59330-d85c-4646-b4e5-2515105d9450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#switchtenanciesinprogress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='switchtenanciesinprogress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>293901b3-755e-4b6e-9896-deb07574a363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>switchtenanciesinprogress</value>
      <webElementGuid>242dc826-c098-4fff-ab96-368c323bf574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>c902ab06-7ca4-4475-81b1-efe993810ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;switchtenanciesinprogress&quot;)</value>
      <webElementGuid>5c04201b-a410-428a-ac85-d42581d41141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='switchtenanciesinprogress']</value>
      <webElementGuid>b5eda3ae-5063-4ffe-a640-3277ffc54011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='requeststab2']/div/div/label[2]/div</value>
      <webElementGuid>c250dbed-6a38-4902-9718-5a2f0e2b3bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div</value>
      <webElementGuid>5d6448e6-8820-4124-98db-8defe9d43791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'switchtenanciesinprogress']</value>
      <webElementGuid>e51fce4a-6c78-4c90-a8fa-0d0ba9c55623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
