<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Add referencing bt</name>
   <tag></tag>
   <elementGuidId>3ea98298-9922-4e93-a680-136f8f597418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addreferencingbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addreferencingbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41a970dc-e83c-4caa-abe1-6b993be7b04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>e10ebe0a-e918-466b-9efd-65b9834f0f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addreferencingbtn</value>
      <webElementGuid>f07818fc-b4a0-4cd2-9f29-318e1a830e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleReferencingDiv()</value>
      <webElementGuid>0896ea72-e357-4eb8-80e0-efdf373eeeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add referencing</value>
      <webElementGuid>5387d63e-093f-4db2-9b3a-4bac5c1fc355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addreferencingbtn&quot;)</value>
      <webElementGuid>fd54f65f-4834-40c0-9203-0b85655983e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addreferencingbtn']</value>
      <webElementGuid>eef63b1f-fdbd-458a-9151-12de7e007854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yourcheckstabmenutab']/div/form/div/div/a</value>
      <webElementGuid>71c586c8-b524-480e-9010-f4eff38bb752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add referencing')]</value>
      <webElementGuid>365734d9-d1e6-4c6b-bda5-55353850cf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent Guarantee'])[1]/following::a[4]</value>
      <webElementGuid>2e0d3c0a-0251-4d25-81e5-a81051d1d59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right to Rent'])[1]/following::a[5]</value>
      <webElementGuid>450bfbdf-5a9e-42b1-a97a-6be96395cb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/preceding::a[1]</value>
      <webElementGuid>d92ce593-2d5c-4468-90fe-c56dafbe7c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekly'])[1]/preceding::a[1]</value>
      <webElementGuid>0ff3ac91-5b79-4408-9dbc-dfb2e14b9a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add referencing']/parent::*</value>
      <webElementGuid>50c55e33-1634-4825-b33d-0f38f3b33abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>eb5ae968-4075-4df9-bd7d-91e4212d6c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addreferencingbtn' and (text() = 'Add referencing' or . = 'Add referencing')]</value>
      <webElementGuid>8351148d-430c-4346-9532-ac96d076ccff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
