<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Renter name textfield</name>
   <tag></tag>
   <elementGuidId>3df71695-7f03-4ed7-971d-9fd683eb75a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rentername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rentername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b126ef72-9e6b-428f-a504-693a7f3decdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rentername</value>
      <webElementGuid>159ff341-7330-4363-aed4-ed088744b8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec56c0af-f6f7-4f10-a9c1-c0c09b135364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>55267969-d928-4b8a-a89a-69685a5b3810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Renter name</value>
      <webElementGuid>e12215ca-bf7e-4f77-bf0e-d3e350c74e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>702e9072-9305-43ef-8d0d-246d9e61aa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[rentername]</value>
      <webElementGuid>39aa625b-9326-45fc-b07c-7e1d5a24fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rentername&quot;)</value>
      <webElementGuid>faf9d819-861a-4d07-99d1-f845769ecdc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rentername']</value>
      <webElementGuid>7021dce4-2fa0-4627-98ed-dcab4b18e46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter123container']/div/input[41]</value>
      <webElementGuid>4562b761-06d8-4828-a12e-793f0e8332d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[41]</value>
      <webElementGuid>4e1dc4ed-77ed-4994-850e-d3a25d0b22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rentername' and @placeholder = 'Renter name' and @type = 'text' and @name = 'invite[rentername]']</value>
      <webElementGuid>2a946b9d-6be0-401c-af06-746301576674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
