<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Renter Email textfield</name>
   <tag></tag>
   <elementGuidId>70ae55d9-d892-4a25-a42b-077fce155ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renteremail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renteremail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37a55d9f-f150-41da-95ba-93702f679783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renteremail</value>
      <webElementGuid>b16722d1-2f66-4840-b4ca-20388c450bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1ab1ae49-f530-4efa-bd39-1d457dae662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>e393b358-56d1-46ce-8319-5f747ea51355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Renter email</value>
      <webElementGuid>c0ac76ea-371a-499e-8d40-765e7ba84da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>228d32a7-c302-4a43-a36d-a0e72d63f69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[renteremail]</value>
      <webElementGuid>aac20282-42d5-4b67-ba41-6c5dae06a8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renteremail&quot;)</value>
      <webElementGuid>3f7d5d1d-e3db-4f87-be49-ed10f8ed8006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renteremail']</value>
      <webElementGuid>f3d7c7dc-328b-48e5-893e-3409e8448ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter123container']/div/input[42]</value>
      <webElementGuid>f39ebc33-af3d-4815-9939-7185e552ccc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[42]</value>
      <webElementGuid>001ee219-717d-4806-8315-c0ed38228025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renteremail' and @placeholder = 'Renter email' and @type = 'text' and @name = 'invite[renteremail]']</value>
      <webElementGuid>5c5f6225-e9f2-4f96-bfb1-8aec0aea175c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
