<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor exiting renter - Gua Name</name>
   <tag></tag>
   <elementGuidId>8eb4627e-6584-4133-ba4d-c4f68bd3befb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renterfirstname2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renterfirstname2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c434c603-6704-4f28-84f1-b26fa78ca5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renterfirstname2</value>
      <webElementGuid>92953c72-7852-4d43-acd3-120825a5b354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3fd6b4dd-49a8-4c8a-88c8-e77df5a40e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>180e0b79-a240-4d1e-8618-209cae21622d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor name*</value>
      <webElementGuid>010fedcd-1c4a-4b5b-ba1d-176d577ee3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8f71b0b-dfdf-42d0-955f-843f4057b90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[rentername]</value>
      <webElementGuid>0e730f1a-340d-4801-8fa6-193a339c26b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renterfirstname2&quot;)</value>
      <webElementGuid>0d1aa785-6d56-4ff7-94b0-c3640eeab6c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renterfirstname2']</value>
      <webElementGuid>c9295b0a-a261-4f56-9a91-cdd505dc2efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/input[12]</value>
      <webElementGuid>ba7b8bb9-1c54-4ef5-a9c4-c00bba0603e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[12]</value>
      <webElementGuid>b364ab24-debd-4ed5-a6fc-d5231a792b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renterfirstname2' and @placeholder = 'Guarantor name*' and @type = 'text' and @name = 'invite[rentername]']</value>
      <webElementGuid>7496078d-e462-4fad-9811-134c16af58c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
