<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Submit Request bt</name>
   <tag></tag>
   <elementGuidId>fa6580e2-5a55-4c5f-b254-5893109db120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invitecheckvalidmobilenew1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='invitecheckvalidmobilenew1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>410ba78a-1ff5-4bf5-b1ca-8a93697a26ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitecheckvalidmobilenew1</value>
      <webElementGuid>c4dd85d0-d32a-46cd-a79f-0c8dd01ca3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>acd69c28-540e-4a96-b925-295c6aa9b819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Request(s)</value>
      <webElementGuid>c9003c89-397c-4b3e-a1f9-c32f50285aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitecheckvalidmobilenew1&quot;)</value>
      <webElementGuid>911a7d28-180f-417a-b80f-ab63bbf02e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='invitecheckvalidmobilenew1']</value>
      <webElementGuid>7ba4f4b4-e026-4b1e-b6a5-de256115a8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div[6]/div</value>
      <webElementGuid>832f3a60-1551-4e09-ae91-3942fcf7c7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter a move in date'])[1]/following::div[2]</value>
      <webElementGuid>b27e86b1-5b84-4c96-be5d-f623778f9ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move in date'])[1]/following::div[3]</value>
      <webElementGuid>4a821f0c-b3fd-4199-96c6-a5ec4a8b6618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Combined'])[1]/preceding::div[2]</value>
      <webElementGuid>8338f04e-4217-4f88-810a-a536d666a70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/preceding::div[2]</value>
      <webElementGuid>18633d91-f76e-4745-b380-6e2fad127147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Request(s)']/parent::*</value>
      <webElementGuid>fa4995a1-ae78-4651-8224-c71f1b9ac4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>98dda575-5a1b-4f32-87c8-28f2fc8e3ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'invitecheckvalidmobilenew1' and (text() = 'Submit Request(s)' or . = 'Submit Request(s)')]</value>
      <webElementGuid>c271d8b7-8ed1-4bfc-bba1-3b883a6bbddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
