<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Company name</name>
   <tag></tag>
   <elementGuidId>61466445-cfab-4cc0-a946-23e9a4a835a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renterfirstname3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renterfirstname3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe2437e-fcc3-4f31-a5ed-aa5c7619e03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renterfirstname3</value>
      <webElementGuid>3d1f313c-00e1-4210-bb1d-ed924b943574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>409a409a-f0bc-494e-ae71-bf2ae1c17534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>4cd72e1b-ca84-436e-9a0e-e1abd970d94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company name*</value>
      <webElementGuid>c0a4dd48-0ff3-4877-b94c-77598817f987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1dbd2f6f-3e67-4839-8408-d100362f4b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[rentername]</value>
      <webElementGuid>9a20e34a-e74b-4971-a886-ece99784856e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renterfirstname3&quot;)</value>
      <webElementGuid>ba37c1bc-31d2-4d8f-a782-56aefde08f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renterfirstname3']</value>
      <webElementGuid>d701720e-590b-4016-b0de-b8e268d8f281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='new_invite']/div/input)[5]</value>
      <webElementGuid>f3e73f20-f941-4fe6-9c5b-ccbc8d6704a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/form/div/input</value>
      <webElementGuid>f25a65c2-fb80-4497-a11b-1e60b53e93fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renterfirstname3' and @placeholder = 'Company name*' and @type = 'text' and @name = 'invite[rentername]']</value>
      <webElementGuid>1134e1fe-6b02-429e-8230-e846181623aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
