<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Contact name</name>
   <tag></tag>
   <elementGuidId>e2a0ebe5-6720-43bb-ba59-0a029c74d835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companyfor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyfor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>348b244f-a027-461e-a459-f0127cec7568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyfor</value>
      <webElementGuid>97c7b481-fba4-4ea9-9d06-3450906ffaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9229651c-daa3-4968-96e1-06bf5d12922f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>b98c78c4-6fb5-4740-9ff7-bf69c5ea1b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact name*</value>
      <webElementGuid>64301f44-de59-4b2c-8f93-e6350faa041c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35c41758-b58b-4a0a-a2ad-db1bc5c3ce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[company_for]</value>
      <webElementGuid>0c1ff2f6-1408-4e6f-9b3a-8e0814268929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyfor&quot;)</value>
      <webElementGuid>515b9493-69c1-437f-9ff4-9e6a921da0f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyfor']</value>
      <webElementGuid>0812159b-075c-4198-95ca-a3a0cabf9cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div/input[5]</value>
      <webElementGuid>01d922e8-27cd-4d28-9201-2a2aa8b97f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[5]</value>
      <webElementGuid>8106760f-ee3a-433e-a93a-f31680e12924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'companyfor' and @placeholder = 'Contact name*' and @type = 'text' and @name = 'invite[company_for]']</value>
      <webElementGuid>54a5c361-933a-4ba2-8b27-a1dd73748b92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
