<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Contact email</name>
   <tag></tag>
   <elementGuidId>69f7f87e-2f26-4c45-a10f-c88fe9909ac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renteremail3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renteremail3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ac2e00-4eb4-4ad8-a3b4-ceed065c27f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renteremail3</value>
      <webElementGuid>8e449d1c-1bc9-44a7-8a3c-42752f340d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ade641ba-1f39-4c02-8f8e-86b91790bd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>1a8f7917-d5d7-4739-bf41-a1eb20cabb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact email*</value>
      <webElementGuid>8da8e91e-6f76-4ab3-82f9-70e49fc71d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47bbe986-7304-493a-a899-c160bff4cd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[renteremail]</value>
      <webElementGuid>d0f94519-7a01-4c6d-8e06-f25acd35c0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renteremail3&quot;)</value>
      <webElementGuid>eb98de17-54a4-4c24-a399-f0a209a9172c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renteremail3']</value>
      <webElementGuid>68085cda-a9c3-4439-b074-41d060509a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div/input[6]</value>
      <webElementGuid>27b2d442-7298-4ed7-aeed-922feee431a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[6]</value>
      <webElementGuid>e2b0f710-30e9-4d46-8027-ba5b3905afb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renteremail3' and @placeholder = 'Contact email*' and @type = 'text' and @name = 'invite[renteremail]']</value>
      <webElementGuid>f57444d6-d620-4f3f-97ff-02d63e44cce1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
