<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor switch</name>
   <tag></tag>
   <elementGuidId>6241171e-de3b-4456-b35c-1af4375c9d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='guarantorornotswitch1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guarantorornotswitch1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9863cde-7b08-4a2a-9d00-abd3fe241c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>e3871793-50de-46d3-89b1-7269da74d54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guarantorornotswitch1</value>
      <webElementGuid>66466e1e-58db-468d-86d8-ec3b234ea445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guarantorornotswitch1&quot;)</value>
      <webElementGuid>a5869947-e02a-4fb3-a3f4-09350751ffd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='guarantorornotswitch1']</value>
      <webElementGuid>f0dce8b1-a303-4aed-a7f3-90913adc9e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter123container']/div/label/div</value>
      <webElementGuid>41cc15e4-1326-4172-bf5a-ceac67e54251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>6f4a17c7-8bed-482c-8720-62b6f5bb31b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'guarantorornotswitch1']</value>
      <webElementGuid>08e00854-cd7f-4dfe-a604-fe9bcaae8bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
