<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Rent value textfield</name>
   <tag></tag>
   <elementGuidId>cf244388-4801-4984-a85c-251c552477c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rentdone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rentdone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17f97812-9ee6-4e5d-9ff7-ea9c33a99544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rentdone</value>
      <webElementGuid>e421e31b-eeb0-461f-b556-47eae780085d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1da72b77-bb21-4669-a372-7b5507e399b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>57871aed-04ec-40c5-a9ca-54d023712d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rent £ (total)</value>
      <webElementGuid>73c8d178-9e28-4583-b8c0-cb6a347fa77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eec73d10-59d4-4929-b065-6bc4ca980a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[total_combined_rent]</value>
      <webElementGuid>865f7173-ff00-4308-837f-05d806aab7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rentdone&quot;)</value>
      <webElementGuid>e7a4dc48-d330-4f5f-917f-900a0efce74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rentdone']</value>
      <webElementGuid>68ac6ada-2fd7-4fef-ae56-03f60605ee65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div/div[2]/div/input</value>
      <webElementGuid>280cdfe8-f650-4c9a-ab7c-37cc7ad60d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/input</value>
      <webElementGuid>f1dc53d8-0254-4063-a07b-ea58841f1aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rentdone' and @placeholder = 'Rent £ (total)' and @type = 'text' and @name = 'invite[total_combined_rent]']</value>
      <webElementGuid>75d51b76-693b-4f93-94eb-d39ff8c2c609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
