<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor - Submit Request bt</name>
   <tag></tag>
   <elementGuidId>4f8f83a5-f0d7-4749-824c-2b1868bd2c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invitecheckvalidmobilenew2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='invitecheckvalidmobilenew2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22fea52e-e11f-428d-a373-62c38b7f732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitecheckvalidmobilenew2</value>
      <webElementGuid>be33fd37-4063-45a1-a1d5-bf6183a4f410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>124a148b-e2aa-47ee-a90e-720a0e2bb8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit
                       Request
                     </value>
      <webElementGuid>f6c7dd75-b388-4a74-8775-f881dacb2f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitecheckvalidmobilenew2&quot;)</value>
      <webElementGuid>e7db06f0-e6b4-44df-8343-72d823ff492b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='invitecheckvalidmobilenew2']</value>
      <webElementGuid>5db2dcae-8eaf-437d-af25-3b8d884f1d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div[13]</value>
      <webElementGuid>a8b4b5b4-7e47-41d4-8007-031de0a81986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[3]/following::div[1]</value>
      <webElementGuid>2e8dc273-07ad-49ac-ba00-5d5be3434e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[2]/following::div[1]</value>
      <webElementGuid>d5b7832a-6ac1-4f65-a2c3-6c9788ec181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Request'])[2]/preceding::div[8]</value>
      <webElementGuid>06fb6cd8-4fa1-497c-ae84-9429257018ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[4]/preceding::div[9]</value>
      <webElementGuid>7f744238-89a5-4144-a1c9-e6e130279645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]</value>
      <webElementGuid>0c423850-ba88-494e-93c6-53ff7f3755ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'invitecheckvalidmobilenew2' and (text() = 'Submit
                       Request
                     ' or . = 'Submit
                       Request
                     ')]</value>
      <webElementGuid>1043ab0d-9f28-48fe-b5c9-47c06d91ce3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
