<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor for existing renter</name>
   <tag></tag>
   <elementGuidId>8f43ab47-f45a-4d35-8c97-438a50b603ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showtabforexistingrenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='showtabforexistingrenter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fbd63566-e817-440d-a6bd-fd792f137f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showtabforexistingrenter</value>
      <webElementGuid>bec18ff3-49eb-4ffb-8dd1-8c13a23a1b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#guarantorforexistingrenter</value>
      <webElementGuid>53f21d04-7e76-43da-a68b-af75bef126f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>guarantorforexistingrenter</value>
      <webElementGuid>28ef97ac-b617-4553-8ca8-4e6f112d9b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>82181df2-915b-4c49-b9ad-d3917bdc520b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>4e0e158e-907d-459f-9e1b-83d43d2f56c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guarantor
                                for existing renter</value>
      <webElementGuid>92fef229-76b5-4cec-8473-beceeaee814b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showtabforexistingrenter&quot;)</value>
      <webElementGuid>ae093a1b-3b9e-4a97-88b0-9097bc5c8b6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='showtabforexistingrenter']</value>
      <webElementGuid>ff427573-c929-4005-9773-df2f84845d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='individualstab']/ul/li[2]/a</value>
      <webElementGuid>4977cc16-5fc4-4beb-b893-cb7ffd24f355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Guarantor
                                for existing renter')]</value>
      <webElementGuid>d5107db7-4f9e-455d-9f3f-b16cb4fed37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renters'])[2]/following::a[1]</value>
      <webElementGuid>38618d5c-1b64-434a-ab58-54aa71479976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/ul/li[2]/a</value>
      <webElementGuid>4ae6fe7a-3736-4fec-9413-d9bf382c2110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'showtabforexistingrenter' and (text() = 'Guarantor
                                for existing renter' or . = 'Guarantor
                                for existing renter')]</value>
      <webElementGuid>6337475f-49fb-41c0-ad0a-9c5749d54db5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
