<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor for email</name>
   <tag></tag>
   <elementGuidId>d2ab0a51-1608-40e4-ab77-806d4be1d8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renteremail2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renteremail2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b6b64ec-ca82-4997-9f63-9011137195a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renteremail2</value>
      <webElementGuid>0e4611b0-7950-4823-bba2-974d4f2ac4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>37834df1-357c-4541-be35-425f05b5092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>f394ba26-eb39-4b77-91de-1a627e1b1093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor email</value>
      <webElementGuid>00d77758-d3f1-4acc-bfdc-7084e39f4117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>533e14b4-1486-46b6-9b3b-ab87bdf0569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[renteremail]</value>
      <webElementGuid>fb9f73e7-8577-4de3-8c69-1fa00c4f6eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renteremail2&quot;)</value>
      <webElementGuid>ddd56cac-fe35-46c4-9f55-11718aa5739f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renteremail2']</value>
      <webElementGuid>1971c4d7-686d-491b-b6f0-479e3eeb0f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/input[14]</value>
      <webElementGuid>f5f376fe-5011-47ed-bf3d-4902935c6be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[14]</value>
      <webElementGuid>a9c3ce4e-fd13-42f6-80fa-4c52f6dca6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renteremail2' and @placeholder = 'Guarantor email' and @type = 'text' and @name = 'invite[renteremail]']</value>
      <webElementGuid>c80a6737-4f79-4cd5-ac4f-e78829526d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
