<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Company as Tenant - Submit Request bt</name>
   <tag></tag>
   <elementGuidId>f16ef93e-3c06-45fc-af95-929341badded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#invitecheckvalidmobilenew3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='invitecheckvalidmobilenew3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d137cdee-8d44-4b37-811a-8fc9503caa24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitecheckvalidmobilenew3</value>
      <webElementGuid>6960c096-c67a-4a89-a0a1-145920581094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>5831e32e-ed5b-470f-a7d3-eeeadbc562dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Request</value>
      <webElementGuid>19b3d7ea-e233-4020-9ee6-1ad016826f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitecheckvalidmobilenew3&quot;)</value>
      <webElementGuid>bd1bcdef-ef00-4be5-ba01-ed28399593bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='invitecheckvalidmobilenew3']</value>
      <webElementGuid>bc8a21c0-1d0c-4db6-b8da-8634f65b8a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/div/div[8]</value>
      <webElementGuid>0434a572-be55-4cb6-a9c4-68ff901f9c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[3]/following::div[11]</value>
      <webElementGuid>1e61ef48-1f0b-4d89-8548-84258ca0a9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[4]/preceding::div[1]</value>
      <webElementGuid>6e313a7e-3bcb-4c50-8156-eb513fe09a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[8]</value>
      <webElementGuid>1153f042-c713-4d7c-9433-b1b123adc554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'invitecheckvalidmobilenew3' and (text() = 'Submit Request' or . = 'Submit Request')]</value>
      <webElementGuid>546503cb-d6ad-4ef9-a411-7b32669cfc76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
