<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing tab - Guarantor email field</name>
   <tag></tag>
   <elementGuidId>3557fa96-1b59-4466-ab3b-07ea5758be31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='invite_guarantoremail_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invite_guarantoremail_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b93d3d-5a74-4ea0-8075-095288ef8765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1002abc0-e789-4ae8-ae78-6514f670cf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>a093930d-7148-4196-9b13-ee0b6c10a792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Guarantor email</value>
      <webElementGuid>829c0223-6357-49f6-a12e-8d753fdaf38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26dc5506-1204-4686-9c83-86cee689923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[guarantoremail_1]</value>
      <webElementGuid>f53ea03c-f3bc-41bf-9884-c48371f0aa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invite_guarantoremail_1</value>
      <webElementGuid>f1e1d732-ff88-4167-80df-48fb99f6f029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite_guarantoremail_1&quot;)</value>
      <webElementGuid>8a15e270-b458-4c7b-baf1-b5371f0b4c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='invite_guarantoremail_1']</value>
      <webElementGuid>15d27466-ab32-4b7e-9368-60fe6b852f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guarantordiv1']/div/input[3]</value>
      <webElementGuid>89ca7275-940d-4c1b-8bc1-e3c2351f1ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input[3]</value>
      <webElementGuid>3b46b409-068d-4c8d-80ee-522ff29b31bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Guarantor email' and @type = 'text' and @name = 'invite[guarantoremail_1]' and @id = 'invite_guarantoremail_1']</value>
      <webElementGuid>683e87e4-67e1-4fee-a184-d0248bf7f8dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
