<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rent Guarantee - Search bar</name>
   <tag></tag>
   <elementGuidId>8e73f1c4-71af-4776-8444-85887b808149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_rtrs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_rtrs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bd0c1bb-9823-4cd3-9ca2-a8fca753138a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6172ce2d-2c90-47e4-b2a0-997e069a9204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>0af93675-5d04-4761-9120-160ff3361ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>b769c985-c8ed-4e03-bbfd-3b4bba7971f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>21c57fff-4637-4ad4-9d9b-1c9838ea5151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by address or policy number</value>
      <webElementGuid>2b952ee6-19d4-4be5-9575-acaece9a71d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_rtrs&quot;)</value>
      <webElementGuid>f4dad542-a16e-4b42-9758-34bf5e68d917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_rtrs']</value>
      <webElementGuid>b468a76b-2a94-4d1f-8ee6-7458156f7849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form/input[2]</value>
      <webElementGuid>af08c381-bf58-4ace-bd54-b194f011df42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>bd237b33-351f-4430-b76b-0ea78a536016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_rtrs' and @id = 'search_rtrs' and @placeholder = 'Search by address or policy number']</value>
      <webElementGuid>53473700-0009-4a07-ba89-84499e3b1616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
