<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rent Guarantee - Policy Wording - Landlord Legal Expenses txt</name>
   <tag></tag>
   <elementGuidId>315db442-fe0e-4ef1-8df2-68eceee11a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='checkstabletable_right_to_rent']/tbody/tr[2]/td[3]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1eae6717-0d6c-4a79-98a8-163baaddb814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b0bc2166-f67e-45f7-bb8c-6f2fb61ba2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf</value>
      <webElementGuid>ef806bf3-4946-4091-9e65-6e3736dc43c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>policy_wording</value>
      <webElementGuid>49f6d7fb-6b5b-4939-a4ce-6f20929515b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>351b6114-2f84-42be-9814-8f5d44eb5451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy Wording</value>
      <webElementGuid>0f1858f8-c57a-48bd-b98f-1cadafff3cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkstabletable_right_to_rent&quot;)/tbody[1]/tr[2]/td[3]/p[1]/a[1]</value>
      <webElementGuid>580670ae-3da0-4cc6-843a-d7377bdc5e2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable_right_to_rent']/tbody/tr[2]/td[3]/p/a</value>
      <webElementGuid>ceb660fd-b3a2-4f2a-86a6-3d94c8d1b833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Policy Wording')])[3]</value>
      <webElementGuid>022d2f42-54a2-407e-b978-11c65779ed1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mission Cottage, ... NN7 4AY'])[1]/following::a[1]</value>
      <webElementGuid>93ae6bb5-1ed7-4529-8940-f80896927e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[1]/preceding::a[1]</value>
      <webElementGuid>f39e9f04-b84d-4212-9f56-cedc5c556411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Information'])[3]/preceding::a[2]</value>
      <webElementGuid>35c8bd8a-dc8d-469a-8f75-1fa9d3f237de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf')]</value>
      <webElementGuid>b1e060e9-c54c-4ea3-9be6-29190761c174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p/a</value>
      <webElementGuid>332e9090-e6ff-444b-b85f-c661377c4493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf' and (text() = 'Policy Wording' or . = 'Policy Wording')]</value>
      <webElementGuid>360fff71-0102-47bb-a49c-5bf4dc55e783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
