<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Rent Guarantee - Policy wording</name>
   <tag></tag>
   <elementGuidId>fdaf7166-a6e4-41ce-8faa-73d20615e90a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='checkstabletable_right_to_rent']/tbody/tr[2]/td[3]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58c3e5fc-4e63-4073-a143-6a7bc780a5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>7db86260-0353-4f22-9779-c98131b136c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf</value>
      <webElementGuid>d33f2286-dace-4e35-b710-9f99fa2c90e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>policy_wording</value>
      <webElementGuid>cb445b73-3c53-4c3a-afeb-904bdf3b271f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>62c51364-d116-43f1-b7b6-ebef9ee65fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy Wording</value>
      <webElementGuid>5f217256-71c4-49ac-a7f9-573ea057069d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkstabletable_right_to_rent&quot;)/tbody[1]/tr[2]/td[3]/p[1]/a[1]</value>
      <webElementGuid>14cd8afb-76d8-4357-806b-4fa81b554d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='checkstabletable_right_to_rent']/tbody/tr[2]/td[3]/p/a</value>
      <webElementGuid>5354e02a-abc7-4106-af8c-f6e40e227334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Policy Wording')])[3]</value>
      <webElementGuid>ccc53a1a-0b60-4d43-92d3-3d459d3352e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mission Cottage, ... NN7 4AY'])[1]/following::a[1]</value>
      <webElementGuid>f071cfb7-64e9-4bce-8abb-e3ea9ad10f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[1]/preceding::a[1]</value>
      <webElementGuid>203b71cc-8cb2-4f61-81f3-84c69b81ee2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Information'])[3]/preceding::a[2]</value>
      <webElementGuid>d65e6f82-5f06-4aea-93fe-32af0f806537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf')]</value>
      <webElementGuid>2d0dbfb0-bbc1-4d4f-920f-1fb9ba622228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/p/a</value>
      <webElementGuid>810878d8-7df6-4284-b77e-9448b234e978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://rentprofile-media.s3.eu-west-1.amazonaws.com/landlord-legal-expenses-and-rent-protection.pdf' and (text() = 'Policy Wording' or . = 'Policy Wording')]</value>
      <webElementGuid>bde0610a-305c-4ba1-9fcf-d9169021a6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
