<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Residential Enquiries - To date (June 30 2025)</name>
   <tag></tag>
   <elementGuidId>863ae149-3235-4ce4-b198-f956f8bc9ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ui-datepicker-current-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr[5]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b5ca39cd-c832-4e99-99d6-6fd13b5988e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>  ui-datepicker-current-day</value>
      <webElementGuid>71fe5655-60ba-4753-bad1-aaee0e283fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-handler</name>
      <type>Main</type>
      <value>selectDay</value>
      <webElementGuid>0fff2386-19c6-4e22-ac3d-1bef7024e009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>612890fd-748f-44bb-9545-be40a141c2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-month</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d6ca7341-a1f4-4819-961f-e8277d6b1b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-year</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>074cc334-8229-4ee7-bc89-e9be042dc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8e81dfcf-7d72-4857-8e6c-ad6d73add84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/table[@class=&quot;ui-datepicker-calendar&quot;]/tbody[1]/tr[5]/td[@class=&quot;ui-datepicker-current-day&quot;]</value>
      <webElementGuid>b94bf69a-a4ad-4b9d-b7ef-b3d6935c742f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr[5]/td[2]</value>
      <webElementGuid>00f4be12-c1d5-4517-b415-396ffe878daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::td[30]</value>
      <webElementGuid>ef5a8d90-aa26-40b1-aac1-beb414cdbb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::td[30]</value>
      <webElementGuid>ca203e10-c129-4333-9438-ca0a18b2e05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::td[6]</value>
      <webElementGuid>9f537040-0146-4bb5-9882-197ea858abdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::td[6]</value>
      <webElementGuid>45045886-6e58-47b0-88ff-de17d6c1e9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr[5]/td[2]</value>
      <webElementGuid>bb15dc09-472d-449d-8a73-94f49ddc0f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '30' or . = '30')]</value>
      <webElementGuid>adb13247-d1c2-44aa-9008-144c5e528860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
