<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Residential enquiries - To Select date range</name>
   <tag></tag>
   <elementGuidId>5bc4af4e-ca91-4060-81d5-2fee816d82ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-to-enquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-to-enquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff0d4bcd-f694-4342-a714-f538a8f7a76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-to-enquiry</value>
      <webElementGuid>4447847c-08ca-4b45-9186-795faab0e0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e78c6aba-84b3-4a93-8bc0-8ff82ae5235f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>5cbae064-0d79-4961-b644-3e80cb79bce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9977ed3a-c132-4c52-8675-3fbd6b37f2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker form-control input hasDatepicker</value>
      <webElementGuid>9f0bebef-180e-41fc-b665-f5b4fb0e6e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-to-enquiry&quot;)</value>
      <webElementGuid>611f7edc-ac48-40d3-aec8-be3edf70958c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-to-enquiry']</value>
      <webElementGuid>7c9199f7-4a40-46f5-bf67-763d845b566f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-custom-range']/div[2]/input</value>
      <webElementGuid>94f7896e-cf07-4dac-a69e-b92150f93fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a2ae263f-8727-4868-94d6-fd4a945246ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-to-enquiry' and @type = 'text' and @placeholder = 'Select']</value>
      <webElementGuid>66ac6468-d4e9-4b83-9311-529840f19372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
