<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Residential enquiries - Search bar</name>
   <tag></tag>
   <elementGuidId>167c8867-90b9-4359-b16c-ccbb047cc92f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_enquiries']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_enquiries</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5eca317f-9f74-4044-9a73-8967a6bd9df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>687888d5-f3f4-462e-b198-c52d851c0ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_enquiries</value>
      <webElementGuid>93803a65-c917-4583-a8f5-db9511e57b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_enquiries</value>
      <webElementGuid>05f6973a-c36f-4d47-8f24-370e8bd9c6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>aef0fc5a-7749-46c8-8080-1c6d1197dbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by address or applicant name</value>
      <webElementGuid>f08fc35a-1791-4326-b881-6c95b27773c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_enquiries&quot;)</value>
      <webElementGuid>f091c18b-e156-439e-8475-0bdc0a705aab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_enquiries']</value>
      <webElementGuid>79cdf14e-6562-4b5e-bc34-a44297a7f017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-enquiries-form']/input[4]</value>
      <webElementGuid>ae7f4cd4-47b5-4b7f-9466-e0557d3135ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>31169edb-fbc3-46d0-a8bc-a34c6aa9e89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_enquiries' and @id = 'search_enquiries' and @placeholder = 'Search by address or applicant name']</value>
      <webElementGuid>094b074d-4822-45fe-a81a-4fe7ce4e6622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
