<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Residential enquiries - From Select date range</name>
   <tag></tag>
   <elementGuidId>dafbad58-e611-426a-b6e9-01e1980e8afd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter-from-enquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter-from-enquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf3eb2c8-a1b8-46af-825b-961192601f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter-from-enquiry</value>
      <webElementGuid>97c3ce06-4f3b-4d6f-9ab7-e2c80cc5b18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0fd29b2-4aa9-45d2-8f26-9e203eb27e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>5a43e789-a11b-4d16-b351-edc5f902e816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e8469b3-661e-4e8f-bac1-8658bb74b9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker form-control input hasDatepicker</value>
      <webElementGuid>c9d76809-4878-45db-9027-0843d345b4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-from-enquiry&quot;)</value>
      <webElementGuid>e100b461-6f32-4fdd-9bc2-c885afb37581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter-from-enquiry']</value>
      <webElementGuid>ae6755ce-aac6-4b33-a647-eefb53f6d18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-custom-range']/div/input</value>
      <webElementGuid>291d2f3b-3b33-4c84-8458-82622925cf1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>18ae27e2-70f5-42cf-bbad-c181bd0a5315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'filter-from-enquiry' and @type = 'text' and @placeholder = 'Select']</value>
      <webElementGuid>b13b58e4-8f54-4538-8623-e42d2a5fe57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
