<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Right to Rent - Show all radio bt</name>
   <tag></tag>
   <elementGuidId>b273a12e-5fde-45e0-98d9-48b25a66e5f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show_all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show_all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aaf2766-4bd8-4f21-9233-6d9c938bb8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e43f4960-4e6b-432b-abb6-03c43b163927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show_all</value>
      <webElementGuid>1fdba034-a4cd-42a2-9af4-e5baaa16d416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>r2r_filter_method</value>
      <webElementGuid>100fb0ac-6111-4213-af30-b63c5805cfd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>show_all</value>
      <webElementGuid>bc410e0b-d647-43a1-b6ec-40a05116f19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='/agent/right_to_rent/show_all';</value>
      <webElementGuid>88ff3716-295d-467f-8832-a30978420dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_all&quot;)</value>
      <webElementGuid>f41aadb9-ffdf-47cd-a506-54b415ae0c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show_all']</value>
      <webElementGuid>d58536a1-6e37-4820-81db-d65dc4fcee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form[2]/div/label/input</value>
      <webElementGuid>4d1bdc1a-bf3d-4bcb-832f-cddfe3dbcfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>087b403b-f3c3-43c2-8507-53ca6404ee2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'show_all' and @name = 'r2r_filter_method']</value>
      <webElementGuid>485c8dfe-24c4-4f6a-bda2-b328038ac133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
