<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Right to Rent - Search bar</name>
   <tag></tag>
   <elementGuidId>5b17cac5-42f3-49c2-92c8-a81b8a6b9f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_rtrs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_rtrs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a7bb715-ef1d-4866-82a3-4bbd06a37955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b043b62c-03cd-4082-b572-6edf6bb56ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>bc9e944d-f4fc-4023-986c-3dd47235e767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>897c3ce0-3d5b-41cd-9cf7-dc066aeef7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>71ed7420-6098-402f-8320-45a6b4cbfde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by name, rental address, or ref</value>
      <webElementGuid>c22fa35a-f78c-4ffd-a79b-f1085d0ca401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_rtrs&quot;)</value>
      <webElementGuid>def71a58-080a-40eb-a44b-7df0b704c16f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_rtrs']</value>
      <webElementGuid>093a178b-a575-49fc-a845-898eae0b9cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form/input[2]</value>
      <webElementGuid>15431464-71a5-4767-8398-addb52892d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>00f22c0e-8fe1-413f-b74e-5e09cc95a561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_rtrs' and @id = 'search_rtrs' and @placeholder = 'Search by name, rental address, or ref']</value>
      <webElementGuid>2c6672e0-7a98-48ff-b4a8-6a789f4ca040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
