<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Right to Rent - Cancel (x) bt</name>
   <tag></tag>
   <elementGuidId>850f35a5-2865-45bb-9850-8d718e4a0a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.string.optional.cancelhover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='✕']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15593ce7-d46b-4bf6-8631-aacaf06c4bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>41e086c8-08d3-49af-81fc-e448edc14197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional cancelhover</value>
      <webElementGuid>69063357-6f74-46b5-83cb-ca34ee7a7eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3ff4ca3-8cd8-4f8f-a754-802fb529c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79621aa8-259e-4a28-b76d-d6e451b6a072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetsearch_rtrs&quot;)/a[1]/input[@class=&quot;string optional cancelhover&quot;]</value>
      <webElementGuid>82480c00-ba1d-485e-a864-7d02b7b09c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='✕']</value>
      <webElementGuid>8e04380c-f145-449a-8c94-bab63fbf9039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='resetsearch_rtrs']/a/input</value>
      <webElementGuid>cec1b4d4-92af-4270-b7e1-8b314ffc8887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/input</value>
      <webElementGuid>3f848a4d-9c97-4a03-894a-50b5781c214c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7bc45df8-c912-4eaf-a225-bf4dacda06fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
