<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void from textfield</name>
   <tag></tag>
   <elementGuidId>4eaffa6e-585b-4ff4-9204-26b84186f843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='move_in_date_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#move_in_date_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8818220b-ed87-47eb-bb9d-5ed59ca088ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c63df3cd-2ae8-495f-a961-acf22c1b94d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>move_in_date_field</value>
      <webElementGuid>8cd55a42-ac6c-43e5-84a4-684b74b9168e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>move_in_date</value>
      <webElementGuid>d9c47209-c209-46e1-8f23-ab5c92e6d8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control  input-lg</value>
      <webElementGuid>29a47bda-4578-43a0-9100-cde25697b666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>show_hide_button()</value>
      <webElementGuid>c0135d90-481d-4f40-bd1a-d06c86610b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;move_in_date_field&quot;)</value>
      <webElementGuid>f0309891-a64d-4f73-88f7-349df95dca0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='move_in_date_field']</value>
      <webElementGuid>06a7ab62-0f6f-4890-b6cb-4b7ce2e1540c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='void_period_form_select_next']/div/div/input</value>
      <webElementGuid>f29ade88-9ea8-44c3-968b-4288ea740c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div/div/input</value>
      <webElementGuid>e16471b9-f25b-4959-9d06-bb359beab663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'move_in_date_field' and @name = 'move_in_date']</value>
      <webElementGuid>c5e074df-4f68-4bce-8166-5e9b85577cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
