<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void - Water reading</name>
   <tag></tag>
   <elementGuidId>23b80470-3ea4-4346-95a7-2b10f839a779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='water_meter_reading_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#water_meter_reading_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2113dbe7-ff69-4a45-b472-bbff04e64535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>water_meter_reading_field</value>
      <webElementGuid>c6310024-c06d-4fd1-9d8d-b9ab5a306a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44fefe47-3b65-4fca-9cb8-d4ba80194264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>9b26b553-2276-45e0-b5ce-479cd1cd83dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Meter reading (recommended)</value>
      <webElementGuid>4449ef1f-5c1a-46b7-8f58-a24fe580c63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2af477e0-67c3-470a-be7c-ca7ad3a0128a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utility[water_meter_reading]</value>
      <webElementGuid>22453952-b63f-4a16-aacb-fb589b6410d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;water_meter_reading_field&quot;)</value>
      <webElementGuid>a9fef92b-7a15-4f7c-ae22-80cf6c971ee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='water_meter_reading_field']</value>
      <webElementGuid>3c1464c3-22ae-4800-bf54-9401ef2467cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='void_period_form_select_next']/div[11]/input</value>
      <webElementGuid>224635dc-c105-424d-bd61-6205cff06c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[11]/input</value>
      <webElementGuid>628f02b4-583b-45ea-a9bd-5ca1b919d741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'water_meter_reading_field' and @placeholder = 'Meter reading (recommended)' and @type = 'text' and @name = 'utility[water_meter_reading]']</value>
      <webElementGuid>7a324787-b655-4160-aa6c-83e0000091da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
