<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void - MPRN textfield</name>
   <tag></tag>
   <elementGuidId>57b1827a-e82a-4c85-ae71-fce9fe9d3254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='select_mprn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_mprn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4ea92fa-5d2b-4bb8-adaf-96589da8a055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_mprn</value>
      <webElementGuid>cd5f10b3-a752-4773-ab02-87a06cbcda4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c566b533-e7f6-4793-9e1a-7116cad52014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional  form-control input-lg</value>
      <webElementGuid>21d0c207-28e4-4a70-ad78-37ecd13ce9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MPRN (required)</value>
      <webElementGuid>e9ef3532-c66e-43e5-b5c1-6488f7baf2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1df8d31a-f5b4-4965-a3fe-164ced1940b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utility[mprn]</value>
      <webElementGuid>a3b518df-74f0-41a6-9dcd-1f393f63aadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_mprn&quot;)</value>
      <webElementGuid>3f0d956f-e4b1-4039-afe1-4322b4edafa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='select_mprn']</value>
      <webElementGuid>38e59024-26ab-423d-9bce-57f040930269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='void_period_form_select_next']/div[10]/div/input</value>
      <webElementGuid>f60ad306-d1fc-4e14-8f0d-162628ffa1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[10]/div/input</value>
      <webElementGuid>c5bf7750-fafb-414e-b2d2-5064812d9a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'select_mprn' and @placeholder = 'MPRN (required)' and @type = 'text' and @name = 'utility[mprn]']</value>
      <webElementGuid>c9285180-f69a-4e0c-a476-3dd34c02e7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
