<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void - Electric reading textfield</name>
   <tag></tag>
   <elementGuidId>20e3e384-1e2f-45df-ad39-28899df30a86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='electric_meter_reading_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#electric_meter_reading_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b43dae5e-e3a9-4fe2-8b31-286134f60f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>electric_meter_reading_field</value>
      <webElementGuid>9deaa282-da8e-4f12-a63e-33c6e44399c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>86632bfd-a40e-48dd-9014-0211e7dc27bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>95ce6c95-1562-4f53-8ccd-f3695874b58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Electric reading (recommended)</value>
      <webElementGuid>8c6696e5-195a-4771-8091-199c2ec039fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d904e1c5-4d71-4636-9beb-8406b3ff51fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utility[electric_meter_reading]</value>
      <webElementGuid>52b18c1a-ae4e-4709-96a9-fa230b9feedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;electric_meter_reading_field&quot;)</value>
      <webElementGuid>679814c7-d6e0-4576-8fd8-5f152fd58699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='electric_meter_reading_field']</value>
      <webElementGuid>079ef9b4-2ea8-4ad7-a094-3c968b35f376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='electricmeterhide_field']/input</value>
      <webElementGuid>242ded6b-2739-442d-9fce-ded6b5732675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[4]/input</value>
      <webElementGuid>6c676a22-e84d-46af-8b31-f1ea5fef3904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'electric_meter_reading_field' and @placeholder = 'Electric reading (recommended)' and @type = 'text' and @name = 'utility[electric_meter_reading]']</value>
      <webElementGuid>c97136db-638f-4a94-96cd-929a264b27a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
