<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void - Gas reading textfield</name>
   <tag></tag>
   <elementGuidId>cc41906a-ed11-499e-9a8c-5cfebfbb6cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gas_meter_reading_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gas_meter_reading_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac0ac83d-ae54-481b-90ef-8365a9057e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gas_meter_reading_field</value>
      <webElementGuid>468987dc-322f-416d-a9e8-e23d63e2220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>300241e5-e207-4638-91c2-05d54ccdae1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional  form-control input-lg</value>
      <webElementGuid>6ad9fa97-9602-416f-8063-06a022296eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Gas reading (recommended)</value>
      <webElementGuid>d3bea266-8ef7-418e-9dca-7ea3efe4bd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f7c9121-94b2-4289-aa9a-8e48c412c3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utility[gas_meter_reading]</value>
      <webElementGuid>4f065442-81ea-4515-ac36-83a64abe1d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gas_meter_reading_field&quot;)</value>
      <webElementGuid>6ee76abd-4135-4f85-a12a-ca6fb81a77d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gas_meter_reading_field']</value>
      <webElementGuid>242da261-b71d-4d44-bd53-a3fc14936ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='void_period_form_select_next']/div[9]/input</value>
      <webElementGuid>7fb2f188-0e4a-4e5a-a05e-87a258d3fabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[9]/input</value>
      <webElementGuid>d6f8b64f-51b6-462a-83fc-b381a226f8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gas_meter_reading_field' and @placeholder = 'Gas reading (recommended)' and @type = 'text' and @name = 'utility[gas_meter_reading]']</value>
      <webElementGuid>36f22b00-ce82-40f6-bcc3-f296a80fe2c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
