<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side Panel - Void - MPAN textfield</name>
   <tag></tag>
   <elementGuidId>b92be5df-d723-4ae5-8001-839fd125555b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='select_mpan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select_mpan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>982e4189-d140-42c1-95c1-63477781b229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select_mpan</value>
      <webElementGuid>b4e2641e-f950-45d3-aa76-a0586cebf070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7d0e9867-c0e3-4cf1-9cbe-d9ae3298fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>1f23bf7e-9c58-43a4-ad13-42936a990179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MPAN (required)</value>
      <webElementGuid>64cffa0b-3b21-4513-bd5d-f96aaacf7610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>baef94ca-7f49-4bed-b8fd-f04ece117f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>utility[mpan]</value>
      <webElementGuid>515c1ba8-d3b0-4312-9764-bb147baa790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select_mpan&quot;)</value>
      <webElementGuid>a6f4c6b8-a48f-4b85-87aa-f80d61e01e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='select_mpan']</value>
      <webElementGuid>4efd4798-86c7-462a-9221-3300496f5c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='void_period_form_select_next']/div[6]/div/input</value>
      <webElementGuid>e21be6d7-d354-41e4-85bd-5e54e1d39493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/form/div[6]/div/input</value>
      <webElementGuid>77d5edb1-7ad3-4e03-8e4c-b880690bd526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'select_mpan' and @placeholder = 'MPAN (required)' and @type = 'text' and @name = 'utility[mpan]']</value>
      <webElementGuid>6ae1e807-4900-4efe-b7b1-80911f4fe6b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
