<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Side panel - Tenancy - Create tenancy</name>
   <tag></tag>
   <elementGuidId>e1fc99e5-f251-41ff-91b1-d9ef599f78a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='confirm-add-select-flow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirm-add-select-flow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5e89610-e297-40bb-9ab9-6fa2ecec835f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-add-select-flow</value>
      <webElementGuid>ed3c59d2-afa1-43ce-a605-b92d1a57213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm-record</value>
      <webElementGuid>02be2735-e89a-46da-9d89-6740817d25f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Tenancy</value>
      <webElementGuid>6b67304c-5e9d-4500-9118-c595b7475e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-add-select-flow&quot;)</value>
      <webElementGuid>a559a0f1-4f74-4de2-bdf9-635209d17d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='confirm-add-select-flow']</value>
      <webElementGuid>a91ac4d7-8f94-4df3-836a-8efd58efed1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='myModalDialog']/div/div[2]/div/div[3]/div[2]/div)[2]</value>
      <webElementGuid>e57dcb7b-55ff-449a-8e93-575f3c92be95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[2]/following::div[2]</value>
      <webElementGuid>00b2f14d-28e6-4366-bfd3-f97eb0e7ec3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon AST - Flat 32, Thornewill House, Cable Street, LONDON, E1 0AP, UNITED KINGDOM'])[1]/following::div[46]</value>
      <webElementGuid>1a586d5d-3ec4-4cba-b341-323d4a0667ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send invite'])[1]/preceding::div[1]</value>
      <webElementGuid>ad2807e0-69a2-49fd-96ec-8b14bfad2f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[3]</value>
      <webElementGuid>96c6d517-dd1a-4933-9343-e0b4bf0b857c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[3]/div[2]/div</value>
      <webElementGuid>01690b62-d211-4ad4-8487-8e4346b242f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'confirm-add-select-flow' and (text() = 'Create Tenancy' or . = 'Create Tenancy')]</value>
      <webElementGuid>6293309a-1266-47e3-af1f-09b9b08ab58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
