<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Topbar - Account bt</name>
   <tag></tag>
   <elementGuidId>c77d6065-4e2a-410b-8d50-da1224216708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header-section']/div/a[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav.navbar-nav.navbar-right.hidden-sm.hidden-xs.myrplinkplacement > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>72e6de45-2c14-4cd3-88fe-98e579779bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCOUNT</value>
      <webElementGuid>607239c6-8deb-4b91-8852-d3f079039ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-section&quot;)/div[@class=&quot;container-fluid&quot;]/a[@class=&quot;hidden-sm hidden-xs&quot;]/div[@class=&quot;nav navbar-nav navbar-right hidden-sm hidden-xs myrplinkplacement&quot;]/p[1]</value>
      <webElementGuid>cc26e212-a013-4e12-978b-524290f572a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header-section']/div/a[2]/div/p</value>
      <webElementGuid>1b50a502-2d56-47f7-baba-4aac6379d07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::p[12]</value>
      <webElementGuid>09ef7898-6563-41cf-a08a-d127830e77e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Nav'])[1]/following::p[12]</value>
      <webElementGuid>ad8a2dde-c1ec-4e70-b225-f4172e9268fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Nav'])[2]/preceding::p[2]</value>
      <webElementGuid>2a228778-c4cc-4ede-951d-fea45cc3ced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGOUT'])[2]/preceding::p[3]</value>
      <webElementGuid>050b0c12-286f-40be-b178-d35d6671b48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCOUNT']/parent::*</value>
      <webElementGuid>8392ce14-0f52-4902-8152-5aa72a21be49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/p</value>
      <webElementGuid>7592e18f-c3f5-4b4a-af2a-b365bd426004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ACCOUNT' or . = 'ACCOUNT')]</value>
      <webElementGuid>93f0b9ff-8707-4b97-9f58-50a420b8b796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
