<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Utilities - Search bar</name>
   <tag></tag>
   <elementGuidId>0a3d4273-dd71-42bd-8150-4697f100cb6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search_rtrs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_rtrs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fac6978-99a7-438e-8928-932de47ce650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3454718e-60ca-4ca0-8bcf-5560cc876d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>cc5d2048-b8f4-454c-a57f-f8797a845ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_rtrs</value>
      <webElementGuid>9adcb3c8-98ec-4737-922e-b7e755fb00e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-lg form-control</value>
      <webElementGuid>1040fefa-cdd1-4bb5-966f-fa62412109e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by address or tenant name</value>
      <webElementGuid>a3027eb0-1a7b-409e-a31f-b0705c229d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_rtrs&quot;)</value>
      <webElementGuid>9b15ec4c-d346-4efb-ad48-844700146e1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_rtrs']</value>
      <webElementGuid>dad10e48-0ebd-4c3b-a8a3-955db4bd68a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='summary']/div/form/input[2]</value>
      <webElementGuid>a3031ab6-a118-4082-810d-75ff170ca690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>dfea2249-5b26-4353-8f18-be7afe3db516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'search_rtrs' and @id = 'search_rtrs' and @placeholder = 'Search by address or tenant name']</value>
      <webElementGuid>5f856a40-f5c2-46fc-b225-8326aea9d9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
