<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Landlod name field</name>
   <tag></tag>
   <elementGuidId>bc70a147-fdb8-4996-aed7-064993009e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='landlord_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#landlord_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>434e2380-3a8f-454b-9169-e8472d74196f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landlord_name</value>
      <webElementGuid>9a5c89ec-de33-4d90-b557-49001fb67dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80222e01-6a7c-444f-b44e-ce7172a3c934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac4b68d3-827f-486d-bc1f-bfb29d2cdf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Landlord name</value>
      <webElementGuid>70317cf9-26f6-455e-9b23-ba11e167fb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>366b599a-a3f0-48d3-a71a-80a240271fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landlord_name&quot;)</value>
      <webElementGuid>67d891f6-2f90-474e-a620-12259bf7cf67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='landlord_name']</value>
      <webElementGuid>790706cd-2707-4ff7-886c-f8859b8aeea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='landlord_manual_option_section']/tr[2]/td[2]/input</value>
      <webElementGuid>dac922b6-00f1-4055-8496-69f102b29e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>318bebb0-e7ed-4852-b3fa-9d0b7e19fd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'landlord_name' and @type = 'text' and @placeholder = 'Landlord name']</value>
      <webElementGuid>1a985154-fb64-405f-af28-0fc13c809d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
