<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Proposed start date field</name>
   <tag></tag>
   <elementGuidId>4dedaa36-4b83-4700-8e96-2668b0203491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='proposedmoveindate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#proposedmoveindate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce2b7389-2a34-401e-9bd5-a7339d79bb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a7d2c8e-88d1-4bd3-ae64-a072c3de27a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>To be set</value>
      <webElementGuid>7286ce37-961e-41a8-9aa3-a63981aff88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional datepicker form-control input-lg hasDatepicker</value>
      <webElementGuid>a8799f8b-f37c-4ddb-a1eb-dfefbc0f0463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>proposedmoveindate</value>
      <webElementGuid>614dcd45-b07d-4b06-8cee-d598c4dfbfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>proposemoveindateHF()</value>
      <webElementGuid>111c1a49-ff16-456b-89d0-803f7dd67550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c24581cd-0c97-48c9-9f37-8df9cfc3bb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>invite[proposed_move_in_date]</value>
      <webElementGuid>4f93f82f-c69e-49a2-83ed-dc634b1edf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proposedmoveindate&quot;)</value>
      <webElementGuid>29175372-445b-4646-a118-a7676bb1e5e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='proposedmoveindate']</value>
      <webElementGuid>dd20a2f9-6b2d-47c5-9638-4488555a63ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_invite']/table[2]/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>f8cd4ed7-ba2b-492d-b11a-4b22808707cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>4f939fec-d474-48ff-941e-d32e13a0decc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'proposedmoveindate' and @type = 'text' and @name = 'invite[proposed_move_in_date]']</value>
      <webElementGuid>d832ee7a-576d-47c4-8605-b2d61aea723c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
