<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Landlord home - Line 1 field</name>
   <tag></tag>
   <elementGuidId>e90d4f22-10e2-4b68-99e0-e77e170d5050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_line_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address_line_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cb4e2fb-3a71-492c-a107-8f6504c5da79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_line_1</value>
      <webElementGuid>2651c113-ea33-4330-aa19-e3c1c3f94cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>64ec8a3b-4f9d-44e6-808d-8640546d66e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Line 1</value>
      <webElementGuid>17d816de-6045-4169-bc4b-ef08c0e79606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_line_1&quot;)</value>
      <webElementGuid>850effe4-9ae7-405d-8149-2ae7bed49d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_line_1']</value>
      <webElementGuid>7899f023-377d-4217-96bc-2c55b173c3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='not_uk_address']/td[2]/input</value>
      <webElementGuid>f6545b06-d1aa-47e6-8069-d4f5bd018ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>a7ddbddd-0e42-4b09-bf13-3035456dee88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'address_line_1' and @placeholder = 'Line 1']</value>
      <webElementGuid>c6361951-4950-4759-873f-060816306742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
