<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Landlords home is not in the UK bt</name>
   <tag></tag>
   <elementGuidId>013171da-b28c-4acf-8e55-e2497628e86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='landlordaddress_notuk_link_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#landlordaddress_notuk_link_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>def4bbc1-5d6e-4cd5-bcdd-c05bb259f82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landlordaddress_notuk_link_id</value>
      <webElementGuid>0fe50d85-8b10-47a9-81c6-6cc2d0969ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b504de0d-3bf2-4c3f-9699-2648d6ea5188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_not_uk_address(this);</value>
      <webElementGuid>6916be84-cab5-4751-9359-94ec69474e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Landlord's home is not in the UK</value>
      <webElementGuid>8aa69af6-87a4-45f9-a591-76c9ccaf334a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landlordaddress_notuk_link_id&quot;)</value>
      <webElementGuid>384bbbda-c6f0-44ec-bd62-d495aab7d901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='landlordaddress_notuk_link_id']</value>
      <webElementGuid>0d2004fc-2278-498b-8328-d62f2b95d931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='landlord_manual_option_section']/tr[6]/td/p/a</value>
      <webElementGuid>d823f82f-68fa-4917-9a29-d5d1c736b129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deposit Scheme'])[1]/following::a[1]</value>
      <webElementGuid>4a82b9fc-43bd-4d39-b39c-44c47189ff8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landlord'])[1]/following::a[1]</value>
      <webElementGuid>8a97643c-0e0d-42ad-ad30-63202b89cbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent (Managed)'])[1]/preceding::a[2]</value>
      <webElementGuid>87c6fc70-da5c-4397-9f75-f49b21f3008d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landlord (Let Only)'])[1]/preceding::a[2]</value>
      <webElementGuid>c3133f6a-92f7-4b3d-aa1d-9f96aa2eaa83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>ba3101fd-f4ca-41c9-ba07-eb20bbabacb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>9838e345-53bb-4927-80ac-3c53fc945779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'landlordaddress_notuk_link_id' and @href = '#' and (text() = concat(&quot;Landlord&quot; , &quot;'&quot; , &quot;s home is not in the UK&quot;) or . = concat(&quot;Landlord&quot; , &quot;'&quot; , &quot;s home is not in the UK&quot;))]</value>
      <webElementGuid>54f0036a-c978-4668-a66a-743bd7ca7397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
