<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create tenancy - Landlord email field</name>
   <tag></tag>
   <elementGuidId>6323c63e-e91b-4041-ba32-071a77e442d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='landlord_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#landlord_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a10bc353-5c8a-4883-bf47-5e83af0b7f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landlord_email</value>
      <webElementGuid>585ac44b-d4d5-48b5-b796-08474130878a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26c0ac6f-3130-448c-871c-63153c54868c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7c739c3-ee63-47d7-a8fc-97c0bc3aed96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Landlord email</value>
      <webElementGuid>4b3cb7af-9297-4933-93b0-7f469fdc9ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>52e91a19-476f-455a-9998-beef7d0a6026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>request_id</value>
      <webElementGuid>c82b8074-335c-4c51-85c5-cc8859366cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landlord_email&quot;)</value>
      <webElementGuid>3fdc7de5-6888-4025-b0e6-b32416c29904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='landlord_email']</value>
      <webElementGuid>2cf4aadf-7dba-4d1e-b0e5-32a4e730ef38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='landlord_manual_option_section']/tr[4]/td[2]/input</value>
      <webElementGuid>d01eade3-13dd-4f03-8aaa-addeae44dc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>b832016d-d1a7-4d5e-9c60-6b8b04f62340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'landlord_email' and @type = 'text' and @placeholder = 'Landlord email' and @name = 'request_id']</value>
      <webElementGuid>0b91fee5-694f-4e23-a5aa-fa8791b8ed05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
