<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_09B7E toggle consent for tenant</name>
   <tag></tag>
   <elementGuidId>c010d51e-ab29-4209-96a2-1cb48ed8920b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='standingorderswitch_confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#standingorderswitch_confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5e2a460-e999-492a-8840-f6e8bb12bf99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>9d76f6a5-9618-4895-821c-18fe00b6ee0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>standingorderswitch_confirm</value>
      <webElementGuid>9f62ebf4-7306-4969-bbee-e05dc2207a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;standingorderswitch_confirm&quot;)</value>
      <webElementGuid>60d09222-a1b7-4f47-9643-6e13d80fae05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='standingorderswitch_confirm']</value>
      <webElementGuid>cb8dbaa6-623a-426e-87d5-96a0e02dd89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickytypeheader']/div/label/div</value>
      <webElementGuid>ef168920-3591-4b5f-9666-1d731af950b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/div</value>
      <webElementGuid>cfbc72e1-4dae-495c-9810-1c685b25eef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'standingorderswitch_confirm']</value>
      <webElementGuid>9c69bb30-4e56-4a66-b001-c1c156833c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
