<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_09B7E bt_Create Tenancy</name>
   <tag></tag>
   <elementGuidId>78bd4e6c-2fd8-427c-adb5-406662072a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='invitecheckvalidmobilenewrightside']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invitecheckvalidmobilenewrightside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0905a906-947a-4c6f-aee2-d9d67cf4af0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invitecheckvalidmobilenewrightside</value>
      <webElementGuid>490ce571-ccb4-4103-8931-93f94b4e7856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('invitecheckvalidmobilenew1').click(); return false;</value>
      <webElementGuid>54848f43-f5d5-495a-a59c-aadee1f10032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-lg</value>
      <webElementGuid>2c0563c6-0719-4c63-b38f-36c1aa3954f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Tenancy</value>
      <webElementGuid>40077084-b520-444d-9ade-3ebf82e32ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invitecheckvalidmobilenewrightside&quot;)</value>
      <webElementGuid>c6722cd5-a0cf-4b2b-a3f8-8d1de7d44c0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='invitecheckvalidmobilenewrightside']</value>
      <webElementGuid>7c458a92-6e9c-4b37-b25b-fe667405bf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stickytypeheader']/div[2]/div</value>
      <webElementGuid>78c3d6a5-45e7-4625-8a89-83f79094e1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new'])[1]/following::div[11]</value>
      <webElementGuid>5073f902-ca42-422d-a37e-807ec5010705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[2]</value>
      <webElementGuid>d64c9ca1-4660-4647-ab48-24cc6323308a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::div[2]</value>
      <webElementGuid>d6366e97-86c0-4f51-9155-966114cd238e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div</value>
      <webElementGuid>a69aba88-c565-4c9f-8cfd-3fbdf6ff6618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'invitecheckvalidmobilenewrightside' and (text() = 'Create Tenancy' or . = 'Create Tenancy')]</value>
      <webElementGuid>55f92050-9333-460d-aaea-2c3601b7e545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
