<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car parking_Start bt</name>
   <tag></tag>
   <elementGuidId>7dadd074-e7e1-4b0a-ac03-ebbef007ccc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='car_parking']/span/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-green.btn-lg > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1e8add0-d443-4e5d-8dc7-8dab5602f4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start</value>
      <webElementGuid>ccc14cb4-f3de-4b60-96da-4b8d01183602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;car_parking&quot;)/span[1]/a[@class=&quot;btn btn-green btn-lg&quot;]/span[1]</value>
      <webElementGuid>e4a3b212-90d3-4579-8371-16871f62834f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='car_parking']/span/a/span</value>
      <webElementGuid>b0038f19-5f3e-406e-871c-6831f70d1ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View details'])[1]/following::span[2]</value>
      <webElementGuid>a78a83a3-da7f-44bc-9a3a-450780b10eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::span[1]</value>
      <webElementGuid>ee332fd9-531f-4cdc-a50b-0cbfb57e9c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::span[1]</value>
      <webElementGuid>123ebc9b-6d98-409a-bc9c-ce6e64bdcf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start']/parent::*</value>
      <webElementGuid>e30d56d2-29d2-43ab-a2d8-27278f6d32bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/a/span</value>
      <webElementGuid>e289fa52-5240-4d8e-a909-be78f785e6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Start' or . = 'Start')]</value>
      <webElementGuid>2bfaf34d-5469-4987-afa6-2ccec0077b56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
