<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Direct debit - TA type signature field</name>
   <tag></tag>
   <elementGuidId>cba02c7d-84d1-456f-a94f-8a8f7d47193d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#write_signature_canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='write_signature_canvas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f583d31-aa63-404b-8536-67c3d7332228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>writesigncanvas_onChange()</value>
      <webElementGuid>1b227ceb-0fc1-4f50-8f7d-0f185ec05332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>write_signature_canvas</value>
      <webElementGuid>739206f7-e9e1-4e28-9aee-3fadcf04d349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>57650c0e-f119-4902-891f-26444d86bbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;write_signature_canvas&quot;)</value>
      <webElementGuid>abd65f56-9982-424f-bdc7-b568e7d32ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='write_signature_canvas']</value>
      <webElementGuid>5da18554-3afd-4463-b2af-75b40639965a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter_write_signature']/input</value>
      <webElementGuid>e468abd3-0283-422a-a06e-c5f2da0f0ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>64c5c09b-a26b-4ece-a0aa-c3103218b439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'write_signature_canvas']</value>
      <webElementGuid>7c7f197a-51ee-444e-a979-f30a5f2ffad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
