<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_work status Continue bt</name>
   <tag></tag>
   <elementGuidId>1a19ee65-8975-48ee-a870-5c753bcdfebc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employmentbtnvalid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='employmentbtnvalid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0485dbb3-d758-467f-8e40-2ed2654dfba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkgreen btn-lg btn-block</value>
      <webElementGuid>5d657d26-f8f3-4ccf-a78e-417dd19a12f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employmentbtnvalid</value>
      <webElementGuid>0ea099db-8554-4f71-b645-d33abb3c6719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>workplacesection1();</value>
      <webElementGuid>600c76f1-fa5e-4a73-8b98-c4325afd8df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>47ab2871-a399-41db-9888-f59ee8454763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employmentbtnvalid&quot;)</value>
      <webElementGuid>895baca7-e2fe-47dc-bd49-03c181b595ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='employmentbtnvalid']</value>
      <webElementGuid>e6131095-86f2-4ebf-9474-f7c30117c872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employment1stpart']/div[9]</value>
      <webElementGuid>1d2da22b-57f8-4bd7-8f30-6a8b58d2cf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[11]/following::div[9]</value>
      <webElementGuid>260456e8-e04a-4c8b-8032-f1328421dd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[11]/following::div[9]</value>
      <webElementGuid>ebdaa8a8-fa17-4b05-b529-fd6599ea1f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back a step'])[8]/preceding::div[1]</value>
      <webElementGuid>a7cebe8e-e466-4351-b6ed-2ec3632dfdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::div[3]</value>
      <webElementGuid>fdf44c09-273c-4280-b191-b60efa803db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[9]</value>
      <webElementGuid>84fdb157-3941-4eda-ac8b-ce605cf2d72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'employmentbtnvalid' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>4b96450f-a54d-47d8-a67a-5e444da319cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
