<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rental history  address</name>
   <tag></tag>
   <elementGuidId>b18b9f17-c4f8-4a16-99e5-ae8db762cf82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressdone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressdone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed8469d3-eb79-4426-95db-4e2971cc504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressdone</value>
      <webElementGuid>3c4ae801-fc58-4c62-8666-92a17057113a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeId('addressdone', 'renter_recommendation_rental_address')</value>
      <webElementGuid>6984a5df-585a-4ec7-ab8e-ff74e706f15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg addpropinputsu landlordrefsection</value>
      <webElementGuid>8762ab29-1da5-4205-9f0b-1e9669603fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select'</value>
      <webElementGuid>69279365-ef20-47ae-8fa6-761dbd10eb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select</value>
      <webElementGuid>859b52ec-c977-471a-a1df-bb81070e852c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b5909c4-7f12-4070-b058-f85a3a9777a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[recommendation_rental_address]</value>
      <webElementGuid>c21f8dac-5f1d-495e-a338-edcd10d99820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>32586ff0-68e6-4fe8-b422-1b48b4a76482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressdone&quot;)</value>
      <webElementGuid>4b224db8-05a6-496f-8e4f-03477893c070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressdone']</value>
      <webElementGuid>b6faadfb-5e6d-461a-9864-e4b3e0ad0584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/input[2]</value>
      <webElementGuid>850ef565-dcf8-40ae-8629-be6c8c70af5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>cf4c1615-4221-42e5-8f03-a68ad3ea05e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressdone' and @placeholder = 'Start typing and select' and @type = 'text' and @name = 'renter[recommendation_rental_address]']</value>
      <webElementGuid>234f3433-1ff8-4622-87d7-1e78fc872569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
