<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_employed w_email address</name>
   <tag></tag>
   <elementGuidId>55c4399d-f6b1-4809-a0d6-bec0072aca1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employedworkplacemail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employedworkplacemail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dba425e1-1387-4aab-a490-1e5e9caa632f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employedworkplacemail</value>
      <webElementGuid>2530f81b-eb2c-4d07-a3a5-d901127ab697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2630066-3d38-4688-b3c5-11d400b730a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string email optional form-control input-lg</value>
      <webElementGuid>49417206-0095-4040-959a-4eda97d4f94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter your own workplace email address</value>
      <webElementGuid>fd676a19-7de6-4569-a738-ab9831ddaea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[workplace_email]</value>
      <webElementGuid>4ccf11c3-a40f-4c47-946e-a771456d3c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employedworkplacemail&quot;)</value>
      <webElementGuid>adf2cbdb-4276-4fad-bb5e-d0dd3698bdd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employedworkplacemail']</value>
      <webElementGuid>1185d911-f73f-4a04-8a32-75274bca805f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employedworkplacemaildiv']/input</value>
      <webElementGuid>03cb9288-9257-4414-86d6-27d37599b16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[6]/input</value>
      <webElementGuid>43fb2fcb-886d-43c7-9054-1eb59c8c90a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'employedworkplacemail' and @type = 'text' and @placeholder = 'Please enter your own workplace email address' and @name = 'renter[workplace_email]']</value>
      <webElementGuid>524ba1fa-7c19-4229-adb8-11175e93df3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
