<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_identity check address bar</name>
   <tag></tag>
   <elementGuidId>2919805e-1c43-4a5b-934d-6c0a1625bd02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d4fa86f-0b59-46bf-b85d-716785c8769b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ebda260-6bc2-4526-b391-dd0e480e397c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee636674-4871-439e-aea0-168a7b504b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop</value>
      <webElementGuid>d537871e-68f3-4e2d-a6ad-74f84f0c7c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>afb0d403-d010-42ee-af4c-230677a22eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select address'</value>
      <webElementGuid>e06cd9f7-bd5a-4c77-a0c3-b1bfdca0fca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select address</value>
      <webElementGuid>74c67f6d-9c9a-4a7c-9f24-5c62d12ab019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[home_address]</value>
      <webElementGuid>4401e034-0c15-421d-8ee0-b3ba21ec856f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop&quot;)</value>
      <webElementGuid>69761135-fb84-401f-80d5-10121855cac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop']</value>
      <webElementGuid>2e17c443-e6ea-48c0-8604-c5d32c4c19e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uk_address']/input</value>
      <webElementGuid>cc33dd2e-dd2c-445a-b6ae-494b225c2c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>177e16e5-15e6-4003-99fc-976ae629550a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'prop' and @placeholder = 'Start typing and select address' and @name = 'renter[home_address]']</value>
      <webElementGuid>6e45623d-f08d-4cd5-8c28-3bc90fb0a126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
