<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_letting agent email</name>
   <tag></tag>
   <elementGuidId>4463f86f-1ecc-42c5-9cb7-6ceea0d9a8cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lemail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lemail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b92bcf4f-390c-4478-8438-5a64f260161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>725c8606-7080-49d4-b83e-dd5e6d3b0336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lemail</value>
      <webElementGuid>672e5b6f-e9cc-421f-8fb6-dac1f9846ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string email optional form-control landlordrefsection input-lg</value>
      <webElementGuid>5d2f7ea4-dcf2-47f7-9458-997c9d8b8250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Letting Agent email address</value>
      <webElementGuid>d0fa3739-8cbb-4a19-8204-8611abc5f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>67b0fedc-1d7a-4ebf-9931-8ccf5d472cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[l_email]</value>
      <webElementGuid>254ee9e1-4719-46bb-8791-96571bb18727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lemail&quot;)</value>
      <webElementGuid>354fe9a3-5e68-4bf8-adcb-1e2b9e0279d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lemail']</value>
      <webElementGuid>7f6dad2f-ae29-40bd-9fdc-aa35b0483681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/input[5]</value>
      <webElementGuid>0eb7851d-5e07-4635-82ee-fc60e18736bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[5]</value>
      <webElementGuid>1bbf06fb-9e9e-447b-b5bc-baa0b38ca4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lemail' and @placeholder = 'Letting Agent email address' and @type = 'email' and @name = 'renter[l_email]']</value>
      <webElementGuid>8b466bfc-d63b-4d60-b561-47d70bc32944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
