<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>0da7dbcd-3c0d-4edc-8922-cb7be5a19f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renter_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renter_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f54858cd-741f-4d7c-8095-1a3ec573a986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5cb4a95-052b-4962-be4f-6777bed4c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password optional form-control input-lg</value>
      <webElementGuid>2d637ca2-6bc0-495f-aadb-0b8b25cf9307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>96a7e177-4a46-4af6-9f7f-ac70a1de1b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>659a4e7c-d875-450f-9e85-94f1118a58d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>06252ab5-306a-4f85-ab3f-9e78e6806001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f3a90972-7171-4fb4-8bf3-48d116ed932c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[password]</value>
      <webElementGuid>79a30bfb-163d-42a7-a344-d3487f910f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renter_password</value>
      <webElementGuid>087ca9ff-bb84-4fa1-98ff-2dbc396a94c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter_password&quot;)</value>
      <webElementGuid>cd429504-bb6e-4713-9973-6d38abba59be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renter_password']</value>
      <webElementGuid>f3c78e00-e39a-4a18-9cc1-f34960d3ce42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/div/input[10]</value>
      <webElementGuid>fd6cf805-b71c-4dca-8d26-f5664bf0624a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>a14896fb-abcd-45c3-8d46-696a98b7f45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @type = 'password' and @name = 'renter[password]' and @id = 'renter_password']</value>
      <webElementGuid>791e6f47-a5b5-4eee-8e7a-eb7744dadd79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
