<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_employed job title</name>
   <tag></tag>
   <elementGuidId>763aa2e1-c885-4386-86e8-3d583a4ac29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renter_job_title_manual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renter_job_title_manual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c56107ec-b06a-44d3-a3af-d9b96754d4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22a97732-4596-409c-9599-4cd82ccef00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>ab91fcf5-9eaf-411a-9ef3-f2149df07aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title</value>
      <webElementGuid>1cbb0512-7d83-4d5f-9118-fd32f2233c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[job_title_manual]</value>
      <webElementGuid>79b8a211-5cc0-4bb3-87aa-3d5c88e2d6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renter_job_title_manual</value>
      <webElementGuid>9012eee4-9bdd-4ec9-8fa9-1819ecd035e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter_job_title_manual&quot;)</value>
      <webElementGuid>a0829659-cbde-42c1-9c7b-fbbd8b7f833f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renter_job_title_manual']</value>
      <webElementGuid>ee75d0c8-1dff-4079-bde4-ab1400b10f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employment1stpart']/input[2]</value>
      <webElementGuid>ef0a86e5-61ef-4f10-824b-29b226c2b135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input[2]</value>
      <webElementGuid>b7c6c6a1-5a18-4a4b-912f-8f12a1e0d42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Job title' and @name = 'renter[job_title_manual]' and @id = 'renter_job_title_manual']</value>
      <webElementGuid>7878d201-acfb-4704-980c-dc090e881930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
