<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_letting agent name</name>
   <tag></tag>
   <elementGuidId>953da27c-7932-4b35-802f-1ca178bd5fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lfirstname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lfirstname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31f09ded-4d81-47aa-ac57-666c5feb6838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>edc53b8c-2f35-4450-8fa5-c26d0591ba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lfirstname</value>
      <webElementGuid>d70e486d-dd43-4f11-8104-0a6f9812d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control landlordrefsection input-lg</value>
      <webElementGuid>96ba154a-dbcb-498e-9083-c97870b646d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Letting Agent name</value>
      <webElementGuid>e2cb01c5-7218-438d-a4c5-22172b1c31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a5d6469-6404-4bae-b150-016073a617e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[l_first_name]</value>
      <webElementGuid>8057aa33-a5c6-4d80-9b3d-c6cd578b18f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lfirstname&quot;)</value>
      <webElementGuid>71cf1d32-68ce-481d-afa1-63a69dac88b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lfirstname']</value>
      <webElementGuid>5005ce9d-1430-4ba6-b39b-04e870bb61a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/input[3]</value>
      <webElementGuid>43baa556-ddd5-4b68-978d-a81055bb1069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>674a2627-16ca-4990-9430-8cb8b96e7f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lfirstname' and @placeholder = 'Letting Agent name' and @type = 'text' and @name = 'renter[l_first_name]']</value>
      <webElementGuid>2798a383-b6d5-4bcb-aebd-15eed7235f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
