<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_employed_company name</name>
   <tag></tag>
   <elementGuidId>773ccf5f-5590-4acb-aa64-ca5d59a24091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renter_company_name_manual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renter_company_name_manual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a86ac973-e9f0-46f5-ba98-137cc9c8f66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>662df183-ac6d-4694-89c0-4a4bd6bcfb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>bad0d4b2-cba6-4d18-b3dc-ae534fad974d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Company name</value>
      <webElementGuid>73e82759-d21b-49d3-b46e-cccecb51fdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[company_name_manual]</value>
      <webElementGuid>7c41595d-1e21-4bf7-a070-c99a40eb6455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renter_company_name_manual</value>
      <webElementGuid>91204a78-1b15-457b-8774-dbb5aac92bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter_company_name_manual&quot;)</value>
      <webElementGuid>8f0f7c7e-6e68-49dd-aa11-e477830dbe28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renter_company_name_manual']</value>
      <webElementGuid>bb85bc0e-9cb9-48d6-a656-02172b6eeb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employment1stpart']/input</value>
      <webElementGuid>67c4c442-b76d-4980-8946-a837d5c609f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>e08d11a4-301b-45cd-8e12-a6e7abc9d4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Company name' and @name = 'renter[company_name_manual]' and @id = 'renter_company_name_manual']</value>
      <webElementGuid>f331b140-8b4a-442d-90f4-fd29c12544fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
