<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_identity check dob - ddmmyyyy</name>
   <tag></tag>
   <elementGuidId>e1537bae-d55e-44b4-bad6-6abc0e30a202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renter_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renter_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9a6770b-0732-43fa-af3a-76bb823fb4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c23d7dd-b0a8-471f-bb58-0386d46dd58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>1357f1fb-bc67-4e9b-b536-4076661f18e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of birth</value>
      <webElementGuid>2f4d3f24-284c-4620-abde-81a52540c843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[dob]</value>
      <webElementGuid>1e7adf5f-b4eb-4a33-9065-a6180d8df596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renter_dob</value>
      <webElementGuid>2cfea7ec-6d26-4447-8435-53c0eafe0802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter_dob&quot;)</value>
      <webElementGuid>cee00f64-471c-4950-9301-1e01d13943c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renter_dob']</value>
      <webElementGuid>e662913e-750a-4db4-9326-30fadf068613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_renter']/input[11]</value>
      <webElementGuid>2f6c0fb2-4a2f-4dbf-a433-6fe104b2bfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>82188116-3106-4b0a-bc7b-441bcf053f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Date of birth' and @name = 'renter[dob]' and @id = 'renter_dob']</value>
      <webElementGuid>772bf5f8-f549-4295-815c-e2ae709d1fd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
