<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Identity check - Continue bt</name>
   <tag></tag>
   <elementGuidId>78d4707a-88b8-4976-98f9-8b7083e17811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkvalid3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkvalid3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6eb4cc92-2aef-47e4-bcec-7fb2b81f2002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkgreen btn-lg btn-block</value>
      <webElementGuid>b51dad0f-180e-49e5-a63f-e921d27c0402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkvalid3</value>
      <webElementGuid>78456b45-a1df-4e0a-9bc7-a06d4dbf6513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>aac5450b-000b-44b7-b335-d81f86726bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>493f9ebf-bad9-4bc2-9e20-cdb8766bc2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkvalid3&quot;)</value>
      <webElementGuid>b02bece6-7837-4c39-af6b-7519a42ee2d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkvalid3']</value>
      <webElementGuid>7027e9df-0349-43ad-a36f-48ad08bccdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_renter']/div[14]</value>
      <webElementGuid>4ea119ce-3148-42d2-a339-d86f0b60e8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[1]</value>
      <webElementGuid>d7c142bf-fefb-490d-abae-b8bccf9e387f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::div[8]</value>
      <webElementGuid>17bdbd00-2415-4f81-83a9-8a3e206492b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back to myRentProfile'])[1]/preceding::div[1]</value>
      <webElementGuid>0291904b-03da-4b6d-90a5-63482159496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[1]</value>
      <webElementGuid>1036f66b-838b-467f-90c0-cf04da9815a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>6971e79d-a32c-40bc-a6de-9a19d6a306f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]</value>
      <webElementGuid>f347e2e6-a7fc-41c7-a7ed-544044c92e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkvalid3' and @href = '#' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>e541b52c-08b5-400d-ab1f-88c205355aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
