<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - First Name field</name>
   <tag></tag>
   <elementGuidId>9390eec7-4e6e-4a9f-97be-692691ef2175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_of_kin_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next_of_kin_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440bacf6-17cc-43d7-8541-7ad0ca13441c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_of_kin_first_name</value>
      <webElementGuid>41452475-589d-403d-a11f-051b71bf2904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04759c5b-def3-4fb8-ba0c-6f709be13b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>1090475c-c608-4aee-a096-64ceb4cdb784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>64533d5c-ca32-48f6-8c5f-ff901cdece5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[next_of_kin_first_name]</value>
      <webElementGuid>f19da48d-7b46-4287-8938-b24329f4f571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_of_kin_first_name&quot;)</value>
      <webElementGuid>17da6372-d83b-44b0-9b9f-321f449decfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next_of_kin_first_name']</value>
      <webElementGuid>cb32fb73-bfb5-42f4-8e7d-450ea7c0b11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/input[3]</value>
      <webElementGuid>98a39c63-e326-4efd-a008-9b72673adfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>0167bab6-2553-4e6c-9630-8bd2020f9df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'next_of_kin_first_name' and @type = 'text' and @placeholder = 'First name' and @name = 'renter[next_of_kin_first_name]']</value>
      <webElementGuid>44bb336f-2335-443b-9a18-8b4a5a4d4d2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
