<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Town-City field</name>
   <tag></tag>
   <elementGuidId>23107b1d-4340-463d-98f7-08223a855db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04f382d3-ce94-4ae8-a96f-fce5ec9dfce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>222aee96-9b6e-4359-b081-77c7e063ea27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_city</value>
      <webElementGuid>565802e3-1513-47fe-8ea5-d91c9bde6c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>cef5809f-bb32-4a54-af50-6ae0d928d118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Town/City</value>
      <webElementGuid>33dbbcc0-87e5-4397-b76b-cd17c6e0fb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[address_city]</value>
      <webElementGuid>009f54a7-7698-4559-a2c6-865066c1ac0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_city&quot;)</value>
      <webElementGuid>c034b58c-bdb3-4e01-be5e-e4d130166e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_city']</value>
      <webElementGuid>fdebd172-7d7c-4b7d-9ae1-0e5a33597a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_uk_address']/input[3]</value>
      <webElementGuid>aa6ceed2-e33a-457b-ad77-4b8133dd9b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[3]</value>
      <webElementGuid>ef8de1f8-e417-4357-ab40-94f1cacaf892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_city' and @placeholder = 'Town/City' and @name = 'renter[address_city]']</value>
      <webElementGuid>6c319226-b8a6-410d-ac72-7339c6335552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
