<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of kin - Home address line 2 (optional)</name>
   <tag></tag>
   <elementGuidId>fb54b8f9-1351-499d-9903-d99f695d720b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_line_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address_line_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e902d614-24e0-4fab-9d4b-6417e3ecfbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53ee01d1-954c-46c3-94a4-30bb053fd5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_line_2</value>
      <webElementGuid>df6d2c82-a693-4594-aebd-587340be559e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>60746fdf-7030-4564-9824-5c0057493467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Home address line 2 (optional)</value>
      <webElementGuid>84e3ea31-4589-421d-88a2-cba79235bab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[address_line_2]</value>
      <webElementGuid>f449553d-dc36-4efa-9cb2-f1f682d48743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_line_2&quot;)</value>
      <webElementGuid>cde8f958-5878-452d-90c8-6850c003bc52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_line_2']</value>
      <webElementGuid>12b1fcd0-8f26-4101-9bac-a59c5292520b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_uk_address']/input[2]</value>
      <webElementGuid>6fd92738-2ac5-424d-85cc-493dd8c06c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>a04171df-a993-433f-b163-32898e634bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_line_2' and @placeholder = 'Home address line 2 (optional)' and @name = 'renter[address_line_2]']</value>
      <webElementGuid>b6fe0093-c5f6-4c80-9b7b-f7973ab037db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
