<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Home address is not in the UK bt</name>
   <tag></tag>
   <elementGuidId>623417f1-0513-440b-806f-c6c00021794f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p_not_uk_address > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='show_not_uk_address(this);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40c47724-d0f1-42c4-bbf8-65091cb74f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>49e6b0b6-d7ca-41bd-b902-8bad4dad2266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show_not_uk_address(this);</value>
      <webElementGuid>a586876c-a7bc-4136-ac67-c0dc0c36fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home address is not in the UK</value>
      <webElementGuid>cfde4740-7a47-45d2-ae42-1b7f98e4ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_not_uk_address&quot;)/a[1]</value>
      <webElementGuid>98a70b2e-045a-4211-8ec5-82e88aac6812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='show_not_uk_address(this);']</value>
      <webElementGuid>69074c87-cdd2-47ab-9290-9871d59ebea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='p_not_uk_address']/a</value>
      <webElementGuid>f813155e-963a-40d7-827f-a443df7654d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home address is not in the UK')]</value>
      <webElementGuid>29186e00-eb39-4877-b90f-36753ede33df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next of Kin'])[1]/following::a[1]</value>
      <webElementGuid>f86da304-bfc9-413e-b29c-9b963ab1c6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[2]/following::a[1]</value>
      <webElementGuid>41979bd0-3ea0-42e6-aaf1-f508f76845e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::a[3]</value>
      <webElementGuid>73940659-e4c1-4b7d-92d3-55a3424296b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::a[4]</value>
      <webElementGuid>fd0c1d46-504f-48d3-86ff-20656440f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home address is not in the UK']/parent::*</value>
      <webElementGuid>99aa82ad-6942-4c6b-86fc-20df80433fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>215839ff-cccc-44f9-92c5-f16b61b7996b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>a2dd1e1c-5a28-4147-be5b-741a261ed0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Home address is not in the UK' or . = 'Home address is not in the UK')]</value>
      <webElementGuid>9bc33a7a-4d5f-4fb8-92d8-de3607bafac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
