<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - I do not want to include next of kin details bt</name>
   <tag></tag>
   <elementGuidId>2bfe3209-4054-49fb-a5cd-8e38ed66ca0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new_renter > p > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='setNextOfKinFalse(event)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb4fd7b3-5c01-4658-9e78-2e90284c1e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setNextOfKinFalse(event)</value>
      <webElementGuid>69336d18-49e6-40ac-8bc8-d759aff90469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5171e684-30f3-430b-bfc2-4c4e3d490d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I do not want to include next of kin details</value>
      <webElementGuid>8e8767a3-9197-4fca-9a22-5c923a07561c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_renter&quot;)/p[1]/a[1]</value>
      <webElementGuid>830b2582-9171-4428-a65a-f84d287c2200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='setNextOfKinFalse(event)']</value>
      <webElementGuid>26f67e6f-efc1-4a24-bc41-52836a3ecf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/p/a</value>
      <webElementGuid>99e5e1f7-0145-49e7-8b48-fdb836c02617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'I do not want to include next of kin details')]</value>
      <webElementGuid>ec2630cc-2f45-4028-b7f9-c6ee43c852f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::a[1]</value>
      <webElementGuid>2db037b8-4eec-428f-848a-2864b44c0e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next of Kin'])[1]/following::a[4]</value>
      <webElementGuid>33334db9-862c-4255-9ee4-fd5af7632269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::a[1]</value>
      <webElementGuid>82d0e618-f954-4ce0-95ac-a1051f64d136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/preceding::a[1]</value>
      <webElementGuid>8f66eadc-d1d2-4807-bfbc-2118880fe57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I do not want to include next of kin details']/parent::*</value>
      <webElementGuid>5ce850aa-17b1-4d16-92a7-406582df4944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>3126edf3-43c0-457b-a547-9cfbc5b0815c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/a</value>
      <webElementGuid>fd17e750-c894-42bd-b3cb-31fcf7dbe0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'I do not want to include next of kin details' or . = 'I do not want to include next of kin details')]</value>
      <webElementGuid>f79933e7-8d43-442d-bacb-f737ec20c8fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
