<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Mobile number</name>
   <tag></tag>
   <elementGuidId>105fb49e-885e-4dc3-a5b9-95b96d1c9625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_of_kin_mobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next_of_kin_mobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f286f42-c12d-4928-b5c1-654fbfb00d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_of_kin_mobile</value>
      <webElementGuid>3972e77e-89f1-462f-a93d-6cb1ab65592a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tnyext</value>
      <webElementGuid>cf481e6a-ee5c-4e36-b07f-53c588b97649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>e842c6ef-8ca0-4bc6-911f-69d992240c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile number</value>
      <webElementGuid>ebdd40be-783a-42f8-b62e-1ace0b3de232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[next_of_kin_mobile]</value>
      <webElementGuid>cedf29a3-1287-4166-aaee-06bf046cb62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_of_kin_mobile&quot;)</value>
      <webElementGuid>5a66bf4a-5c1f-4914-89d0-faa03d87e44d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next_of_kin_mobile']</value>
      <webElementGuid>aab2c9bf-c588-4ef0-84a0-95b1f43313e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/input[9]</value>
      <webElementGuid>5e783386-cab9-4f4e-afc7-ef7d40ea17d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>db8a243a-1e6f-4c66-a56f-39f8245060da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'next_of_kin_mobile' and @type = 'tnyext' and @placeholder = 'Mobile number' and @name = 'renter[next_of_kin_mobile]']</value>
      <webElementGuid>19061fde-5fa8-42c6-9b14-a2904166d69d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
