<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Email address field</name>
   <tag></tag>
   <elementGuidId>bbc0b439-920b-45bd-bd8f-cd4945355ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_of_kin_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next_of_kin_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22653b2b-74d6-4643-82b5-6aa1faa64f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_of_kin_email</value>
      <webElementGuid>b746edcd-a959-42e7-a9d2-50cbba83ff17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tnyext</value>
      <webElementGuid>7545779c-d1fa-4529-b6c6-62778f0f77b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string email optional form-control input-lg</value>
      <webElementGuid>737b94e7-98de-4787-8ff9-cab6cd6400dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>d424325a-b189-49b5-b788-4bb5a9815bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[next_of_kin_email]</value>
      <webElementGuid>58eb69b8-4691-4aae-83e9-6308f4959b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_of_kin_email&quot;)</value>
      <webElementGuid>6265840a-a7ee-47b0-a2d7-f8dcf0299262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next_of_kin_email']</value>
      <webElementGuid>33b1a6f3-d057-4eee-9402-389d350baf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/input[8]</value>
      <webElementGuid>1338035c-b2d9-45f3-99fd-e00409d73ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>3a83a7c9-855a-46bf-9f46-646912b99316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'next_of_kin_email' and @type = 'tnyext' and @placeholder = 'Email address' and @name = 'renter[next_of_kin_email]']</value>
      <webElementGuid>e4810a5e-b997-4b08-8577-8b8bc8245864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
