<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Select relationship dropdown</name>
   <tag></tag>
   <elementGuidId>5830b634-654e-4271-a3b5-4a220e1a7e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_of_kin_relationship</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='next_of_kin_relationship']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8bb4d3ea-6de9-493c-816c-13b9daf1d7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_of_kin_relationship</value>
      <webElementGuid>5abeff66-b03e-41ef-ad45-daa98805b818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>relationship_function()</value>
      <webElementGuid>cd0eada4-27e9-49eb-9445-517220a01dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg</value>
      <webElementGuid>2eae435a-4887-491a-93f9-a296efcb72db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
     Select relationship
    Spouse
    Son
    Daughter
    Father
    Mother
    Guarantor
    Roommate
    Friend
    Other
  </value>
      <webElementGuid>f3ed625c-a01f-4ab4-9c00-07d132ba42a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_of_kin_relationship&quot;)</value>
      <webElementGuid>ccd53d70-1878-48be-92ce-fa53066b123b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='next_of_kin_relationship']</value>
      <webElementGuid>bd46081c-860d-421e-a299-275a50df4954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/select</value>
      <webElementGuid>fbfc62cc-2054-4c65-8e09-c112b100c53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next of Kin'])[1]/following::select[1]</value>
      <webElementGuid>6eaea7da-9b69-4d7d-9c65-25103c771e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[2]/following::select[1]</value>
      <webElementGuid>9432b723-3ff9-4e48-91e1-2c03b0137954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[2]</value>
      <webElementGuid>036f62d8-97ea-4cff-8f2e-73dae3ff9f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::select[2]</value>
      <webElementGuid>21558bea-8ada-4edd-b188-764dbd9b1956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aa7bd5cc-2080-448f-8a5b-eac298b8e114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'next_of_kin_relationship' and (text() = '
     Select relationship
    Spouse
    Son
    Daughter
    Father
    Mother
    Guarantor
    Roommate
    Friend
    Other
  ' or . = '
     Select relationship
    Spouse
    Son
    Daughter
    Father
    Mother
    Guarantor
    Roommate
    Friend
    Other
  ')]</value>
      <webElementGuid>dfb00f03-1e14-48bf-b0ca-9e34c948e86c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
