<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Home address line 1 field</name>
   <tag></tag>
   <elementGuidId>fe9db4ed-f3cb-43d1-b81b-9d232b47b8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_line_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_line_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f403d8ce-7fe6-45d2-9b44-43d679d20b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7742a156-9b5f-4d3d-874d-67c1859dbaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_line_1</value>
      <webElementGuid>424e582c-ed11-4cbb-b0d2-5b0a5db4da0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>1f3ff3e8-e3fd-489c-85d5-34de5978e686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Home address line 1</value>
      <webElementGuid>eef09947-e823-42fe-ab4b-bd41dde0583d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[address_line_1]</value>
      <webElementGuid>c5687c4f-9276-4051-80b8-6d5efcaafec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_line_1&quot;)</value>
      <webElementGuid>0996cd3a-6a02-498d-9126-52e635869671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_line_1']</value>
      <webElementGuid>69b7b609-2580-4ac0-a693-66d9767e06b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_uk_address']/input</value>
      <webElementGuid>e5185157-ddd2-4ca7-a1e4-6a469d6e36a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>4903db56-a601-40c9-af2e-26ea7f7a9b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_line_1' and @placeholder = 'Home address line 1' and @name = 'renter[address_line_1]']</value>
      <webElementGuid>759a2281-b012-4b0d-94fe-71af5fc6c53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
