<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Last Name field</name>
   <tag></tag>
   <elementGuidId>163ee7ca-7c07-4431-bf5b-6fb2c2d4c95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next_of_kin_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='next_of_kin_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad93ef0a-cd06-43ac-a03e-816925cb29b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next_of_kin_last_name</value>
      <webElementGuid>8d6990f7-3322-4043-a1f2-3f906b375964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61385ede-7305-4131-ab23-493a44b7dd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>99ade390-eaaa-4346-90fd-ba42b0b4802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>5e2219ba-0dc8-4f8d-9da8-c079bda2b5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[next_of_kin_last_name]</value>
      <webElementGuid>0652d95e-17fb-4c09-8aae-1ff56f5af85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next_of_kin_last_name&quot;)</value>
      <webElementGuid>5bf33ba8-6bf6-4753-afa5-02a2a16bbd3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='next_of_kin_last_name']</value>
      <webElementGuid>cf8c30aa-e1b5-4c81-a993-561378ffc4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/input[4]</value>
      <webElementGuid>db40ce0c-b120-4b82-833f-492cb6cf8eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>be2f4e03-64ec-41e9-b876-594f8cedd8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'next_of_kin_last_name' and @type = 'text' and @placeholder = 'Last name' and @name = 'renter[next_of_kin_last_name]']</value>
      <webElementGuid>b22f9924-54df-4281-bf94-4d4eb572863e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
