<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Address field</name>
   <tag></tag>
   <elementGuidId>a4a4782f-6c73-48ec-b92a-07065b18f21b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6955630-affd-48e1-a567-df6b4024c96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5226f17e-67da-4e62-9240-bbe1b459fc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce22f24d-8e5a-4603-afe3-4210643b8e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prop</value>
      <webElementGuid>842ff243-729e-4ef5-a6eb-94f6bd5c4757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>047f3c68-d43d-41b5-bd9b-01f84cd79184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder = 'Start typing and select address'</value>
      <webElementGuid>1d5a449d-d536-48ad-b33c-3bd99be2934c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start typing and select address</value>
      <webElementGuid>83b65088-e14e-4d0d-9d04-cff137db7509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[next_of_kin_home_address]</value>
      <webElementGuid>ea0c1995-9a0a-41ad-96ac-0e50cb9fccf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prop&quot;)</value>
      <webElementGuid>39d838d6-7512-49f0-b8ed-5b2f7622264b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prop']</value>
      <webElementGuid>a0f0fee9-5882-40c0-82c6-aba6f73560e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uk_address']/input</value>
      <webElementGuid>4fe23856-d511-468f-8360-13d7d863b653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>0380aeaa-0560-43ff-abb5-d8c5feb49617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'prop' and @placeholder = 'Start typing and select address' and @name = 'renter[next_of_kin_home_address]']</value>
      <webElementGuid>b4e7ef80-12e5-423e-afed-fbf6e2e5c333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
