<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referencing - Next of Kin - Post code field</name>
   <tag></tag>
   <elementGuidId>fceacedf-4491-4c9e-b550-72cd11dd7b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address_post_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='address_post_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d707d93f-1871-4cc7-94e6-44e25d3300ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2540bb06-d29e-4422-b3f7-d715730b8a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address_post_code</value>
      <webElementGuid>0ffdafbd-06c9-4c1c-ac59-6e5682ba32c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>ba198f7b-1944-428f-b3ea-ad794ac1fd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>6d7a0f69-aa75-41f4-8fd2-d98a46878706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[address_post_code]</value>
      <webElementGuid>928289e1-801c-4df8-bc5b-d4965af0641d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_post_code&quot;)</value>
      <webElementGuid>95d40e5a-ffb3-4239-80e2-723e773c4994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='address_post_code']</value>
      <webElementGuid>d9fb27ce-6990-4e00-9aac-90c7e8bf6750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='not_uk_address']/input[4]</value>
      <webElementGuid>a6b56519-f731-432b-86ea-32a0432ff9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[4]</value>
      <webElementGuid>edcd2413-72a5-4729-8cee-5dc0d3f0a4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'address_post_code' and @placeholder = 'Postcode' and @name = 'renter[address_post_code]']</value>
      <webElementGuid>6769f752-90c4-4c86-ad3d-372348de8025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
