<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Renter login page - Password</name>
   <tag></tag>
   <elementGuidId>4109b36c-7235-4eaf-8e78-372add768417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renter_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#renter_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97475217-d7d6-41df-8077-7347381c7496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password optional form-control input-lg</value>
      <webElementGuid>3cc9a70d-ecc8-4fe0-8e6a-f51a7f28148b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ca0bb680-62a2-4f4b-b28c-7f0bc0c574fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>7937bda2-9b45-439d-8567-0c208ab185dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>72</value>
      <webElementGuid>07dbf96a-a478-4e28-a0a0-aa3599474dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8a11f1f9-7353-4926-be21-6e70e7ca98a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[password]</value>
      <webElementGuid>30f44187-e639-4395-a693-6c185ebd0068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renter_password</value>
      <webElementGuid>84ee1b4b-7aa1-4965-94be-e6feaf7c95bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renter_password&quot;)</value>
      <webElementGuid>ac019595-2ffc-4105-a5ab-3be7329a8d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renter_password']</value>
      <webElementGuid>0758f9bd-dd9a-416c-b109-5064140ebd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_renter']/div/input[2]</value>
      <webElementGuid>96be1548-c660-4b8d-a6e8-40bfe8326496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>cbb4c4bd-252d-45c7-a7f3-ddd8b4f13abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password' and @type = 'password' and @name = 'renter[password]' and @id = 'renter_password']</value>
      <webElementGuid>c1cb8c19-1498-45ef-81c0-c081d57241d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
