<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TA_ViewDetails</name>
   <tag></tag>
   <elementGuidId>e6e364e3-299f-4b34-9f98-c84d0c9c5d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tenancy_agreement']/span/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ac2c9111-78e8-4d1d-939e-fba28bc4419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details</value>
      <webElementGuid>984566ea-b105-4e3a-8a2d-52072d7547c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenancy_agreement&quot;)/span[1]/a[1]/span[1]</value>
      <webElementGuid>772f62bf-edeb-449c-b4fc-a05ab6651bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tenancy_agreement']/span/a/span</value>
      <webElementGuid>26387c6a-faec-487c-8dc5-6f109a25ce39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome, emp1'])[1]/following::span[6]</value>
      <webElementGuid>e610b618-11b5-486a-a759-7a5d0020c582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View details'])[2]/preceding::span[1]</value>
      <webElementGuid>3d26c7ec-a9e5-4db3-a6ec-51136ac934db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View details']/parent::*</value>
      <webElementGuid>13e5b10c-7993-4145-a0b4-b193ca15c21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a/span</value>
      <webElementGuid>ec9dc794-d33d-4c29-b84f-d09365def5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'View details' or . = 'View details')]</value>
      <webElementGuid>8763fd9e-1f72-434c-a413-e1d608d0dd0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
