<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_StandingOrderView details</name>
   <tag></tag>
   <elementGuidId>c7681663-83e0-4838-bac8-943160d9f24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start_standing_order > span > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='start_standing_order']/span/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31213f0d-8d82-40f1-b283-c9ec44746c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details</value>
      <webElementGuid>655bce47-a6f6-4290-b45f-b985c1e79390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start_standing_order&quot;)/span[1]/a[1]/span[1]</value>
      <webElementGuid>d202b346-4266-4e6f-83e3-41196eaf5e77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='start_standing_order']/span/a/span</value>
      <webElementGuid>13ff5d01-1c96-46ea-8c51-881c854d5173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View details'])[3]/following::span[2]</value>
      <webElementGuid>897b1319-e360-442a-89b0-bc4e6efa84cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Council tax'])[1]/preceding::span[3]</value>
      <webElementGuid>12a0adf6-f68d-4712-91ed-131020f85eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Water supply'])[1]/preceding::span[4]</value>
      <webElementGuid>5a714652-83a1-49f9-a23a-cae0fc5ba5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span/a/span</value>
      <webElementGuid>67bcadb9-38f7-48eb-befb-e90df002e487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'View details' or . = 'View details')]</value>
      <webElementGuid>25acf626-df8a-4d78-843e-b1b2df694135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
