<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TA - Sign agreement field</name>
   <tag></tag>
   <elementGuidId>91b9ba90-c823-4570-87bd-017f6ba705e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='write_signature_canvas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#write_signature_canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9b4d2b0-9790-4b25-9705-16ecbf3b93c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>writesigncanvas_onChange()</value>
      <webElementGuid>aff4ba20-d194-4438-b8ad-753e0c7cec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>write_signature_canvas</value>
      <webElementGuid>5fca66cc-0cfb-44c0-9eb7-696150cf1bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>547195e1-4c49-4a99-a19a-d9c8f65cad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;write_signature_canvas&quot;)</value>
      <webElementGuid>59bd6c57-34d8-48ef-99d0-958c0f72fad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='write_signature_canvas']</value>
      <webElementGuid>c354a08b-8a0c-4c3c-af68-58e2a243ad8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='renter_write_signature']/input</value>
      <webElementGuid>b623ae56-1709-4e5e-9bc4-0c60d03f3e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f2f77b56-10e9-47ca-9d38-238d210d2f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'write_signature_canvas']</value>
      <webElementGuid>060f8024-ae3d-41a0-a0b5-47802d11fc3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
