<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work status - LLP Company - Job title</name>
   <tag></tag>
   <elementGuidId>44db9ec6-fb3b-4af4-a6c8-71eebe904fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='llpjobtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#llpjobtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc3627fd-9516-4e80-95b4-106fe948d669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>llpjobtitle</value>
      <webElementGuid>f4de27a2-7e19-454f-ab96-cb15015a05a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6678b023-035a-4522-999f-c54c4a24a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>ec5b1dc8-0060-492e-8181-414a0483d535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title</value>
      <webElementGuid>3cb98a47-02ea-4e7d-a53a-e37bf545ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_llp_job_title]</value>
      <webElementGuid>7a1135f1-01ad-4528-b553-0aa9ecf13f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;llpjobtitle&quot;)</value>
      <webElementGuid>5b1a2ce8-25f0-4cbf-87cf-cde5d9638777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='llpjobtitle']</value>
      <webElementGuid>e5515440-326a-4ad8-b6f2-ff5f3680eeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployedllp1']/input</value>
      <webElementGuid>84c4201b-b5a3-4655-ae33-8ab51b985f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>b17debb7-d267-4bd0-ac9d-afba08861f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'llpjobtitle' and @type = 'text' and @placeholder = 'Job title' and @name = 'renter[self_employed_llp_job_title]']</value>
      <webElementGuid>34405a52-7991-42da-a503-1ba5244a1257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
