<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work Status - Student - Income description</name>
   <tag></tag>
   <elementGuidId>4b3cd59b-a93d-44e3-b070-ee270c2707dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#additional_income_description_text_area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='additional_income_description_text_area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3c4d5892-0e82-4123-9007-71c47b51d722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Income description...</value>
      <webElementGuid>d9d5c6c6-2964-4547-b285-805313cb6e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roundcorners</value>
      <webElementGuid>932520b8-b640-44b5-9740-78c1c76d4522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>additional_income_description_text_area</value>
      <webElementGuid>aef5e47c-0e7f-48e1-b796-f27d2edac0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additional_income_description_text_area&quot;)</value>
      <webElementGuid>5db1ef1c-2e8d-4045-85f6-5131a57b5648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='additional_income_description_text_area']</value>
      <webElementGuid>a7c46eb9-1975-475e-b27c-4f94a01a9f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_renter_9955']/textarea</value>
      <webElementGuid>80fddb05-d597-4fa0-85ce-13c43dd65dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>69ea5228-0a48-4f1b-98ec-dadf87b3f0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Income description...' and @id = 'additional_income_description_text_area']</value>
      <webElementGuid>1b31c94f-5faf-4d91-a031-ff070355e945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
