<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work status - Studemt - Continue bt</name>
   <tag></tag>
   <elementGuidId>ef3c7333-fcf3-4fd6-8d17-2713472dad46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#continuebtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='continuebtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3574e26b-7b94-4bb2-847c-8f7602a4f416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkgreen btn-lg btn-block</value>
      <webElementGuid>f0e9bfc4-1020-402e-a9e9-0eb9eeba9342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>continuebtn</value>
      <webElementGuid>67a5f857-ff8c-4190-a297-8678e711e800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>ddeedb6f-61ca-4e68-9948-8451447d8f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continuebtn&quot;)</value>
      <webElementGuid>5789bc79-ffb3-4bc3-95cc-40539c32ccc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='continuebtn']</value>
      <webElementGuid>55b4e884-a088-4da5-abcc-b0f9bd650120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentsignupholder']/div[3]</value>
      <webElementGuid>cd897e22-e668-4123-87d0-84691d6d9cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Renter'])[1]/following::div[1]</value>
      <webElementGuid>4e79d673-b602-4d9a-a5f2-66ca7dd29f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::div[2]</value>
      <webElementGuid>5194661b-d41b-49ef-96a9-55f3ae5b0b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back a step'])[1]/preceding::div[1]</value>
      <webElementGuid>69024af8-db3b-4489-ad52-c16d735d1a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/preceding::div[2]</value>
      <webElementGuid>efc3fb4d-1a43-404b-9f15-ff0118d0726f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>69254715-cf54-4ffd-ba86-5de75ef153c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]</value>
      <webElementGuid>7a49fe6a-b8d9-47a7-8630-ad05e6790aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'continuebtn' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>c16280e2-b1df-4dee-8839-bca4117c7bbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
