<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work status - sole-trader - Job title</name>
   <tag></tag>
   <elementGuidId>17a71346-d11e-473b-b734-e6b629dc5ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='soletraderjobtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#soletraderjobtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>113e292a-899d-4564-937a-80557623dafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soletraderjobtitle</value>
      <webElementGuid>397f3403-1fe9-4144-af7a-2c60102b6d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e7bdc01-ca60-49f6-9e99-01681c0bfd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>string optional form-control input-lg</value>
      <webElementGuid>5dbeff59-1f26-49ae-a5d3-615eb505d69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job title</value>
      <webElementGuid>2b26ff98-6831-487e-b53d-3a47ac0affe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renter[self_employed_sole_trader_job_title]</value>
      <webElementGuid>cd8ccc53-8467-4268-b732-53b44772268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;soletraderjobtitle&quot;)</value>
      <webElementGuid>a5e66051-2946-41e3-b1cd-58bf84bc0162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='soletraderjobtitle']</value>
      <webElementGuid>fbb30146-fefa-4d05-82e1-a8bf76858028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='selfemployedsoletrader1']/input</value>
      <webElementGuid>efae2b8b-fb16-4ab6-881e-88d3e73365c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6783d325-c02b-4067-9e58-a16223c2a3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'soletraderjobtitle' and @type = 'text' and @placeholder = 'Job title' and @name = 'renter[self_employed_sole_trader_job_title]']</value>
      <webElementGuid>2cecae4e-f12d-460b-a5be-2ecd2a9216bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
