<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work stauts - Student Yes bt</name>
   <tag></tag>
   <elementGuidId>0a184e68-f870-4b48-8304-e2e8cd0e0205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#income_opt_yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='income_opt_yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ebbd7bc-bed0-4d1d-9925-21a083a62999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg btn-block</value>
      <webElementGuid>d0532e4a-50c4-4e25-af1b-c4d18de84c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>income_opt_yes</value>
      <webElementGuid>20e86c12-9ed7-4cf5-8b4d-9d968f750718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeOptYES();</value>
      <webElementGuid>974289b6-985f-4bfc-8d4c-dc519a3feedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>32800162-cdba-4a14-a0fb-c4328ce6496f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;income_opt_yes&quot;)</value>
      <webElementGuid>021ee7f3-c22d-4dcb-ab73-2135d20edad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='income_opt_yes']</value>
      <webElementGuid>373187d8-4c7a-4942-a9ea-20d1f7370792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_renter_9955']/div/div</value>
      <webElementGuid>5eb4c0a1-bbe7-4fb1-b75b-df6a0a79fe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/following::div[4]</value>
      <webElementGuid>54c1add0-da95-484e-ac21-d0d75a04bb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[2]/following::div[9]</value>
      <webElementGuid>17407caa-e53b-473f-87f2-ceaa3fb95899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[1]</value>
      <webElementGuid>15581e1e-c734-4f3a-a0e8-dd23afc5ff12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Renter'])[1]/preceding::div[4]</value>
      <webElementGuid>04ebdd1c-319b-4ff1-b5da-67b168c64f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>1d5f0082-cf8a-45e8-955b-c5c0ff69746b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>5c894d96-39d2-4784-9656-7b301e1fd77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'income_opt_yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>e1d88ad4-26df-4139-a43f-e48169783c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
